name: Prune Docker
runs:
  using: composite
  steps:
    - name: Prune Docker images (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        TIMEFORMAT='Docker pruning: %3R s'
        time sudo docker image prune --all --force || true

    - name: Prune Docker resources (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: docker system prune -af || true
