#![no_main]

use arbitrary::Arbitrary;
use commonware_codec::codec::FixedSize;
use commonware_cryptography::{ed25519, Signer};
use commonware_p2p::{
    simulated, Channel, Receiver as ReceiverTrait, Recipients, Sender as SenderTrait,
};
use commonware_runtime::{deterministic, Clock, IoBuf, Metrics, Quota, Runner};
use commonware_utils::NZUsize;
use libfuzzer_sys::fuzz_target;
use rand::Rng;
use std::{
    collections::{hash_map, HashMap, VecDeque},
    num::NonZeroU32,
    time::Duration,
};

const MAX_OPERATIONS: usize = 50;
const MAX_PEERS: usize = 16;
const MIN_PEERS: usize = 2;
const MAX_MSG_SIZE: u32 = 1024 * 1024;
const MAX_SLEEP_DURATION_MS: u64 = 1000;
const MSG_ID_SIZE: usize = core::mem::size_of::<u64>();

/// Default rate limit set high enough to not interfere with normal operation
const TEST_QUOTA: Quota = Quota::per_second(NonZeroU32::MAX);

struct ExpectedMsg {
    id: u64,
    generation: u64,
    message: IoBuf,
}

/// Operations that can be performed on the simulated p2p network during fuzzing.
#[derive(Debug, Arbitrary)]
enum Operation {
    /// Register a new channel for a peer to send/receive messages.
    RegisterChannel {
        /// Index of the peer registering the channel.
        peer_idx: u8,
        /// Channel identifier
        channel_id: u8,
    },
    /// Send a message from one peer to another on a specific channel.
    SendMessage {
        /// Index of the peer sending the message.
        peer_idx: u8,
        /// Channel to send the message on.
        channel_id: u8,
        /// Index of the recipient peer.
        to_idx: u8,
        /// Size of the message payload in bytes.
        msg_size: usize,
    },
    /// Attempt to receive pending messages from all peers.
    ReceiveMessages,
    /// Advance deterministic time before later operations.
    Sleep {
        /// Duration to sleep in milliseconds.
        duration_ms: u16,
    },
    /// Add or update a network link between two peers with specific characteristics.
    AddLink {
        /// Index of the sender peer.
        from_idx: u8,
        /// Index of the receiver peer.
        to_idx: u8,
        /// Base latency in milliseconds.
        latency_ms: u16,
        /// Latency jitter in milliseconds.
        jitter: u16,
        /// Success rate (0-255 maps to 0.0-1.0).
        success_rate: u8,
    },
    /// Remove a network link between two peers.
    RemoveLink {
        /// Index of the sender peer.
        from_idx: u8,
        /// Index of the receiver peer.
        to_idx: u8,
    },
}

/// Input generated by the fuzzer for testing the simulated p2p network.
#[derive(Debug)]
struct FuzzInput {
    /// Random seed for deterministic execution.
    seed: u64,
    /// Sequence of operations to execute on the network.
    ///
    /// Length is in the range [1, MAX_OPERATIONS].
    operations: Vec<Operation>,
    /// Number of peers to create in the network.
    ///
    /// Must be in the range [MIN_PEERS, MAX_PEERS].
    num_peers: u8,
}

impl<'a> Arbitrary<'a> for FuzzInput {
    fn arbitrary(u: &mut arbitrary::Unstructured<'a>) -> arbitrary::Result<Self> {
        let seed = u.arbitrary()?;
        let num_operations = u.int_in_range(1..=MAX_OPERATIONS)?;
        let mut operations = Vec::with_capacity(num_operations);
        for _ in 0..num_operations {
            operations.push(u.arbitrary()?);
        }
        let num_peers = u.int_in_range(MIN_PEERS..=MAX_PEERS)? as u8;
        Ok(FuzzInput {
            seed,
            operations,
            num_peers,
        })
    }
}

/// Main fuzzing entry point for testing the simulated p2p network.
///
/// Creates a deterministic network and executes a sequence of random operations,
/// verifying that received messages match expectations.
fn fuzz(input: FuzzInput) {
    let num_peers = input.num_peers;

    let p2p_cfg = simulated::Config {
        max_size: MAX_MSG_SIZE,
        disconnect_on_block: false,
        tracked_peer_sets: NZUsize!(1),
    };

    let executor = deterministic::Runner::seeded(input.seed);
    executor.start(|mut context| async move {
        // Generate peer identities
        let mut peer_pks = Vec::new();
        for _ in 0..num_peers {
            let private_key = ed25519::PrivateKey::from_seed(context.gen());
            peer_pks.push(private_key.public_key());
        }

        // Create the simulated network and oracle for controlling it
        let (network, oracle) = simulated::Network::new_with_peers(
            context.with_label("network"),
            p2p_cfg,
            peer_pks.iter().cloned(),
        )
        .await;
        let _network_handle = network.start();

        // Track registered channels: (peer_idx, channel_id) -> (sender, receiver)
        // Each peer can register multiple channels for message segregation
        // The receiver gets messages from ALL senders on that channel, not per-sender streams
        #[allow(clippy::type_complexity)]
        let mut channels: HashMap<
            (usize, u8),
            (
                commonware_p2p::simulated::Sender<ed25519::PublicKey, deterministic::Context>,
                commonware_p2p::simulated::Receiver<ed25519::PublicKey>,
            ),
        > = HashMap::new();

        // Track messages that may still be delivered: (to_idx, sender_pk, channel_id) -> messages.
        // The simulated network may drop messages, but an accepted message may also remain in
        // flight across link updates. FIFO is enforced only within a single link generation.
        let mut expected_msgs: HashMap<(usize, ed25519::PublicKey, u8), VecDeque<ExpectedMsg>> =
            HashMap::new();
        let mut skipped_msgs: HashMap<(usize, ed25519::PublicKey, u8), Vec<(u64, u64)>> =
            HashMap::new();
        let mut link_generations: HashMap<(usize, usize), u64> = HashMap::new();
        let mut next_msg_id = 0u64;

        for op in input.operations.into_iter() {
            match op {
                Operation::RegisterChannel {
                    peer_idx,
                    channel_id,
                } => {
                    // Normalize peer index to valid range
                    let idx = (peer_idx as usize) % peer_pks.len();

                    // Only register if not already registered
                    if let hash_map::Entry::Vacant(e) = channels.entry((idx, channel_id)) {
                        if let Ok((sender, receiver)) = oracle
                            .control(peer_pks[idx].clone())
                            .register(channel_id as u64, TEST_QUOTA)
                            .await
                        {
                            e.insert((sender, receiver));
                        }
                    }
                }

                Operation::SendMessage {
                    peer_idx,
                    channel_id,
                    to_idx,
                    msg_size,
                } => {
                    // Normalize sender and receiver indices to valid ranges
                    let from_idx = (peer_idx as usize) % peer_pks.len();
                    let to_idx = (to_idx as usize) % peer_pks.len();

                    // Clamp message size to not exceed max, accounting for channel and ID overhead.
                    let msg_size =
                        msg_size.clamp(0, MAX_MSG_SIZE as usize - Channel::SIZE - MSG_ID_SIZE);

                    // Skip if sender channel not registered
                    let Some((sender, _)) = channels.get_mut(&(from_idx, channel_id)) else {
                        continue;
                    };

                    // Generate a uniquely-tagged random message payload.
                    let id = next_msg_id;
                    next_msg_id = next_msg_id.wrapping_add(1);
                    let mut bytes = Vec::with_capacity(MSG_ID_SIZE + msg_size);
                    bytes.extend_from_slice(&id.to_le_bytes());
                    let payload_offset = bytes.len();
                    bytes.resize(MSG_ID_SIZE + msg_size, 0);
                    context.fill(&mut bytes[payload_offset..]);
                    let message = IoBuf::from(bytes);

                    // Attempt to send the message
                    // Note: Success only means accepted for transmission, not guaranteed delivery
                    let accepted = sender
                        .send(
                            Recipients::One(peer_pks[to_idx].clone()),
                            message.clone(),
                            true,
                        )
                        .await;

                    // Track the message only if the network accepted this recipient.
                    if let Ok(accepted) = accepted {
                        if accepted.iter().any(|pk| pk == &peer_pks[to_idx]) {
                            let generation =
                                *link_generations.get(&(from_idx, to_idx)).unwrap_or(&0);
                            expected_msgs
                                .entry((to_idx, peer_pks[from_idx].clone(), channel_id))
                                .or_default()
                                .push_back(ExpectedMsg {
                                    id,
                                    generation,
                                    message,
                                });
                        }
                    }
                }

                Operation::ReceiveMessages => {
                    // Attempt to receive one message from each registered receiver channel.
                    let mut receiver_channels: Vec<(usize, u8)> = channels.keys().copied().collect();
                    receiver_channels.sort_unstable();

                    // Each (to_idx, channel_id) is a distinct mailbox receiving from all senders
                    for (to_idx, channel_id) in receiver_channels {
                        let (_, receiver) = channels.get_mut(&(to_idx, channel_id)).unwrap();

                        // Try to receive one message without waiting for future deliveries.
                        commonware_macros::select! {
                            result = receiver.recv() => {
                                let Ok((sender_pk, message)) = result else {
                                    continue; // Receive error
                                };
                                if message.len() < MSG_ID_SIZE {
                                    panic!(
                                        "Message from sender {} to receiver {} on channel {} too short for ID. Message len: {}",
                                        sender_pk, to_idx, channel_id, message.len()
                                    );
                                }
                                let id = u64::from_le_bytes(
                                    message.as_ref()[..MSG_ID_SIZE]
                                        .try_into()
                                        .expect("slice length checked"),
                                );

                                // Find the expected queue for this sender-receiver-channel tuple
                                let expected_msgs_key = (to_idx, sender_pk.clone(), channel_id);
                                let fifo_skip = |id: u64| -> Option<u64> {
                                    skipped_msgs
                                        .get(&expected_msgs_key)
                                        .and_then(|skipped| {
                                            skipped
                                                .iter()
                                                .find(|(skipped_id, _)| *skipped_id == id)
                                        })
                                        .map(|(_, generation)| *generation)
                                };
                                let Some(queue) = expected_msgs.get_mut(&expected_msgs_key) else {
                                    if let Some(generation) = fifo_skip(id) {
                                        panic!(
                                            "FIFO violation from sender {} to receiver {} on channel {}. Message ID {} was already skipped in generation {}",
                                            sender_pk, to_idx, channel_id, id, generation
                                        );
                                    }
                                    panic!(
                                        "Expected queue not found for sender {} to receiver {} on channel {}. Message ID: {}, message len: {}",
                                        sender_pk, to_idx, channel_id, id, message.len()
                                    );
                                };

                                // Find message by unique ID. Messages can be dropped, delayed, or
                                // delivered after a link update, but any delivered payload must
                                // correspond to a prior accepted send for this sender/receiver/channel.
                                if let Some(pos) = queue.iter().position(|m| m.id == id) {
                                    let generation = queue[pos].generation;
                                    let first_same_generation = queue
                                        .iter()
                                        .position(|m| m.generation == generation)
                                        .expect("matched message has a generation");

                                    let skipped: Vec<_> = queue
                                        .drain(first_same_generation..pos)
                                        .map(|msg| (msg.id, msg.generation))
                                        .collect();
                                    if !skipped.is_empty() {
                                        skipped_msgs
                                            .entry(expected_msgs_key.clone())
                                            .or_default()
                                            .extend(skipped);
                                    }

                                    let expected = queue
                                        .remove(first_same_generation)
                                        .expect("matched message present");
                                    if expected.message != message {
                                        panic!(
                                            "Corrupted message from sender {} to receiver {} on channel {}. Message ID: {}, message len: {}",
                                            sender_pk, to_idx, channel_id, id, message.len()
                                        );
                                    }

                                    // Clean up empty queue
                                    if queue.is_empty() {
                                        expected_msgs.remove(&expected_msgs_key);
                                    }
                                } else {
                                    if let Some(generation) = fifo_skip(id) {
                                        panic!(
                                            "FIFO violation from sender {} to receiver {} on channel {}. Message ID {} was already skipped in generation {}",
                                            sender_pk, to_idx, channel_id, id, generation
                                        );
                                    }
                                    panic!(
                                        "Unexpected message from sender {} to receiver {} on channel {}. Message ID: {}, message len: {}",
                                        sender_pk, to_idx, channel_id, id, message.len()
                                    );
                                }
                            },
                            _ = context.sleep(Duration::ZERO) => {
                                continue; // No message is ready now.
                            }
                        }
                    }
                }

                Operation::Sleep { duration_ms } => {
                    let duration_ms = (duration_ms as u64).min(MAX_SLEEP_DURATION_MS);
                    context.sleep(Duration::from_millis(duration_ms)).await;
                }

                Operation::AddLink {
                    from_idx,
                    to_idx,
                    latency_ms,
                    jitter,
                    success_rate,
                } => {
                    // Normalize sender and receiver indices to valid ranges
                    let from_idx = (from_idx as usize) % peer_pks.len();
                    let to_idx = (to_idx as usize) % peer_pks.len();

                    // Create link with specified characteristics
                    // success_rate is normalized from u8 (0-255) to f64 (0.0-1.0)
                    let link = simulated::Link {
                        latency: Duration::from_millis(latency_ms as u64),
                        jitter: Duration::from_millis(jitter as u64),
                        success_rate: (success_rate as f64) / 255.0,
                    };
                    if oracle
                        .add_link(peer_pks[from_idx].clone(), peer_pks[to_idx].clone(), link)
                        .await
                        .is_ok()
                    {
                        // Generation 0 means no link has ever existed for the pair. Accepted sends
                        // should only observe generations created by successful AddLink calls.
                        *link_generations.entry((from_idx, to_idx)).or_default() += 1;
                    }
                }

                Operation::RemoveLink { from_idx, to_idx } => {
                    // Normalize sender and receiver indices to valid ranges
                    let from_idx = (from_idx as usize) % peer_pks.len();
                    let to_idx = (to_idx as usize) % peer_pks.len();

                    // Remove link to simulate network partition
                    let _ = oracle
                        .remove_link(peer_pks[from_idx].clone(), peer_pks[to_idx].clone())
                        .await;
                }
            }
        }
    });
}

fuzz_target!(|input: FuzzInput| {
    fuzz(input);
});
