//! Consistency checks across emulated execution backends.

use crate::{
    Operation, Simd,
    emulated::{EmulatedArmV9, EmulatedIceLake, EmulatedNeon, EmulatedScalar},
};
use core::fmt::Debug;

/// Checks that an operation produces the same result on every emulated backend.
///
/// Call this for each input generated by a test or fuzz harness. `operation` must
/// construct a fresh operation with equivalent inputs on each invocation, including
/// resetting any mutable state. It is called once per backend because execution
/// consumes the operation.
///
/// Include observable buffer changes in [`Operation::Output`] to compare them as well.
/// Agreement between backends does not establish correctness against an independent
/// reference implementation.
///
/// # Panics
///
/// Panics if any backend's output differs from the scalar output, or if constructing
/// or executing an operation panics.
///
/// # Examples
///
/// ```
/// use commonware_simd::{check_consistent, Operation};
/// use core::fmt::Debug;
///
/// fn check_case<O: Operation>(make_operation: impl FnMut() -> O)
/// where
///     O::Output: PartialEq + Debug,
/// {
///     check_consistent(make_operation);
/// }
/// ```
pub fn check_consistent<O: Operation>(mut operation: impl FnMut() -> O)
where
    O::Output: PartialEq + Debug,
{
    let expected = EmulatedScalar.execute(operation());
    assert_eq!(
        EmulatedIceLake.execute(operation()),
        expected,
        "EmulatedIceLake differs from EmulatedScalar"
    );
    assert_eq!(
        EmulatedArmV9.execute(operation()),
        expected,
        "EmulatedArmV9 differs from EmulatedScalar"
    );
    assert_eq!(
        EmulatedNeon.execute(operation()),
        expected,
        "EmulatedNeon differs from EmulatedScalar"
    );
}
