//! Consistency checks across emulated execution backends.

use crate::{
    Operation, Simd,
    emulated::{EmulatedArmV9, EmulatedIceLake, EmulatedNeon, EmulatedScalar},
};
use core::fmt::Debug;

/// Checks that an operation produces the same result on every emulated backend.
///
/// Call this for each input generated by a test or fuzz harness. `operation` must
/// construct a fresh operation with equivalent inputs on each invocation, including
/// resetting any mutable state. It is called once per backend because execution
/// consumes the operation.
///
/// All emulated backends must produce the same output type. Normalize any
/// backend-specific registers at this outer boundary.
///
/// Include observable buffer changes in [`Operation::Output`] to compare them as well.
/// Agreement between backends does not establish correctness against an independent
/// reference implementation.
///
/// # Panics
///
/// Panics if any backend's output differs from the scalar output, or if constructing
/// or executing an operation panics.
///
/// # Examples
///
/// ```
/// use commonware_simd::{check_consistent, Operation, Simd};
///
/// struct Add;
/// impl<S: Simd> Operation<S> for Add {
///     type Output = u32;
///     fn portable(self, simd: S) -> u32 {
///         let mut output = [0; 16];
///         simd.u32_store(simd.u32_add(simd.u32_splat(1), simd.u32_splat(2)), &mut output);
///         output[0]
///     }
/// }
/// check_consistent(|| Add);
/// ```
pub fn check_consistent<O, R>(mut operation: impl FnMut() -> O)
where
    O: Operation<EmulatedScalar, Output = R>
        + Operation<EmulatedIceLake, Output = R>
        + Operation<EmulatedArmV9, Output = R>
        + Operation<EmulatedNeon, Output = R>,
    R: PartialEq + Debug,
{
    let expected = EmulatedScalar.execute(operation());
    assert_eq!(
        EmulatedIceLake.execute(operation()),
        expected,
        "EmulatedIceLake differs from EmulatedScalar"
    );
    assert_eq!(
        EmulatedArmV9.execute(operation()),
        expected,
        "EmulatedArmV9 differs from EmulatedScalar"
    );
    assert_eq!(
        EmulatedNeon.execute(operation()),
        expected,
        "EmulatedNeon differs from EmulatedScalar"
    );
}
