name: Setup
inputs:
  additional-cache-key:
    description: "An additional cache key that is added alongside the automatic `job`-based cache key."
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Rust Cache
      uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}
        key: ${{ replace(replace(inputs.additional-cache-key, ' ', '-'), '/', '-') }}
        cache-on-failure: false
