name: Setup
inputs:
  additional-cache-key:
    description: "An additional cache key that is added alongside the automatic `job`-based cache key."
    required: false
    default: ""
runs:
  using: composite
  steps:
    # Use /mnt for Cargo builds on Linux (has ~70GB vs ~14GB on /)
    - name: Relocate Cargo directories to /mnt on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo mkdir -p /mnt/target /mnt/.cargo/bin
        sudo chown -R "$(id -u):$(id -g)" /mnt/target /mnt/.cargo
        echo "CARGO_TARGET_DIR=/mnt/target" >> "$GITHUB_ENV"
        echo "CARGO_HOME=/mnt/.cargo" >> "$GITHUB_ENV"
        echo "/mnt/.cargo/bin" >> "$GITHUB_PATH"
    - name: Normalize cache key
      id: cache-key
      shell: bash
      env:
        ADDITIONAL_CACHE_KEY: ${{ inputs.additional-cache-key }}
      run: |
        key="${ADDITIONAL_CACHE_KEY}"
        key="${key// /-}"
        key="${key//\//-}"
        key="${key//$'\n'/}"
        key="${key//$'\r'/}"
        echo "key=${key}" >> "$GITHUB_OUTPUT"
    - name: Setup rust cache
      uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}
        key: ${{ steps.cache-key.outputs.key }}
        cache-on-failure: false
        cache-workspace-crates: true
        cache-directories: ${{ env.CARGO_TARGET_DIR }}
