name: 'Setup'
inputs:
  rust-version:
    description: 'The version of Rust to use in cache keys'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.8
    - name: Configure sccache
      shell: bash
      run: |
        echo "RUSTC_WRAPPER=sccache" >> "$GITHUB_ENV"
        echo "SCCACHE_GHA_ENABLED=true" >> "$GITHUB_ENV"
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}-${{ inputs.rust-version }}
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}-${{ inputs.rust-version }}
