name: Setup
runs:
  using: composite
  steps:
    - name: Rust Cache
      uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      with:
        cache-on-failure: true
        save-if: ${{ github.ref == 'refs/heads/main' }}
