name: Setup
inputs:
  cache-key:
    description: "Additional cache key to differentiate matrix entries (e.g., partition)."
    required: false
    default: ""
  cache-workspace-crates:
    description: "Whether to cache workspace crate build artifacts (set to false to cache only dependencies)."
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Rust Cache
      uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      with:
        cache-on-failure: true
        save-if: ${{ github.ref == 'refs/heads/main' }}
        key: ${{ inputs.cache-key }}
        cache-workspace-crates: ${{ inputs.cache-workspace-crates }}
