comment:
  layout: "header, diff, files, footer"
  behavior: new
  require_changes: false
  require_head: false
  require_base: false
  hide_project_coverage: false

coverage:
  status:
    patch:
      default:
        threshold: 0.25%
        only_pulls: true
    project:
      default:
        threshold: 0.25%
        only_pulls: true
