[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200

[profile.ci]
verbosity = 4

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true 
