//! Crate-level differential tests and fuzzing operations.
//!
//! # Test vectors
//!
//! The RFC 9380 BLS12-381 and SHA-256 XMD vectors in
//! `cryptography/bls/src/test/vectors.rs` are generated by
//! `cryptography/bls/generate_test_vectors.py`. Regenerate or check them with:
//!
//! ```text
//! python3 cryptography/bls/generate_test_vectors.py
//! python3 cryptography/bls/generate_test_vectors.py --check
//! ```
//!
//! The generator verifies the pinned RFC's SHA-256 digest and validates every field width and
//! vector count before rewriting the fixture. Network access is required.

#[cfg(test)]
mod vectors;

use crate::{
    banderwagon::{G as BanderG, Scalar as BanderScalar},
    bls12381::{
        group::{G1, G2},
        pairing::{Gt, multi_pairing, pairing},
        recovery::{RecoveryError, RecoveryPlan},
        scalar::Scalar,
        signing::{BatchError, SigningKey, min_pk, min_sig},
    },
};
use alloc::{vec, vec::Vec};
use arbitrary::{Arbitrary, Unstructured};
#[cfg(not(miri))]
use commonware_codec::Encode as _;
use commonware_codec::{Copying, DecodeExt as _};
#[cfg(not(miri))]
use commonware_cryptography::banderwagon::{F as LegacyBanderScalar, G as LegacyBanderG};
use commonware_utils::TestRng;

const MIN_PK_DST: &[u8] = b"BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_POP_";
const MIN_SIG_DST: &[u8] = b"BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_POP_";

const INTERESTING_LENGTHS: [usize; 18] = [
    0, 1, 31, 32, 33, 47, 48, 49, 63, 64, 65, 95, 96, 97, 127, 128, 255, 256,
];

fn arbitrary_bytes(u: &mut Unstructured<'_>, limit: usize) -> arbitrary::Result<Vec<u8>> {
    let length = if u.ratio(3, 4)? {
        *u.choose(&INTERESTING_LENGTHS)?
    } else {
        u.int_in_range(0..=limit)?
    }
    .min(limit);
    Ok(match u.int_in_range(0u8..=3)? {
        0 => vec![0; length],
        1 => vec![u.arbitrary()?; length],
        2 => (0..length).map(|i| i as u8).collect(),
        _ => u.bytes(length)?.to_vec(),
    })
}

fn arbitrary_wide_scalar(u: &mut Unstructured<'_>) -> arbitrary::Result<[u8; 64]> {
    Ok(match u.int_in_range(0u8..=7)? {
        0 => [0; 64],
        1 => {
            let mut bytes = [0; 64];
            bytes[63] = 1;
            bytes
        }
        2 => [0xff; 64],
        3 => {
            let mut bytes = [0; 64];
            bytes[32..].copy_from_slice(&Scalar::ONE.neg().to_bytes());
            bytes
        }
        4 => {
            let mut bytes = [0; 64];
            let bit = usize::from(u.int_in_range(0u8..=255)?);
            bytes[63 - bit / 8] = 1 << (bit % 8);
            bytes
        }
        _ => u.arbitrary()?,
    })
}

fn arbitrary_g1_encoding(u: &mut Unstructured<'_>) -> arbitrary::Result<Vec<u8>> {
    let mut torsion = [0; 48];
    torsion[0] = if u.arbitrary()? { 0x80 } else { 0xa0 };
    let bytes = match u.int_in_range(0u8..=8)? {
        0 => G1::IDENTITY.to_bytes().to_vec(),
        1 => G1::generator().to_bytes().to_vec(),
        2 => torsion.to_vec(),
        3 => vec![0; 48],
        4 => vec![0xff; 48],
        5 => {
            let mut bytes = G1::generator().to_bytes();
            bytes[0] ^= 1 << u.int_in_range(5u8..=7)?;
            bytes.to_vec()
        }
        6 => u.arbitrary::<[u8; 48]>()?.to_vec(),
        _ => arbitrary_bytes(u, 128)?,
    };
    Ok(bytes)
}

fn arbitrary_g2_encoding(u: &mut Unstructured<'_>) -> arbitrary::Result<Vec<u8>> {
    let mut zero_x = [0; 96];
    zero_x[0] = if u.arbitrary()? { 0x80 } else { 0xa0 };
    let bytes = match u.int_in_range(0u8..=8)? {
        0 => G2::IDENTITY.to_bytes().to_vec(),
        1 => G2::generator().to_bytes().to_vec(),
        2 => zero_x.to_vec(),
        3 => vec![0; 96],
        4 => vec![0xff; 96],
        5 => {
            let mut bytes = G2::generator().to_bytes();
            bytes[0] ^= 1 << u.int_in_range(5u8..=7)?;
            bytes.to_vec()
        }
        6 => u.arbitrary::<[u8; 96]>()?.to_vec(),
        _ => arbitrary_bytes(u, 128)?,
    };
    Ok(bytes)
}

#[cfg(not(miri))]
fn blst_scalar_valid(bytes: &[u8]) -> bool {
    if bytes.len() != 32 {
        return false;
    }
    let mut scalar = blst::blst_scalar::default();
    // SAFETY: the length check proves that the input has the 32 bytes consumed by blst.
    unsafe {
        blst::blst_scalar_from_bendian(&mut scalar, bytes.as_ptr());
        blst::blst_scalar_fr_check(&scalar)
    }
}

#[cfg(not(miri))]
fn blst_g1_valid(bytes: &[u8]) -> bool {
    bytes.len() == 48
        && blst::min_sig::Signature::from_bytes(bytes).is_ok_and(|point| point.subgroup_check())
}

#[cfg(not(miri))]
fn blst_g2_valid(bytes: &[u8]) -> bool {
    bytes.len() == 96
        && blst::min_pk::Signature::from_bytes(bytes).is_ok_and(|point| point.subgroup_check())
}

#[cfg(not(miri))]
fn blst_hash_to_g1(message: &[u8], dst: &[u8]) -> [u8; 48] {
    let mut point = blst::blst_p1::default();
    let mut bytes = [0; 48];
    // SAFETY: all slices provide valid pointers and lengths, and the output buffers have the
    // exact sizes required by the hash-to-G1 and compression APIs.
    unsafe {
        blst::blst_hash_to_g1(
            &mut point,
            message.as_ptr(),
            message.len(),
            dst.as_ptr(),
            dst.len(),
            core::ptr::null(),
            0,
        );
        blst::blst_p1_compress(bytes.as_mut_ptr(), &point);
    }
    bytes
}

#[cfg(not(miri))]
fn blst_hash_to_g2(message: &[u8], dst: &[u8]) -> [u8; 96] {
    let mut point = blst::blst_p2::default();
    let mut bytes = [0; 96];
    // SAFETY: all slices provide valid pointers and lengths, and the output buffers have the
    // exact sizes required by the hash-to-G2 and compression APIs.
    unsafe {
        blst::blst_hash_to_g2(
            &mut point,
            message.as_ptr(),
            message.len(),
            dst.as_ptr(),
            dst.len(),
            core::ptr::null(),
            0,
        );
        blst::blst_p2_compress(bytes.as_mut_ptr(), &point);
    }
    bytes
}

fn assert_hash_to_curve(message: &[u8], dst: &[u8]) {
    let g1 = G1::hash_to_curve(message, dst);
    let g2 = G2::hash_to_curve(message, dst);
    #[cfg(not(miri))]
    assert_eq!(
        g1.to_bytes(),
        blst_hash_to_g1(message, dst),
        "G1 message={} dst={}",
        message.len(),
        dst.len()
    );
    #[cfg(not(miri))]
    assert_eq!(
        g2.to_bytes(),
        blst_hash_to_g2(message, dst),
        "G2 message={} dst={}",
        message.len(),
        dst.len()
    );
    assert!(!g1.is_identity());
    assert!(!g2.is_identity());
}

#[cfg(not(miri))]
fn blst_pairing(p: &G1, q: &G2) -> [u8; 576] {
    let mut p_affine = blst::blst_p1_affine::default();
    let mut q_affine = blst::blst_p2_affine::default();
    let mut miller = blst::blst_fp12::default();
    let mut target = blst::blst_fp12::default();
    let mut bytes = [0; 576];
    // SAFETY: native encodings are fixed-size canonical subgroup points, each output is initialized,
    // and the final serialization buffer has the 576 bytes required by blst.
    unsafe {
        assert_eq!(
            blst::blst_p1_uncompress(&mut p_affine, p.to_bytes().as_ptr()),
            blst::BLST_ERROR::BLST_SUCCESS,
        );
        assert_eq!(
            blst::blst_p2_uncompress(&mut q_affine, q.to_bytes().as_ptr()),
            blst::BLST_ERROR::BLST_SUCCESS,
        );
        blst::blst_miller_loop(&mut miller, &q_affine, &p_affine);
        blst::blst_final_exp(&mut target, &miller);
        blst::blst_bendian_from_fp12(bytes.as_mut_ptr(), &target);
    }
    bytes
}

fn check_decode(u: &mut Unstructured<'_>) -> arbitrary::Result<()> {
    let scalar = arbitrary_bytes(u, 64)?;
    let decoded_scalar = Scalar::decode(Copying(scalar.as_slice()));
    #[cfg(not(miri))]
    assert_eq!(decoded_scalar.is_ok(), blst_scalar_valid(&scalar),);
    if let Ok(decoded) = decoded_scalar {
        assert_eq!(decoded.to_bytes().as_slice(), scalar.as_slice());
    }

    let g1 = arbitrary_g1_encoding(u)?;
    let decoded_g1 = G1::decode(Copying(g1.as_slice()));
    #[cfg(not(miri))]
    assert_eq!(decoded_g1.is_ok(), blst_g1_valid(&g1));
    if let Ok(point) = decoded_g1 {
        assert_eq!(point.to_bytes().as_slice(), g1.as_slice());
    }

    let g2 = arbitrary_g2_encoding(u)?;
    let decoded_g2 = G2::decode(Copying(g2.as_slice()));
    #[cfg(not(miri))]
    assert_eq!(decoded_g2.is_ok(), blst_g2_valid(&g2));
    if let Ok(point) = decoded_g2 {
        assert_eq!(point.to_bytes().as_slice(), g2.as_slice());
    }
    Ok(())
}

fn check_group(u: &mut Unstructured<'_>) -> arbitrary::Result<()> {
    let a = Scalar::from_wide_bytes(&arbitrary_wide_scalar(u)?);
    let b = Scalar::from_wide_bytes(&arbitrary_wide_scalar(u)?);
    let sum = a.add(&b);

    let p = G1::generator().mul(&a);
    let q = G1::generator().mul(&b);
    assert_eq!(p.add(&q), G1::generator().mul(&sum));
    assert_eq!(p.sub(&q), G1::generator().mul(&a.sub(&b)));
    assert_eq!(p.double(), G1::generator().mul(&a.add(&a)));
    assert_eq!(p.add(&p.neg()), G1::IDENTITY);

    let p = G2::generator().mul(&a);
    let q = G2::generator().mul(&b);
    assert_eq!(p.add(&q), G2::generator().mul(&sum));
    assert_eq!(p.sub(&q), G2::generator().mul(&a.sub(&b)));
    assert_eq!(p.double(), G2::generator().mul(&a.add(&a)));
    assert_eq!(p.add(&p.neg()), G2::IDENTITY);

    #[cfg(not(miri))]
    if !sum.is_zero() {
        let key = blst::min_pk::SecretKey::from_bytes(&sum.to_bytes()).unwrap();
        assert_eq!(
            G1::generator().mul(&sum).to_bytes(),
            key.sk_to_pk().to_bytes()
        );
        let key = blst::min_sig::SecretKey::from_bytes(&sum.to_bytes()).unwrap();
        assert_eq!(
            G2::generator().mul(&sum).to_bytes(),
            key.sk_to_pk().to_bytes()
        );
    }
    Ok(())
}

fn check_hash(u: &mut Unstructured<'_>) -> arbitrary::Result<()> {
    let message = arbitrary_bytes(u, 256)?;
    let dst = arbitrary_bytes(u, 256)?;
    assert_hash_to_curve(&message, &dst);
    Ok(())
}

fn check_signing(u: &mut Unstructured<'_>) -> arbitrary::Result<()> {
    let mut scalar = Scalar::from_wide_bytes(&arbitrary_wide_scalar(u)?);
    if scalar.is_zero() {
        scalar = Scalar::ONE;
    }
    let key = SigningKey::from_bytes(&scalar.to_bytes()).unwrap();
    let message = arbitrary_bytes(u, 256)?;

    let native_public = min_pk::public_key(&key);
    let native_signature = min_pk::sign(&key, &message, MIN_PK_DST);
    #[cfg(not(miri))]
    let oracle = blst::min_pk::SecretKey::from_bytes(&key.to_bytes()).unwrap();
    #[cfg(not(miri))]
    assert_eq!(native_public.to_bytes(), oracle.sk_to_pk().to_bytes());
    #[cfg(not(miri))]
    assert_eq!(
        native_signature.to_bytes(),
        oracle.sign(&message, MIN_PK_DST, &[]).to_bytes(),
    );
    assert!(min_pk::verify(
        &native_public,
        &message,
        MIN_PK_DST,
        &native_signature
    ));

    let native_public = min_sig::public_key(&key);
    let native_signature = min_sig::sign(&key, &message, MIN_SIG_DST);
    #[cfg(not(miri))]
    let oracle = blst::min_sig::SecretKey::from_bytes(&key.to_bytes()).unwrap();
    #[cfg(not(miri))]
    assert_eq!(native_public.to_bytes(), oracle.sk_to_pk().to_bytes());
    #[cfg(not(miri))]
    assert_eq!(
        native_signature.to_bytes(),
        oracle.sign(&message, MIN_SIG_DST, &[]).to_bytes(),
    );
    assert!(min_sig::verify(
        &native_public,
        &message,
        MIN_SIG_DST,
        &native_signature
    ));
    Ok(())
}

fn check_pairing(u: &mut Unstructured<'_>) -> arbitrary::Result<()> {
    let a = Scalar::from_wide_bytes(&arbitrary_wide_scalar(u)?);
    let b = Scalar::from_wide_bytes(&arbitrary_wide_scalar(u)?);
    let p = G1::generator().mul(&a);
    let q = G2::generator().mul(&b);
    let actual = pairing(&p, &q);
    #[cfg(not(miri))]
    assert_eq!(actual.to_bytes(), blst_pairing(&p, &q));
    assert_eq!(
        actual,
        pairing(&G1::generator().mul(&a.mul(&b)), &G2::generator())
    );
    assert_eq!(
        multi_pairing(&[(p, q), (p.neg(), q), (G1::IDENTITY, q)]),
        Gt::IDENTITY,
    );
    Ok(())
}

fn arbitrary_scalar(u: &mut Unstructured<'_>) -> arbitrary::Result<Scalar> {
    Ok(Scalar::from_wide_bytes(&arbitrary_wide_scalar(u)?))
}

fn check_msm(u: &mut Unstructured<'_>) -> arbitrary::Result<()> {
    let count = u.int_in_range(0usize..=6)?;
    let mut point_scalars = Vec::with_capacity(count);
    let mut coefficients = Vec::with_capacity(count);
    for i in 0..count {
        let point_scalar = match u.int_in_range(0u8..=5)? {
            0 => Scalar::ZERO,
            1 if i != 0 => point_scalars[u.int_in_range(0..=i - 1)?],
            _ => arbitrary_scalar(u)?,
        };
        let coefficient = match u.int_in_range(0u8..=4)? {
            0 => Scalar::ZERO,
            1 => Scalar::ONE,
            2 => Scalar::ONE.neg(),
            _ => arbitrary_scalar(u)?,
        };
        point_scalars.push(point_scalar);
        coefficients.push(coefficient);
    }

    let linear = point_scalars
        .iter()
        .zip(&coefficients)
        .fold(Scalar::ZERO, |sum, (point, coefficient)| {
            sum.add(&point.mul(coefficient))
        });
    macro_rules! check_group {
        ($group:ty) => {{
            let points: Vec<_> = point_scalars
                .iter()
                .map(|scalar| <$group>::generator().mul(scalar))
                .collect();
            let naive = points
                .iter()
                .zip(&coefficients)
                .fold(<$group>::IDENTITY, |sum, (point, coefficient)| {
                    sum.add(&point.mul(coefficient))
                });
            let actual = <$group>::msm_vartime(&points, &coefficients).unwrap();
            assert_eq!(actual, naive);
            assert_eq!(actual, <$group>::generator().mul(&linear));

            let mismatched = if points.is_empty() {
                <$group>::msm_vartime(&points, &[Scalar::ONE])
            } else {
                <$group>::msm_vartime(&points, &coefficients[..coefficients.len() - 1])
            };
            assert!(mismatched.is_none());

            let mut witness = arbitrary_scalar(u)?;
            if witness.is_zero() {
                witness = Scalar::ONE;
            }
            let point = <$group>::generator().mul(&witness);
            let weight = arbitrary_scalar(u)?;
            assert_eq!(
                <$group>::msm_vartime(&[point], &[Scalar::ZERO]),
                Some(<$group>::IDENTITY),
            );
            assert_eq!(
                <$group>::msm_vartime(&[point, point], &[weight, weight.neg()]),
                Some(<$group>::IDENTITY),
            );
            assert_eq!(
                <$group>::msm_vartime(&[point, point], &[weight, Scalar::ONE]),
                Some(point.mul(&weight.add(&Scalar::ONE))),
            );
        }};
    }
    check_group!(G1);
    check_group!(G2);
    Ok(())
}

fn evaluate_polynomial(coefficients: &[Scalar], point: &Scalar) -> Scalar {
    coefficients
        .iter()
        .rev()
        .fold(Scalar::ZERO, |value, coefficient| {
            value.mul(point).add(coefficient)
        })
}

fn check_recovery(u: &mut Unstructured<'_>) -> arbitrary::Result<()> {
    let count = u.int_in_range(2usize..=5)?;
    let mut next = u.int_in_range(1u64..=32)?;
    let mut points = Vec::with_capacity(count);
    for _ in 0..count {
        points.push(Scalar::from_u64(next));
        next += u.int_in_range(1u64..=8)?;
    }
    if u.arbitrary()? {
        points.reverse();
    }

    let degree = u.int_in_range(0..=count - 1)?;
    let coefficients = (0..=degree)
        .map(|_| arbitrary_scalar(u))
        .collect::<arbitrary::Result<Vec<_>>>()?;
    let evaluations: Vec<_> = points
        .iter()
        .map(|point| evaluate_polynomial(&coefficients, point))
        .collect();
    let plan = RecoveryPlan::new(&points).unwrap();
    let g1: Vec<_> = evaluations
        .iter()
        .map(|value| G1::generator().mul(value))
        .collect();
    let g2: Vec<_> = evaluations
        .iter()
        .map(|value| G2::generator().mul(value))
        .collect();
    assert_eq!(
        plan.recover_g1(&g1),
        Ok(G1::generator().mul(&coefficients[0]))
    );
    assert_eq!(
        plan.recover_g2(&g2),
        Ok(G2::generator().mul(&coefficients[0]))
    );

    let mut zero = points.clone();
    zero[u.int_in_range(0..=count - 1)?] = Scalar::ZERO;
    assert!(matches!(
        RecoveryPlan::new(&zero),
        Err(RecoveryError::ZeroEvaluationPoint)
    ));
    let mut duplicate = points.clone();
    let source = u.int_in_range(0..=count - 1)?;
    let mut destination = u.int_in_range(0..=count - 2)?;
    if destination >= source {
        destination += 1;
    }
    duplicate[destination] = duplicate[source];
    assert!(matches!(
        RecoveryPlan::new(&duplicate),
        Err(RecoveryError::DuplicateEvaluationPoint),
    ));
    Ok(())
}

#[derive(Clone, Copy, Debug, Arbitrary, Eq, PartialEq)]
enum BatchCase {
    Valid,
    Invalid,
    Empty,
    Mismatch,
    Identity,
    Duplicate,
}

#[derive(Clone, Copy, Debug)]
enum BatchShape {
    General,
    SameMessage,
    SameSigner,
}

#[derive(Debug)]
struct BatchInput {
    case: BatchCase,
    scalars: Vec<Scalar>,
    messages: Vec<Vec<u8>>,
    shared_message: Vec<u8>,
    identity_signature: bool,
    challenge_seed: u64,
}

impl BatchInput {
    fn arbitrary(u: &mut Unstructured<'_>) -> arbitrary::Result<Self> {
        let case = u.arbitrary()?;
        let count = match case {
            BatchCase::Empty => 0,
            BatchCase::Duplicate => u.int_in_range(2usize..=3)?,
            _ => u.int_in_range(1usize..=3)?,
        };
        let mut scalars = Vec::with_capacity(count);
        let mut messages = Vec::with_capacity(count);
        for _ in 0..count {
            let mut scalar = arbitrary_scalar(u)?;
            if scalar.is_zero() {
                scalar = Scalar::ONE;
            }
            scalars.push(scalar);
            messages.push(arbitrary_bytes(u, 64)?);
        }
        if case == BatchCase::Duplicate {
            scalars[count - 1] = scalars[0];
            messages[count - 1] = messages[0].clone();
        }
        Ok(Self {
            case,
            scalars,
            messages,
            shared_message: arbitrary_bytes(u, 64)?,
            identity_signature: u.arbitrary()?,
            challenge_seed: u.arbitrary()?,
        })
    }
}

fn check_batch(u: &mut Unstructured<'_>, shape: BatchShape) -> arbitrary::Result<()> {
    let input = BatchInput::arbitrary(u)?;
    macro_rules! check_scheme {
        ($scheme:ident, $public_group:ty, $signature_group:ty, $dst:expr) => {{
            // Each shape starts with valid signatures so mutations isolate the rejection path.
            let mut public_keys = Vec::with_capacity(input.scalars.len());
            let mut signatures = Vec::with_capacity(input.scalars.len());
            for (index, scalar) in input.scalars.iter().enumerate() {
                let signer_scalar = match shape {
                    BatchShape::SameSigner => input.scalars[0],
                    _ => *scalar,
                };
                let key = SigningKey::from_bytes(&signer_scalar.to_bytes()).unwrap();
                let message = match shape {
                    BatchShape::SameMessage => input.shared_message.as_slice(),
                    _ => input.messages[index].as_slice(),
                };
                public_keys.push($scheme::public_key(&key));
                signatures.push($scheme::sign(&key, message, $dst));
            }

            if input.case == BatchCase::Invalid {
                let generator = <$signature_group>::generator();
                let corrupted = signatures[0].add(&generator);
                signatures[0] = if corrupted.is_identity() {
                    signatures[0].add(&generator.double())
                } else {
                    corrupted
                };
            } else if input.case == BatchCase::Identity {
                if input.identity_signature {
                    signatures[0] = <$signature_group>::IDENTITY;
                } else {
                    public_keys[0] = <$public_group>::IDENTITY;
                }
            } else if input.case == BatchCase::Mismatch {
                signatures.pop();
            }

            // Individual verification determines validity independently of the batch implementation.
            let messages: Vec<_> = match shape {
                BatchShape::SameMessage => (0..public_keys.len())
                    .map(|_| input.shared_message.as_slice())
                    .collect(),
                _ => input.messages.iter().map(Vec::as_slice).collect(),
            };
            let expected = public_keys.iter().zip(&messages).zip(&signatures).all(
                |((&public_key, &message), &signature)| {
                    $scheme::verify(&public_key, message, $dst, &signature)
                },
            );
            if matches!(input.case, BatchCase::Invalid | BatchCase::Identity) {
                assert!(!expected, "failed to invalidate {shape:?} {input:?}");
            }

            let mut rng = TestRng::new(input.challenge_seed);
            let actual = match shape {
                BatchShape::General => {
                    $scheme::batch_verify(&mut rng, &public_keys, &messages, $dst, &signatures)
                }
                BatchShape::SameMessage => $scheme::batch_verify_same_message(
                    &mut rng,
                    &public_keys,
                    &input.shared_message,
                    $dst,
                    &signatures,
                ),
                BatchShape::SameSigner => {
                    let public_key = public_keys
                        .first()
                        .copied()
                        .unwrap_or_else(<$public_group>::generator);
                    $scheme::batch_verify_same_signer(
                        &mut rng,
                        &public_key,
                        &messages,
                        $dst,
                        &signatures,
                    )
                }
            };

            // Empty, mismatched, and identity inputs retain their specific errors.
            match input.case {
                BatchCase::Empty => assert_eq!(actual, Err(BatchError::Empty)),
                BatchCase::Mismatch => assert_eq!(actual, Err(BatchError::LengthMismatch)),
                BatchCase::Identity => assert_eq!(actual, Err(BatchError::Identity)),
                BatchCase::Invalid => assert_eq!(actual, Err(BatchError::InvalidSignature)),
                BatchCase::Valid | BatchCase::Duplicate => {
                    assert!(expected, "failed to build valid {shape:?} {input:?}");
                    assert_eq!(actual, Ok(()), "{shape:?} {input:?}");
                }
            }
        }};
    }
    check_scheme!(min_pk, G1, G2, MIN_PK_DST);
    check_scheme!(min_sig, G2, G1, MIN_SIG_DST);
    Ok(())
}

fn check_banderwagon(u: &mut Unstructured<'_>) -> arbitrary::Result<()> {
    let wide = match u.int_in_range(0u8..=4)? {
        0 => [0; 64],
        1 => {
            let mut bytes = [0; 64];
            bytes[0] = 1;
            bytes
        }
        2 => [0xff; 64],
        _ => u.arbitrary()?,
    };
    let scalar = BanderScalar::from_wide_bytes(&wide);
    let point = BanderG::generator().mul(&scalar);
    #[cfg(not(miri))]
    let legacy_scalar = LegacyBanderScalar::decode(Copying(&scalar.to_bytes())).unwrap();
    #[cfg(not(miri))]
    let legacy_generator =
        LegacyBanderG::decode(Copying(&BanderG::generator().to_bytes())).unwrap();
    #[cfg(not(miri))]
    assert_eq!(
        point.to_bytes().as_slice(),
        (legacy_generator * &legacy_scalar).encode().as_ref(),
    );

    let encoding = match u.int_in_range(0u8..=5)? {
        0 => BanderG::IDENTITY.to_bytes().to_vec(),
        1 => BanderG::generator().to_bytes().to_vec(),
        2 => point.to_bytes().to_vec(),
        3 => vec![0; 32],
        4 => vec![0xff; 32],
        _ => arbitrary_bytes(u, 64)?,
    };
    let native = BanderG::decode(Copying(encoding.as_slice()));
    #[cfg(not(miri))]
    let legacy = LegacyBanderG::decode(Copying(encoding.as_slice()));
    #[cfg(not(miri))]
    assert_eq!(native.is_ok(), legacy.is_ok());
    if let Ok(native) = native {
        assert_eq!(native.to_bytes().as_slice(), encoding.as_slice());
        #[cfg(not(miri))]
        if let Ok(legacy) = legacy {
            assert_eq!(native.to_bytes().as_slice(), legacy.encode().as_ref());
        }
    }
    Ok(())
}

/// Fuzzing operations for composed public API invariants.
pub mod fuzz {
    use super::*;

    /// A composed public API fuzzing operation.
    #[derive(Clone, Copy, Debug, Arbitrary)]
    pub enum Plan {
        /// Compare canonical scalar and group decoding with blst.
        Decode,
        /// Exercise group operations and compare generator multiplication with blst.
        Group,
        /// Compare RFC 9380 hash-to-curve outputs with blst.
        Hash,
        /// Compare public keys and signatures with blst.
        Signing,
        /// Compare pairings with blst and exercise multi-pairing cancellation.
        Pairing,
        /// Compare G1 and G2 MSMs with naive and linear-equation oracles.
        Msm,
        /// Recover generated polynomials in G1 and G2 with one reusable plan.
        Recovery,
        /// Compare both general batch-verification schemes with individual verification.
        BatchGeneralMatchesIndividual,
        /// Compare both same-message batch-verification schemes with individual verification.
        BatchSameMessageMatchesIndividual,
        /// Compare both same-signer batch-verification schemes with individual verification.
        BatchSameSignerMatchesIndividual,
        /// Compare Banderwagon scalar multiplication and hostile decoding with commonware_cryptography.
        Banderwagon,
    }

    impl Plan {
        /// Runs the fuzzing operation using the remaining input.
        pub fn run(self, u: &mut Unstructured<'_>) -> arbitrary::Result<()> {
            match self {
                Self::Decode => check_decode(u),
                Self::Group => check_group(u),
                Self::Hash => check_hash(u),
                Self::Signing => check_signing(u),
                Self::Pairing => check_pairing(u),
                Self::Msm => check_msm(u),
                Self::Recovery => check_recovery(u),
                Self::BatchGeneralMatchesIndividual => check_batch(u, BatchShape::General),
                Self::BatchSameMessageMatchesIndividual => check_batch(u, BatchShape::SameMessage),
                Self::BatchSameSignerMatchesIndividual => check_batch(u, BatchShape::SameSigner),
                Self::Banderwagon => check_banderwagon(u),
            }
        }
    }

    #[cfg(test)]
    fn minifuzz(plan: Plan, search_limit: u64) {
        commonware_invariants::minifuzz::Builder::default()
            .with_seed(0)
            .with_search_limit(search_limit)
            .test(|u| plan.run(u));
    }

    #[cfg(test)]
    #[test]
    fn minifuzz_decode() {
        minifuzz(Plan::Decode, 100);
    }

    #[cfg(test)]
    #[test]
    fn minifuzz_group() {
        minifuzz(Plan::Group, 24);
    }

    #[cfg(test)]
    #[test]
    fn minifuzz_hash() {
        minifuzz(Plan::Hash, 24);
    }

    #[cfg(test)]
    #[test]
    fn minifuzz_signing() {
        minifuzz(Plan::Signing, 12);
    }

    #[cfg(test)]
    #[test]
    fn minifuzz_pairing() {
        minifuzz(Plan::Pairing, 12);
    }

    #[cfg(test)]
    #[test]
    fn minifuzz_msm() {
        minifuzz(Plan::Msm, 16);
    }

    #[cfg(test)]
    #[test]
    fn minifuzz_recovery() {
        minifuzz(Plan::Recovery, 12);
    }

    #[cfg(test)]
    #[test]
    fn minifuzz_batch_general_matches_individual() {
        minifuzz(Plan::BatchGeneralMatchesIndividual, 6);
    }

    #[cfg(test)]
    #[test]
    fn minifuzz_batch_same_message_matches_individual() {
        minifuzz(Plan::BatchSameMessageMatchesIndividual, 6);
    }

    #[cfg(test)]
    #[test]
    fn minifuzz_batch_same_signer_matches_individual() {
        minifuzz(Plan::BatchSameSignerMatchesIndividual, 6);
    }

    #[cfg(test)]
    #[test]
    fn minifuzz_banderwagon() {
        minifuzz(Plan::Banderwagon, 32);
    }
}

#[cfg(test)]
mod tests {
    use super::{
        vectors::{
            RFC9380_G1_DST, RFC9380_G1_RO, RFC9380_G2_DST, RFC9380_G2_RO, RFC9380_XMD_SHA256_32,
            RFC9380_XMD_SHA256_128, RFC9380_XMD_SHA256_DST,
        },
        *,
    };
    use crate::hash::expand_message_xmd;
    use commonware_codec::Encode;
    #[cfg(not(miri))]
    use commonware_utils::test_rng;
    #[cfg(not(miri))]
    use rand_core::Rng;

    #[test]
    fn rfc9380_g1_hash_to_curve_vectors() {
        assert_eq!(RFC9380_G1_RO.len(), 5);
        for vector in RFC9380_G1_RO {
            let (x, y) = G1::hash_to_curve(vector.message, RFC9380_G1_DST)
                .to_affine()
                .expect("RFC hash output is not the identity");
            assert_eq!(x.to_bytes(), vector.x);
            assert_eq!(y.to_bytes(), vector.y);
        }
    }

    #[test]
    fn rfc9380_g2_hash_to_curve_vectors() {
        assert_eq!(RFC9380_G2_RO.len(), 5);
        for vector in RFC9380_G2_RO {
            let (x, y) = G2::hash_to_curve(vector.message, RFC9380_G2_DST)
                .to_affine()
                .expect("RFC hash output is not the identity");
            assert_eq!(x.c0.to_bytes(), vector.x_c0);
            assert_eq!(x.c1.to_bytes(), vector.x_c1);
            assert_eq!(y.c0.to_bytes(), vector.y_c0);
            assert_eq!(y.c1.to_bytes(), vector.y_c1);
        }
    }

    #[test]
    fn rfc9380_expand_message_xmd_vectors() {
        assert_eq!(RFC9380_XMD_SHA256_32.len(), 5);
        for vector in RFC9380_XMD_SHA256_32 {
            assert_eq!(
                expand_message_xmd::<32>(vector.message, RFC9380_XMD_SHA256_DST),
                vector.output
            );
        }

        assert_eq!(RFC9380_XMD_SHA256_128.len(), 5);
        for vector in RFC9380_XMD_SHA256_128 {
            assert_eq!(
                expand_message_xmd::<128>(vector.message, RFC9380_XMD_SHA256_DST),
                vector.output
            );
        }
    }

    #[cfg(not(miri))]
    #[test]
    fn hash_to_curve_matches_blst() {
        const DST: &[u8] = b"BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_NUL_";
        for length in [0, 1, 31, 32, 63, 64, 65, 127, 128, 255, 256] {
            let message: Vec<_> = (0..length).map(|i| i as u8).collect();
            assert_hash_to_curve(&message, DST);
        }
        let mut rng = test_rng();
        for _ in 0..8 {
            let mut message = vec![0; (rng.next_u32() as usize) % 512];
            rng.fill_bytes(&mut message);
            assert_hash_to_curve(&message, DST);
        }
    }

    #[cfg(not(miri))]
    #[test]
    fn hash_to_curve_dst_boundaries_match_blst() {
        let message = b"RFC 9380 oversized DST";
        assert_hash_to_curve(b"", b"");
        for length in [0, 1, 254, 255, 256, 257, 1024] {
            let dst: Vec<_> = (0..length).map(|i| i as u8).collect();
            assert_hash_to_curve(message, &dst);
        }
    }

    #[test]
    fn canonical_identity_is_the_only_infinity_encoding() {
        let mut g1 = [0; 48];
        g1[0] = 0xc0;
        assert_eq!(G1::from_bytes(&g1), Some(G1::IDENTITY));
        assert_eq!(G1::decode(G1::IDENTITY.encode()).unwrap(), G1::IDENTITY);
        for invalid in [
            {
                let mut bytes = g1;
                bytes[0] |= 0x20;
                bytes
            },
            {
                let mut bytes = g1;
                bytes[47] = 1;
                bytes
            },
        ] {
            assert!(G1::from_bytes(&invalid).is_none());
        }

        let mut g2 = [0; 96];
        g2[0] = 0xc0;
        assert_eq!(G2::from_bytes(&g2), Some(G2::IDENTITY));
        assert_eq!(G2::decode(G2::IDENTITY.encode()).unwrap(), G2::IDENTITY);
        for invalid in [
            {
                let mut bytes = g2;
                bytes[0] |= 0x20;
                bytes
            },
            {
                let mut bytes = g2;
                bytes[95] = 1;
                bytes
            },
        ] {
            assert!(G2::from_bytes(&invalid).is_none());
        }
    }
}
