[package]
name = "restaking"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.9.2", features = ["full"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
alloy-node-bindings = "0.9.2"
rand = { workspace = true }