#![cfg(feature = "arbitrary")]

use commonware_clearing::bajillion::{
    admission::{
        Committee,
        bls12381::{Certificate, Vote},
    },
    boundary::{
        DepositBatch, DepositRecord, SignedWithdrawal, WithdrawalAction, WithdrawalBatch,
        WithdrawalBody, WithdrawalId,
    },
    challenge::{AccountLookup, Challenge, RangeLower, RowOpening, StateLookup, StateOpening},
    commitment::{MultiOpening, Opening, RangeOpening, VectorKind, VectorRoot},
    credit::{CreditRoot, ShardHead, ShardLookup, ShardOpening, ShardSet},
    payment::{Payment, PaymentContext, ReceiptBody, SendBody, SignedReceipt, SignedSend, TxId},
    state::{AccountRow, AccountState, Prefix, StateLeaf},
    transition::{
        Assignment, BatchId, ChangeRange, Close, CloseLimits, ExternalPayoutClaim, Header,
        LayoutRange, ProofSlice, RootBundle, SliceBoundary, StateRange, TerminalProof,
        WithdrawalClaim,
    },
};
use commonware_codec::conformance::CodecConformance;
use commonware_cryptography::sha256::Digest as Sha256Digest;
use commonware_cryptography_curve25519::signing::StrictVerifyingKey as VerifyingKey;

commonware_conformance::conformance_tests! {
    CodecConformance<Certificate> => 1024,
    CodecConformance<Vote> => 1024,
    CodecConformance<Committee> => 1024,
    CodecConformance<DepositRecord<VerifyingKey>> => 1024,
    CodecConformance<DepositBatch<VerifyingKey>> => 1024,
    CodecConformance<WithdrawalId<Sha256Digest>>,
    CodecConformance<WithdrawalAction>,
    CodecConformance<WithdrawalBody<Sha256Digest>>,
    CodecConformance<SignedWithdrawal<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<WithdrawalBatch<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<RowOpening<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<StateOpening<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<StateLookup<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<AccountLookup<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<RangeLower<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<Challenge<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<VectorKind>,
    CodecConformance<VectorRoot<Sha256Digest>>,
    CodecConformance<RootBundle<Sha256Digest>>,
    CodecConformance<Opening<Sha256Digest>> => 1024,
    CodecConformance<RangeOpening<Sha256Digest>> => 1024,
    CodecConformance<MultiOpening<Sha256Digest>> => 1024,
    CodecConformance<ShardHead<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<CreditRoot<Sha256Digest>>,
    CodecConformance<ShardSet<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<ShardOpening<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<ShardLookup<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<PaymentContext<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<TxId<Sha256Digest>>,
    CodecConformance<SendBody<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<SignedSend<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<ReceiptBody<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<SignedReceipt<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<Payment<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<AccountState>,
    CodecConformance<StateLeaf<VerifyingKey>> => 1024,
    CodecConformance<Prefix>,
    CodecConformance<AccountRow<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<Assignment<Sha256Digest>>,
    CodecConformance<BatchId<Sha256Digest>>,
    CodecConformance<Header<Sha256Digest>>,
    CodecConformance<CloseLimits>,
    CodecConformance<SliceBoundary>,
    CodecConformance<LayoutRange<Sha256Digest>> => 1024,
    CodecConformance<ChangeRange<VerifyingKey, Sha256Digest>> => 256,
    CodecConformance<StateRange<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<TerminalProof<Sha256Digest>> => 1024,
    CodecConformance<ExternalPayoutClaim<VerifyingKey, Sha256Digest>> => 256,
    CodecConformance<WithdrawalClaim<VerifyingKey, Sha256Digest>> => 256,
    CodecConformance<ProofSlice<VerifyingKey, Sha256Digest>> => 256,
    CodecConformance<Close<VerifyingKey, Sha256Digest>> => 256,
}
