#![cfg(feature = "arbitrary")]

use commonware_clearing::bajillion::{
    admission::{
        Committee,
        bls12381::{Certificate, Vote},
    },
    boundary::{
        DepositBatch, DepositRecord, SignedWithdrawal, WithdrawalAction, WithdrawalBatch,
        WithdrawalBody, WithdrawalId,
    },
    challenge::{
        AccountLookup, AckWitness, Challenge, ChangeAbsence, ChangeOpening, EntryWitness,
        HigherEntryLookup, StateAbsence, StateLookup, StateOpening, StateValueOpening,
    },
    commitment::{MultiOpening, Opening, RangeOpening, VectorKind, VectorRoot},
    payment::{EntryReceipt, PaymentContext, SendAuthorization, VectorAck, VectorSendBody},
    settlement::SettlementChain,
    state::{
        AccountChange, AccountRow, AccountState, ChangeGuard, ChangeValue, ChangeValueCore, Prefix,
        SettlementOutput, StateLeaf,
    },
    transition::{
        Assignment, BatchId, CloseLimits, CoverageRange, ExternalPayoutClaim, Header, ProofSlice,
        RootBundle, SliceBoundary, TerminalProof, WithdrawalClaim, WithdrawalOutput,
    },
    vector::{OutEntry, OutTipLookup, OutVector, TransposeEntry},
};
use commonware_codec::conformance::CodecConformance;
use commonware_cryptography::{Sha256, sha256::Digest as Sha256Digest};
use commonware_cryptography_curve25519::signing::StrictVerifyingKey as VerifyingKey;

commonware_conformance::conformance_tests! {
    CodecConformance<Certificate> => 1024,
    CodecConformance<Vote> => 1024,
    CodecConformance<Committee> => 1024,
    CodecConformance<DepositRecord<VerifyingKey>> => 1024,
    CodecConformance<DepositBatch<VerifyingKey>> => 1024,
    CodecConformance<WithdrawalId<Sha256Digest>>,
    CodecConformance<WithdrawalAction>,
    CodecConformance<WithdrawalBody<Sha256Digest>>,
    CodecConformance<SignedWithdrawal<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<WithdrawalBatch<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<ChangeOpening<Sha256Digest>> => 1024,
    CodecConformance<ChangeAbsence<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<StateOpening<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<StateValueOpening<Sha256Digest>> => 1024,
    CodecConformance<StateAbsence<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<StateLookup<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<AccountLookup<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<AckWitness<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<EntryWitness<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<HigherEntryLookup<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<Challenge<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<VectorKind>,
    CodecConformance<VectorRoot<Sha256Digest>>,
    CodecConformance<RootBundle<Sha256Digest>>,
    CodecConformance<Opening<Sha256Digest>> => 1024,
    CodecConformance<RangeOpening<Sha256Digest>> => 1024,
    CodecConformance<MultiOpening<Sha256Digest>> => 1024,
    CodecConformance<PaymentContext<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<VectorSendBody<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<SendAuthorization<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<VectorAck<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<EntryReceipt<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<OutEntry<VerifyingKey>>,
    CodecConformance<OutVector<VerifyingKey>> => 1024,
    CodecConformance<OutTipLookup<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<TransposeEntry<VerifyingKey>>,
    CodecConformance<AccountState>,
    CodecConformance<StateLeaf<VerifyingKey>> => 1024,
    CodecConformance<Prefix>,
    CodecConformance<SettlementOutput>,
    CodecConformance<ChangeValueCore<Sha256Digest>> => 1024,
    CodecConformance<ChangeValue<Sha256Digest>> => 1024,
    CodecConformance<ChangeGuard<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<AccountChange<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<AccountRow<VerifyingKey, Sha256Digest>> => 1024,
    CodecConformance<Assignment<Sha256Digest>>,
    CodecConformance<BatchId<Sha256Digest>>,
    CodecConformance<Header<Sha256Digest>>,
    CodecConformance<CloseLimits>,
    CodecConformance<SliceBoundary>,
    CodecConformance<CoverageRange<Sha256Digest>> => 1024,
    CodecConformance<WithdrawalOutput> => 1024,
    CodecConformance<TerminalProof<Sha256Digest>> => 1024,
    CodecConformance<ExternalPayoutClaim<VerifyingKey, Sha256Digest>> => 256,
    CodecConformance<WithdrawalClaim<Sha256Digest>> => 256,
    CodecConformance<ProofSlice<VerifyingKey, Sha256Digest>> => 256,
    CodecConformance<SettlementChain<Sha256, VerifyingKey>> => 256,
}
