[package]
name = "commonware-golden"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
# bulletproofs = { version = "5.0.0", features = ["yoloproofs"] }
rand.workspace = true
bytes.workspace = true
serde.workspace = true
futures.workspace = true
tracing.workspace = true
thiserror.workspace = true
governor.workspace = true
rand_core.workspace = true
serde_json.workspace = true
commonware-p2p.workspace = true
commonware-codec.workspace = true
commonware-utils.workspace = true
commonware-macros.workspace = true
prometheus-client.workspace = true
commonware-runtime.workspace = true
commonware-storage.workspace = true
commonware-resolver.workspace = true
commonware-broadcast.workspace = true
commonware-consensus.workspace = true
commonware-cryptography.workspace = true
clap = { workspace = true, features = ["derive"] }
