[package]
name = "commonware-stream"
edition.workspace = true
publish = true
version.workspace = true
license.workspace = true
description = "Exchange messages over arbitrary transport."
readme = "README.md"
homepage.workspace = true
repository = "https://github.com/commonwarexyz/monorepo/tree/main/stream"
documentation = "https://docs.rs/commonware-stream"

[lints]
workspace = true

[dependencies]
commonware-codec.workspace = true
commonware-cryptography = { workspace = true, features = ["std"] }
commonware-formatting.workspace = true
commonware-macros = { workspace = true, features = ["std"] }
commonware-runtime.workspace = true
commonware-utils.workspace = true
futures.workspace = true
rand_core.workspace = true
thiserror.workspace = true

[dev-dependencies]
commonware-conformance.workspace = true
commonware-math.workspace = true
rand.workspace = true

[features]
arbitrary = [
	"commonware-codec/arbitrary",
	"commonware-cryptography/arbitrary",
	"commonware-runtime/arbitrary",
	"commonware-utils/arbitrary",
]

[lib]
bench = false
