#!/usr/bin/env python3
"""evaluate.py: the exec-only optimizer on the frozen held-out set (run.sh step 2).

  evaluate.py --work DIR --eval BIN [--heavy HEAVY]

For every H1 function (sandblaster/bench/heldout/h1/src/lib.rs, all 30)
it writes a DSL root lifting H1's file in place with `items = "<fn>"`
(the reading of h1/h1.sbmir, extracted by run.sh) and runs `heldout_eval`
on it (sandblaster/front/examples/heldout_eval.rs: driver::check, exec-only
elaboration, the always-on optimizer with user alternatives excluded, the
in-place lowering and its lifted round trip). For H2 it runs the frozen
root of each sampled function (h2/roots/<slug>/mod.rs) the same way.

Then one more root lifts H1 with `items` = every H1 function whose own run
passed the front end, so that one lowered copy holds every rewrite; it is
written to gen/h1.rs (the `optimized` subject). H2's lowered copies give
gen/h2_opt.rs (items.py). Each function's record, and the union run, go to
DIR/eval.json; nothing here reads a timing.

No optimizer setting is passed: the run is the production optimizer
(OptOptions::default, strict off so a failure is recorded, not fatal) with
only `exclude_user_rewrites` set (there are no user alternatives in the
held-out set; the option makes sure of it).
"""
import argparse
import json
import os
import re
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "../../.."))
HELDOUT = os.path.join(REPO, "sandblaster/bench/heldout")
H1_SRC = os.path.join(HELDOUT, "h1/src/lib.rs")
H1_MIR = os.path.join(HERE, "h1/h1.sbmir")

sys.path.insert(0, HERE)
import items as items_mod  # noqa: E402


def h1_functions():
    """The public functions of H1, in file order."""
    s = items_mod.strip(open(H1_SRC).read())
    # module level only: stop at the test module
    s = s[: s.find("#[cfg(test)]")] if "#[cfg(test)]" in s else s
    return re.findall(r"(?m)^pub fn (\w+)", s)


def h2_functions():
    """[(slug, kernel name, root, file, item)] from the held-out manifest."""
    try:
        import tomllib
    except ImportError:  # pragma: no cover
        raise SystemExit("python >= 3.11 needed (tomllib)")
    m = tomllib.load(open(os.path.join(HELDOUT, "manifest.toml"), "rb"))
    out = []
    for f in m["h2"]["function"]:
        out.append((f["slug"], f["kernel_name"], os.path.join(HELDOUT, "h2", f["root"]), f["file"], f["id"].rsplit("::", 1)[1]))
    return out


def env():
    e = dict(os.environ)
    e.update(HEAVY_SLOTS="2", CARGO_BUILD_JOBS="4", SANDBLASTER_MEM_LIMIT_GB="6", SANDBLASTER_GATE_WORKERS="2")
    e.pop("SANDBLASTER_STRICT_OPT", None)
    return e


def write_root(d, item_list):
    os.makedirs(d, exist_ok=True)
    mir = os.path.relpath(H1_MIR, d)
    src = os.path.relpath(H1_SRC, d)
    uses = "".join(f"pub use h1::{i};\n" for i in item_list)
    text = (
        "//! Held-out evaluation root (generated by sandblaster/bench/heldout-harness/evaluate.py).\n"
        "#![forbid(unsafe_code)]\n\n"
        f'#[lift(mir = "{mir}", in_place, items = "{", ".join(item_list)}")]\n'
        f'#[path = "{src}"]\n'
        "pub mod h1;\n\n" + uses
    )
    p = os.path.join(d, "mod.rs")
    open(p, "w").write(text)
    return p


def run(args, root, out_dir, prefixes):
    cmd = ([args.heavy] if args.heavy else []) + [args.eval, root, out_dir] + prefixes
    t = time.time()
    p = subprocess.run(cmd, cwd=REPO, env=env(), capture_output=True, text=True)
    secs = round(time.time() - t, 1)
    line = next((l for l in p.stdout.splitlines() if l.startswith("{")), None)
    if line is None:
        return {"front_end": False, "errors": "heldout_eval did not finish (exit %s): %s" % (p.returncode, p.stderr[-800:]), "secs": secs}
    r = json.loads(line)
    r["secs"] = secs
    return r


def summarize(r, name):
    """One function's record: stage reached, outcome, rung, lowering, reason."""
    rec = {"function": name, "secs": r.get("secs")}
    if not r.get("front_end"):
        errs = [l for l in r.get("errors", "").splitlines() if "error[" in l] or [r.get("errors", "")]
        rec.update(stage="reader", changed=False, reason=re.sub(r"\S*/mono-wt/", "", errs[0]).strip())
        return rec
    defs = [d for d in r["defs"] if d["name"] == name]
    if not defs:
        rec.update(stage="elaboration", changed=False, reason="no definition named %s%s" % (name, (": " + r["elab_errors"][:300]) if r.get("elab_errors") else ""))
        return rec
    if defs[0]["status"] != "Checked":
        obs = [o for o in r.get("unproven", []) if o["def"] == name]
        why = "; ".join("%s obligation %s: %s" % (o["kind"], o["status"].split("(")[0], " ".join(o["goal"].split())[:160]) for o in obs[:3])
        rec.update(stage="elaboration", changed=False, reason="exec-only elaboration: %s%s" % (defs[0]["status"][:400], (" (" + why + ")") if why else ""), unproven=obs)
        return rec
    fn = next((f for f in r["fns"] if f["name"] == name and f["set"] is None), None)
    low = next((x for m in r["modules"] for x in m["records"] if x["function"] == name), None)
    rec["optimizer"] = fn
    rec["lowering"] = low
    if fn is None:
        rec.update(stage="optimizer", changed=False, reason="the optimizer has no report for it")
        return rec
    rec["outcome"] = fn["outcome"]
    rec["rung"] = fn["rung"]
    if low and low.get("lowered"):
        rec.update(stage="lowered", changed=True, origin=low["origin"], reason="lowered: rung %s, portable cost %s -> %s milli-cycles" % (low["rung"], low["cost_source"], low["cost_residual"]))
    else:
        why = low["reason"] if low else "no lowering record"
        if fn["outcome"] != "Specialized":
            why = "optimizer: %s%s" % ("FAILURE " if fn["failure"] else "", fn["reason"])
        rec.update(stage="kept", changed=False, reason=why)
    return rec


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--work", required=True)
    ap.add_argument("--eval", required=True)
    ap.add_argument("--heavy", default="")
    ap.add_argument("--only", nargs="*")
    args = ap.parse_args()
    os.makedirs(os.path.join(args.work, "out"), exist_ok=True)
    fns = h1_functions()
    assert len(fns) == 30, f"H1 has {len(fns)} public functions, the manifest says 30"
    result = {"h1": [], "h2": [], "union": None}
    for f in fns:
        if args.only and f not in args.only:
            continue
        root = write_root(os.path.join(args.work, "roots", f), [f])
        r = run(args, root, os.path.join(args.work, "out", f), [f"crate::h1::{f}"])
        json.dump(r, open(os.path.join(args.work, "out", f + ".json"), "w"), indent=1)
        rec = summarize(r, f"crate::h1::{f}")
        rec["set"] = "H1"
        result["h1"].append(rec)
        print(f"[H1] {f}: {rec['stage']}: {rec['reason'][:160]}", flush=True)
    for slug, kname, root, file, item in h2_functions():
        r = run(args, root, os.path.join(args.work, "out", slug), [kname])
        json.dump(r, open(os.path.join(args.work, "out", slug + ".json"), "w"), indent=1)
        rec = summarize(r, kname)
        rec.update(set="H2", slug=slug, file=file, item=item)
        result["h2"].append(rec)
        print(f"[H2] {slug} {kname}: {rec['stage']}: {rec['reason'][:160]}", flush=True)
    # the union root: one lowered copy with every H1 rewrite
    passed = [r["function"].rsplit("::", 1)[1] for r in result["h1"] if r["stage"] != "reader"]
    gen = os.path.join(HERE, "gen")
    os.makedirs(gen, exist_ok=True)
    h1_gen = os.path.join(gen, "h1.rs")
    if passed and not args.only:
        root = write_root(os.path.join(args.work, "roots", "_union"), passed)
        r = run(args, root, os.path.join(args.work, "out", "_union"), [f"crate::h1::{f}" for f in passed])
        json.dump(r, open(os.path.join(args.work, "out", "_union.json"), "w"), indent=1)
        result["union"] = {"items": passed, "front_end": r.get("front_end"), "errors": r.get("errors"), "records": [summarize(r, f"crate::h1::{f}") for f in passed] if r.get("front_end") else []}
        lowered = [m["written"] for m in r.get("modules", []) if m["file"].endswith("h1/src/lib.rs")]
        if lowered:
            open(h1_gen, "w").write(open(lowered[0]).read())
        else:
            open(h1_gen, "w").write(open(H1_SRC).read())
            result["union"]["note"] = "no lowered copy: gen/h1.rs is the source as-is"
    elif not args.only:
        open(h1_gen, "w").write(open(H1_SRC).read())
        result["union"] = {"items": [], "note": "no H1 function passed the reader: gen/h1.rs is the source as-is"}
    # H2: each sampled function's text from its lowered copy (the source when nothing was lowered)
    parts = []
    for rec in result["h2"]:
        out = os.path.join(args.work, "out", rec["slug"])
        stem = os.path.splitext(os.path.basename(rec["file"]))[0]
        lowered = os.path.join(out, f"{stem}.lowered.rs")
        src = lowered if os.path.exists(lowered) else os.path.join(REPO, rec["file"])
        rec["opt_text_from"] = "lowered copy" if src == lowered else "source (no lowered copy)"
        p = subprocess.run([sys.executable, os.path.join(HERE, "items.py"), src, rec["item"], "--helpers", "--label", f"the lowered copy of {rec['file']}" if src == lowered else rec["file"]], capture_output=True, text=True, check=True)
        parts.append(p.stdout)
    if not args.only:
        open(os.path.join(gen, "h2_opt.rs"), "w").write("\n".join(parts))
    json.dump(result, open(os.path.join(args.work, "eval.json"), "w"), indent=1)
    print(json.dumps({k: len(v) if isinstance(v, list) else bool(v) for k, v in result.items()}))


if __name__ == "__main__":
    main()
