//! Waiter identity and lifecycle state for tracked io_uring requests.
//!
//! This module manages independently generational waiter and ticket-completion
//! IDs, request lifecycle transitions, and outstanding-operation tracking.
//! Waiters own kernel-referenced request state only until terminal completion.
//! Ordinary op results remain parked in their waiter, while detached ticket
//! results move to [TicketCompletions] so their waiter slot can be recycled
//! before the ticket is consumed.

use super::{
    Tick, UserData,
    request::{Output, Request},
};
use crate::Error;
use io_uring::squeue::Entry as SqueueEntry;
use std::task::Waker;
use tracing::warn;

/// Stable waiter identity packed into SQE/CQE `user_data`.
///
/// Layout:
/// - bits 0..31: slot index
/// - bits 32..62: generation (31 bits, wraps at 2^31)
/// - bit 63: reserved as cancel-tag in completion `user_data`
///
/// The generation counter detects stale CQEs that arrive after a slot has been
/// recycled. In normal (non-cancel) operation this cannot happen: a slot is
/// only freed after its CQE is processed, so the slot cannot be reused before
/// the CQE is consumed. With cancellation, the original op CQE can arrive
/// before the cancel CQE. When this happens the slot is freed and may be
/// recycled while the cancel CQE is still pending. The generation check
/// discards that stale cancel CQE. The 31-bit generation wraps after ~2 billion
/// reuses of the same slot, but cancellation is run synchronously on the kernel
/// side (a CQE is always generated by the time the cancel request has been
/// submitted, see
/// <https://man7.org/linux/man-pages/man3/io_uring_prep_cancel.3.html#NOTES>),
/// so a wrap-around collision is not feasible in practice.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct WaiterId(UserData);

impl WaiterId {
    /// Number of low-order bits reserved for the waiter slot index.
    const INDEX_BITS: u32 = 32;
    /// Number of bits reserved for the generation field.
    const GENERATION_BITS: u32 = 31;
    /// Bitmask that extracts the waiter slot index from packed user data.
    const INDEX_MASK: UserData = (1u64 << Self::INDEX_BITS) - 1;
    /// Bitmask that extracts the 31-bit generation from packed user data.
    const GENERATION_MASK: UserData = (1u64 << Self::GENERATION_BITS) - 1;
    /// High-bit tag used to mark cancellation CQE user data.
    const CANCEL_TAG: UserData = 1u64 << 63;

    /// Build a waiter id from slot index and generation components.
    pub const fn new(index: u32, generation: u32) -> Self {
        let index = index as UserData;
        let generation = generation as UserData;
        Self((generation & Self::GENERATION_MASK) << Self::INDEX_BITS | index)
    }

    /// Return the slot index component of this waiter id.
    pub const fn index(self) -> u32 {
        (self.0 & Self::INDEX_MASK) as u32
    }

    /// Return the generation component of this waiter id.
    const fn generation(self) -> u32 {
        ((self.0 >> Self::INDEX_BITS) & Self::GENERATION_MASK) as u32
    }

    /// Return the waiter id for the same slot with incremented generation.
    const fn next_generation(self) -> Self {
        let generation = ((self.generation() as UserData).wrapping_add(1)) & Self::GENERATION_MASK;
        Self::new(self.index(), generation as u32)
    }

    /// Encode this waiter id as `user_data` for the operation SQE/CQE.
    ///
    /// This value contains only the packed waiter identity (slot + generation),
    /// with the cancel tag bit clear.
    pub const fn user_data(self) -> UserData {
        self.0
    }

    /// Encode this waiter id as `user_data` for the cancel SQE/CQE.
    ///
    /// This preserves the waiter identity and sets the high cancel-tag bit so
    /// completion handling can distinguish cancel CQEs from operation CQEs.
    pub const fn cancel_user_data(self) -> UserData {
        self.0 | Self::CANCEL_TAG
    }

    /// Decode `user_data` into waiter identity and cancel-tag state.
    ///
    /// The returned waiter id always has the cancel-tag bit stripped. The
    /// boolean reports whether that bit was set in the input value.
    const fn from_user_data(user_data: UserData) -> (Self, bool) {
        let is_cancel = (user_data & Self::CANCEL_TAG) != 0;
        (Self(user_data & !Self::CANCEL_TAG), is_cancel)
    }
}

/// Stable identity for a detached ticket's completion entry.
///
/// Completion generations are independent from waiter generations. A ticket
/// keeps this ID after admission and never observes the waiter ID that carries
/// its request through the kernel.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CompletionId {
    /// Completion-arena slot index.
    index: u32,
    /// Generation of the completion-arena slot at allocation time.
    ///
    /// Recycled slots advance this value so a stale ticket cannot address a
    /// later completion that uses the same index.
    generation: u32,
}

impl CompletionId {
    /// Build a completion ID from its slot index and generation.
    const fn new(index: u32, generation: u32) -> Self {
        Self { index, generation }
    }

    /// Return the completion-arena slot index.
    const fn index(self) -> u32 {
        self.index
    }

    /// Return the generation captured by this ID.
    #[cfg(test)]
    const fn generation(self) -> u32 {
        self.generation
    }

    /// Advance the generation for a recycled completion slot.
    ///
    /// The index remains reusable, but the old ID no longer validates against
    /// the replacement entry. Generation arithmetic wraps at `u32::MAX`.
    const fn next_generation(self) -> Self {
        Self::new(self.index, self.generation.wrapping_add(1))
    }
}

/// Why a request's cancellation was requested.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CancelReason {
    /// The request's deadline elapsed: the observer sees [Error::Timeout].
    ///
    /// Also used for drop-orphaned requests, whose parked result is never
    /// observed (the reason is immaterial there).
    Deadline,
    /// The runtime is shutting down: the observer sees [Error::Closed],
    /// distinguishing shutdown from an ordinary operation timeout or a
    /// genuine kernel failure.
    Shutdown,
}

impl CancelReason {
    /// The error a cancelled request surfaces to its observer.
    pub const fn into_error(self) -> Error {
        match self {
            Self::Deadline => Error::Timeout,
            Self::Shutdown => Error::Closed,
        }
    }
}

/// Lifecycle state of a tracked request.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WaiterState {
    /// Request is still tracked and has not transitioned to cancellation.
    Active {
        /// Absolute wheel tick by which the request must complete.
        ///
        /// If completion has not been observed by this tick, cancellation is
        /// requested. `None` means this request has no scheduled deadline yet,
        /// either because it carries none or because its first staging has not
        /// converted the deadline to a wheel tick.
        target_tick: Option<Tick>,
    },
    /// Cancellation was requested.
    ///
    /// If the request still has an operation SQE in flight, the loop stages an
    /// async cancel. If the request is only parked in the backlog, the loop
    /// completes it locally with the reason's error when that entry is
    /// revisited.
    CancelRequested {
        /// Why cancellation was requested (selects the observer's error).
        reason: CancelReason,
    },
}

/// Progress state of the logical request stored in a slot.
enum Lifecycle {
    /// The request is still progressing and owns all operation resources.
    Pending(Request),
    /// The terminal result is parked until the owning ordinary op takes it.
    ///
    /// The kernel has fully retired the operation before this state is
    /// entered, so the buffers inside the output are exclusively
    /// userspace-owned again.
    Ready(Output),
    /// A detached ticket's output has left the waiter and is ready to publish
    /// in its completion entry.
    ///
    /// This state exists only while the driver holds the op-state borrow that
    /// performs the terminal transition. The waiter is recycled before any
    /// external waker can run.
    TicketComplete,
}

/// Observer that owns the eventual result of a waiter.
enum Observer {
    /// An ordinary op future. Its waker stays with the waiter because its
    /// result is consumed from that same slot.
    Op(Option<Waker>),
    /// A detached ticket. Its waker lives in the separate completion arena,
    /// and terminal output moves there when the waiter completes.
    Ticket(CompletionId),
    /// The observer was dropped. Requests whose orphan policy stops progress
    /// cancel, while storage writes and syncs detach and keep running.
    Orphaned,
}

/// Non-orphaned terminal output after its waiter state is committed.
enum FinishedOutput {
    /// Output parked in an ordinary op waiter.
    Op { waker: Option<Waker> },
    /// Output leaving the waiter for a detached completion entry.
    Ticket {
        completion_id: CompletionId,
        output: Output,
    },
}

/// State for one tracked logical request.
struct Waiter {
    /// Stable identity of this waiter slot instance.
    id: WaiterId,
    /// Lifecycle state for the logical request stored in this slot.
    state: WaiterState,
    /// Whether the logical request currently has an operation SQE in flight.
    in_flight: bool,
    /// Owner of the eventual output.
    observer: Observer,
    /// Progress state and owned resources.
    lifecycle: Lifecycle,
}

/// Outcome produced when staging the next SQE for a waiter.
pub enum StageOutcome {
    /// The waiter was canceled while parked in the backlog and completed
    /// locally without emitting an SQE. This covers local deadline expiry
    /// (the observer sees timeout), local shutdown (the observer sees
    /// closed), and orphan retirement (no observer, the slot is freed).
    Complete {
        /// Waker to invoke outside any state borrow, when an ordinary op still
        /// observes the parked result.
        waker: Option<Waker>,
        /// Whether the slot was freed because its observer was already dropped.
        freed: bool,
    },
    /// A detached ticket reached a terminal state without emitting an SQE.
    /// Its output must be published before this waiter is recycled.
    Ticket {
        /// Waiter whose request reached the terminal state.
        waiter_id: WaiterId,
        /// Detached completion entry that receives the output.
        completion_id: CompletionId,
        /// Terminal request output.
        output: Output,
    },
    /// The waiter is still active and produced an SQE for submission.
    Submit(SqueueEntry),
}

/// Outcome produced when handling an operation CQE for a waiter.
pub enum CompletionOutcome {
    /// The CQE belonged to an async cancel SQE and was handled internally.
    Cancel,
    /// The logical request needs another SQE and should be placed back in the
    /// backlog.
    Requeue(WaiterId),
    /// The logical request reached a terminal state.
    ///
    /// An ordinary op result was parked in its waiter, or an orphaned result
    /// was dropped and its waiter freed.
    Complete {
        /// Waker to invoke outside any state borrow, if an op is waiting.
        waker: Option<Waker>,
        /// Active deadline tracking to remove from the timeout wheel, when
        /// completion happened before cancellation was requested.
        target_tick: Option<Tick>,
        /// Whether the slot was freed because its observer was already dropped.
        freed: bool,
    },
    /// A detached ticket reached a terminal state.
    ///
    /// The driver publishes `output` into `completion_id`, removes timeout
    /// accounting, and recycles `waiter_id` before invoking any waker.
    Ticket {
        /// Waiter whose kernel-owned request state is terminal.
        waiter_id: WaiterId,
        /// Detached completion entry that receives the output.
        completion_id: CompletionId,
        /// Terminal request output.
        output: Output,
        /// Active deadline tracking to remove from the timeout wheel.
        target_tick: Option<Tick>,
    },
}

/// Outcome produced when a waiter's observer is dropped.
pub enum DropOutcome {
    /// The parked result was dropped and the slot freed.
    Freed,
    /// The request was transitioned to cancellation.
    Cancel {
        /// Whether an async-cancel SQE must be staged because an operation
        /// SQE is in flight.
        needs_sqe: bool,
        /// Scheduled deadline tick leaving active timeout tracking, if any.
        target_tick: Option<Tick>,
    },
    /// The request keeps running to completion without an observer (storage
    /// writes and syncs preserve durability semantics on caller drop).
    Detached,
}

/// Outcome produced when a detached ticket is dropped.
pub enum CompletionDropOutcome {
    /// The request is still active in `waiter_id` and must follow its
    /// request-kind-specific orphan path.
    Pending {
        /// Active waiter linked from the removed completion entry.
        waiter_id: WaiterId,
        /// Stored task waker to drop after waiter wind-down is committed.
        waker: Option<Waker>,
    },
    /// The terminal output was dropped and the completion slot recycled.
    Ready,
}

/// Lifecycle of a detached ticket completion.
enum Completion {
    /// The waiter still owns the active request and its kernel resources.
    Pending {
        /// Waiter slot that owns the request until terminal completion.
        waiter_id: WaiterId,
        /// Ticket task waker retained until the output is published or dropped.
        waker: Option<Waker>,
    },
    /// Terminal userspace-owned output, independent from the recycled waiter slot.
    Ready(Output),
}

/// One detached ticket completion entry.
struct TicketCompletion {
    /// Generation-stamped identity used to reject stale ticket operations.
    id: CompletionId,
    /// Pending or ready lifecycle state for this completion.
    completion: Completion,
}

/// Independently generational arena for detached ticket completions.
///
/// The arena grows only to its high-water mark. Dropped or consumed entries
/// return to a free list and reuse their existing vector storage.
pub struct TicketCompletions {
    /// Completion entries indexed by [`CompletionId::index`]. A live entry is
    /// `Pending` while its waiter owns the request, then `Ready` while this
    /// arena owns the terminal output.
    entries: Vec<Option<TicketCompletion>>,
    /// Stack of generation-advanced IDs for recycled completion slots. Full-ID
    /// validation rejects tickets from an older generation of the same slot.
    free: Vec<CompletionId>,
    /// Number of entries in the `Ready` state. Pending entries are represented
    /// by their waiter and therefore are not counted here.
    ready: usize,
}

impl TicketCompletions {
    /// Create an empty completion arena with no allocated slots.
    pub const fn new() -> Self {
        Self {
            entries: Vec::new(),
            free: Vec::new(),
            ready: 0,
        }
    }

    /// Allocate a pending completion and admit its associated waiter.
    ///
    /// `insert_waiter` receives the generation-stamped completion ID before
    /// the completion entry is installed. It must insert a waiter that stores
    /// that ID as its reverse link. The waiter owns the request while the
    /// completion entry owns the ticket waker until publication or drop.
    ///
    /// A recycled slot keeps its vector allocation and receives its next
    /// generation. A fresh slot starts at generation zero.
    pub fn insert_pending(
        &mut self,
        waker: Waker,
        insert_waiter: impl FnOnce(CompletionId) -> WaiterId,
    ) -> (CompletionId, WaiterId) {
        let id = self.free.last().copied().unwrap_or_else(|| {
            let index = u32::try_from(self.entries.len()).expect("completion slot index overflow");
            CompletionId::new(index, 0)
        });
        let waiter_id = insert_waiter(id);
        let entry = TicketCompletion {
            id,
            completion: Completion::Pending {
                waiter_id,
                waker: Some(waker),
            },
        };
        let index = id.index() as usize;
        if index == self.entries.len() {
            self.entries.push(Some(entry));
        } else {
            let recycled = self
                .free
                .pop()
                .expect("reused completion missing from free list");
            assert_eq!(recycled, id, "completion free list order changed");
            let replaced = self.entries[index].replace(entry);
            assert!(replaced.is_none(), "free completion slot still occupied");
        }
        (id, waiter_id)
    }

    /// Publish a ticket's terminal output and return its task waker.
    ///
    /// The entry changes from `Pending` to `Ready`, transferring output
    /// ownership from the waiter to this arena. The associated waiter remains
    /// tracked until the caller removes deadline accounting and recycles it
    /// before invoking the returned waker.
    ///
    /// Panics if `completion_id` is stale or untracked, if the entry is already
    /// ready, or if its linked waiter does not equal `waiter_id`.
    pub fn publish_ready(
        &mut self,
        completion_id: CompletionId,
        waiter_id: WaiterId,
        output: Output,
    ) -> Option<Waker> {
        let entry = self.entry_mut(completion_id, "publish_ready");
        let Completion::Pending {
            waiter_id: pending_waiter,
            ..
        } = &entry.completion
        else {
            panic!("publish_ready called for ready completion");
        };
        assert_eq!(
            *pending_waiter, waiter_id,
            "publish_ready called with wrong waiter id"
        );
        let Completion::Pending { waker, .. } =
            std::mem::replace(&mut entry.completion, Completion::Ready(output))
        else {
            unreachable!("completion verified pending above");
        };
        self.ready += 1;
        waker
    }

    /// Take a ready output, or refresh the pending ticket waker.
    ///
    /// Taking a ready output recycles its completion slot and advances its
    /// generation. A pending entry remains linked to its waiter and stores the
    /// latest task waker. Returns `None` while pending.
    ///
    /// Panics if `completion_id` is stale or untracked.
    pub fn poll_take(&mut self, completion_id: CompletionId, waker: &Waker) -> Option<Output> {
        let index = completion_id.index() as usize;
        let entry = self.entry_mut(completion_id, "poll_take");
        match &mut entry.completion {
            Completion::Pending { waker: stored, .. } => {
                match stored {
                    Some(existing) => existing.clone_from(waker),
                    None => *stored = Some(waker.clone()),
                }
                None
            }
            Completion::Ready(_) => {
                let Completion::Ready(output) = self.take(index) else {
                    unreachable!("completion verified ready above");
                };
                Some(output)
            }
        }
    }

    /// Remove a ticket's completion state and recycle its slot.
    ///
    /// A Pending entry returns its stored waker so the caller can first
    /// commit the linked waiter's orphan transition, then drop the waker
    /// outside the owner-state borrow. A Ready entry drops its output and
    /// returns `Ready`.
    ///
    /// Panics if `completion_id` is stale or untracked.
    pub fn mark_orphaned(&mut self, completion_id: CompletionId) -> CompletionDropOutcome {
        let index = completion_id.index() as usize;
        let _ = self.entry(completion_id, "mark_orphaned");
        match self.take(index) {
            Completion::Pending { waiter_id, waker } => {
                CompletionDropOutcome::Pending { waiter_id, waker }
            }
            Completion::Ready(_) => CompletionDropOutcome::Ready,
        }
    }

    /// Return the number of terminal outputs retained by tickets.
    pub const fn ready(&self) -> usize {
        self.ready
    }

    /// Return the completion arena's high-water size.
    #[cfg(test)]
    pub const fn arena_len(&self) -> usize {
        self.entries.len()
    }

    /// Look up a live completion after validating its full generation-stamped ID.
    ///
    /// `operation` is included in invariant-failure messages. Panics when the
    /// slot is empty, out of bounds, or belongs to another generation.
    fn entry(&self, id: CompletionId, operation: &str) -> &TicketCompletion {
        let entry = self
            .entries
            .get(id.index() as usize)
            .and_then(Option::as_ref)
            .unwrap_or_else(|| panic!("{operation} called for untracked completion"));
        assert_eq!(entry.id, id, "{operation} called with stale completion id");
        entry
    }

    /// Mutably look up a live completion after validating its full ID.
    ///
    /// `operation` is included in invariant-failure messages. Panics when the
    /// slot is empty, out of bounds, or belongs to another generation.
    fn entry_mut(&mut self, id: CompletionId, operation: &str) -> &mut TicketCompletion {
        let entry = self
            .entries
            .get_mut(id.index() as usize)
            .and_then(Option::as_mut)
            .unwrap_or_else(|| panic!("{operation} called for untracked completion"));
        assert_eq!(entry.id, id, "{operation} called with stale completion id");
        entry
    }

    /// Remove a live entry by arena index and recycle its next-generation ID.
    ///
    /// The caller must validate the generation with [`Self::entry`] or
    /// [`Self::entry_mut`] first. This helper decrements the ready count when
    /// needed and panics if `index` is out of bounds or empty.
    fn take(&mut self, index: usize) -> Completion {
        let entry = self.entries[index]
            .take()
            .expect("tracked completion missing");
        if matches!(entry.completion, Completion::Ready(_)) {
            self.ready -= 1;
        }
        self.free.push(entry.id.next_generation());
        entry.completion
    }
}

/// Tracks logical requests and the state needed to complete them.
pub struct Waiters {
    /// Waiters indexed by slot index.
    ///
    /// Free slots have no waiter (`None`).
    entries: Vec<Option<Waiter>>,
    /// Stack of reusable waiter IDs. Removing a slot advances its generation
    /// before the ID is returned here, rejecting late CQEs for its old owner.
    free: Vec<WaiterId>,
    /// Number of tracked waiters still in [Lifecycle::Pending].
    pending: usize,
}

impl Waiters {
    /// Create an empty waiter set that can track at most `capacity` logical
    /// requests at once.
    pub fn new(capacity: usize) -> Self {
        let mut entries = Vec::with_capacity(capacity);
        entries.resize_with(capacity, || None);

        let mut free = Vec::with_capacity(capacity);
        free.extend((0..capacity).rev().map(|index| {
            let index = u32::try_from(index).expect("slot index overflow");
            WaiterId::new(index, 0)
        }));

        Self {
            entries,
            free,
            pending: 0,
        }
    }

    /// Return the number of currently tracked waiters.
    pub const fn len(&self) -> usize {
        self.entries.len() - self.free.len()
    }

    /// Return whether there are no tracked waiters.
    #[cfg_attr(not(test), allow(dead_code))]
    pub const fn is_empty(&self) -> bool {
        self.entries.len() == self.free.len()
    }

    /// Return the number of tracked waiters whose request is still
    /// progressing (staged, in flight, or awaiting cancellation).
    ///
    /// Parked ordinary op results are excluded because they hold no kernel
    /// resources. Ticket results leave the waiter entirely, so drain
    /// termination keys on this count rather than [Self::len].
    pub const fn pending(&self) -> usize {
        self.pending
    }

    /// Return whether all waiter slots are currently occupied.
    #[cfg_attr(not(test), allow(dead_code))]
    pub const fn is_full(&self) -> bool {
        self.free.is_empty()
    }

    /// Return the authoritative number of free waiter slots.
    ///
    /// Capacity reservations reconcile against this value after every waiter
    /// removal so userspace grants cannot drift from the slab.
    pub const fn free_len(&self) -> usize {
        self.free.len()
    }

    /// Insert an ordinary request and return its generation-stamped waiter ID.
    ///
    /// The waiter owns the request and the supplied task waker. Deadline
    /// scheduling happens separately at first staging, and terminal output is
    /// parked in this waiter until the same op future takes it.
    ///
    /// Panics if no free slot is available.
    #[inline]
    pub fn insert(&mut self, request: Request, waker: Waker) -> WaiterId {
        self.insert_with_observer(request, Observer::Op(Some(waker)))
    }

    /// Insert a request owned by a detached ticket.
    ///
    /// The waiter stores `completion_id` as its reverse link. The ticket waker
    /// remains in [`TicketCompletions`] while pending, and terminal output is
    /// transferred there before this waiter slot is recycled.
    ///
    /// Panics if no free slot is available.
    pub fn insert_ticket(&mut self, request: Request, completion_id: CompletionId) -> WaiterId {
        self.insert_with_observer(request, Observer::Ticket(completion_id))
    }

    /// Insert a pending request with the observer that will own its output.
    ///
    /// The next generation-stamped free slot starts active, without an SQE in
    /// flight, and with a pending request lifecycle. This shared helper also
    /// updates the tracked and progressing counts used by capacity and drain
    /// accounting.
    ///
    /// Panics if no free slot is available.
    fn insert_with_observer(&mut self, request: Request, observer: Observer) -> WaiterId {
        let id = self
            .free
            .pop()
            .expect("waiters should not exceed configured capacity");
        let index = id.index() as usize;
        let replaced = self.entries[index].replace(Waiter {
            id,
            state: WaiterState::Active { target_tick: None },
            in_flight: false,
            observer,
            lifecycle: Lifecycle::Pending(request),
        });
        assert!(replaced.is_none(), "free slot should not contain waiter");
        self.pending += 1;
        id
    }

    /// Free the slot at `index`, returning its final lifecycle state.
    ///
    /// Panics if `index` is out of bounds or the slot is empty. Callers must
    /// already have validated that the slot still belongs to the expected
    /// waiter.
    fn take(&mut self, index: usize) -> Lifecycle {
        let slot = self.entries[index].take().expect("tracked waiter missing");
        self.free.push(slot.id.next_generation());
        if matches!(slot.lifecycle, Lifecycle::Pending(_)) {
            self.pending -= 1;
        }
        slot.lifecycle
    }

    /// Return the deadline that still needs wheel scheduling for a waiter.
    ///
    /// This is `Some` only for the first staging of a request that carries a
    /// deadline: later stagings observe the recorded tick.
    pub fn deadline_to_schedule(&self, waiter_id: WaiterId) -> Option<std::time::Instant> {
        let slot = self
            .entries
            .get(waiter_id.index() as usize)
            .and_then(Option::as_ref)?;
        if slot.id != waiter_id {
            return None;
        }
        let WaiterState::Active { target_tick: None } = slot.state else {
            return None;
        };
        let Lifecycle::Pending(request) = &slot.lifecycle else {
            return None;
        };
        request.deadline()
    }

    /// Record the scheduled wheel tick for a waiter's deadline.
    ///
    /// Panics if the waiter is not tracked, already scheduled, or already
    /// cancel-requested.
    pub fn set_target_tick(&mut self, waiter_id: WaiterId, tick: Tick) {
        let slot = self
            .entries
            .get_mut(waiter_id.index() as usize)
            .and_then(Option::as_mut)
            .expect("set_target_tick called for untracked waiter");
        assert_eq!(slot.id, waiter_id, "set_target_tick with stale waiter id");
        assert!(
            matches!(slot.state, WaiterState::Active { target_tick: None }),
            "set_target_tick called for scheduled or cancelled waiter"
        );
        slot.state = WaiterState::Active {
            target_tick: Some(tick),
        };
    }

    /// Request cancellation for an active waiter.
    ///
    /// Returns `true` when the waiter was successfully transitioned to
    /// cancel-requested. Returns `false` when the waiter id is stale, not
    /// present, already cancel-requested, or already completed.
    pub fn cancel(&mut self, waiter_id: WaiterId) -> bool {
        let Some(slot) = self.entries.get_mut(waiter_id.index() as usize) else {
            return false;
        };
        let Some(slot) = slot.as_mut() else {
            return false;
        };
        if slot.id != waiter_id {
            // Slot was reused, this CQE belongs to an older waiter generation.
            return false;
        }
        if !matches!(slot.lifecycle, Lifecycle::Pending(_)) {
            // The parked result is no longer cancellable.
            return false;
        }
        match slot.state {
            WaiterState::Active { .. } => {
                slot.state = WaiterState::CancelRequested {
                    reason: CancelReason::Deadline,
                };
                true
            }
            WaiterState::CancelRequested { .. } => false,
        }
    }

    /// Request cancellation for every progressing waiter.
    ///
    /// Returns, for each transitioned waiter, its id, its deadline tick (so
    /// the caller can release timeout-wheel accounting), and whether it has an
    /// operation SQE in flight (requiring an async-cancel SQE). Waiters that
    /// are not in flight retire locally when restaged.
    pub fn cancel_active(&mut self) -> Vec<(WaiterId, Option<Tick>, bool)> {
        let mut cancelled = Vec::new();
        for slot in self.entries.iter_mut().filter_map(Option::as_mut) {
            if !matches!(slot.lifecycle, Lifecycle::Pending(_)) {
                continue;
            }
            let WaiterState::Active { target_tick } = slot.state else {
                continue;
            };
            slot.state = WaiterState::CancelRequested {
                reason: CancelReason::Shutdown,
            };
            cancelled.push((slot.id, target_tick, slot.in_flight));
        }
        cancelled
    }

    /// Stage the next SQE for a waiter.
    ///
    /// This either returns the next SQE to issue, or resolves the waiter
    /// locally:
    ///
    /// - [`StageOutcome::Submit`] leaves the waiter tracked and yields the next SQE.
    /// - [`StageOutcome::Complete`] completes the waiter locally (deadline
    ///   expiry, shutdown, or orphan retirement) without emitting an SQE.
    /// - [`StageOutcome::Ticket`] returns terminal ticket output for publication
    ///   before its waiter is recycled.
    ///
    /// When this returns [`StageOutcome::Submit`], the waiter is marked as having an
    /// operation SQE outstanding immediately, so [`Waiters::is_in_flight`] will return
    /// `true` for that waiter.
    ///
    /// Panics if `waiter_id` does not refer to a currently tracked pending
    /// waiter or if the waiter already has an operation SQE outstanding.
    #[inline]
    pub fn stage(&mut self, waiter_id: WaiterId) -> StageOutcome {
        let index = waiter_id.index() as usize;
        let slot = self
            .entries
            .get_mut(index)
            .and_then(Option::as_mut)
            .expect("stage called for untracked waiter");
        assert_eq!(slot.id, waiter_id, "stage called with stale waiter id");
        let Lifecycle::Pending(request) = &mut slot.lifecycle else {
            panic!("stage called for completed waiter");
        };

        match slot.state {
            WaiterState::CancelRequested { reason } => {
                // Cancellation marked while the request sat in the backlog:
                // an in-flight request is never restaged (its CQE requeues it
                // with `in_flight` already cleared), and freeing an in-flight
                // slot below would release kernel-referenced buffers.
                assert!(
                    !slot.in_flight,
                    "stage called for cancelled waiter with op in flight"
                );
                if matches!(slot.observer, Observer::Orphaned) {
                    // Nobody can take the parked result, so free the slot.
                    let _ = self.take(index);
                    StageOutcome::Complete {
                        waker: None,
                        freed: true,
                    }
                } else {
                    // The output moves the owned buffer out of the request,
                    // so the emptied shell drops in place. The reason selects
                    // what the observer sees: a deadline expiry surfaces as
                    // timeout, a shutdown as closed.
                    let output = request.interrupt(reason.into_error());
                    match self.finish_output_at(waiter_id, output) {
                        FinishedOutput::Op { waker } => StageOutcome::Complete {
                            waker,
                            freed: false,
                        },
                        FinishedOutput::Ticket {
                            completion_id,
                            output,
                        } => StageOutcome::Ticket {
                            waiter_id,
                            completion_id,
                            output,
                        },
                    }
                }
            }
            WaiterState::Active { .. } => {
                // An orphaned request whose kind stops on orphaning is moved
                // to `CancelRequested` by `mark_orphaned` before it can ever
                // be staged again, so it must never surface here: retiring it
                // from this arm would silently resurrect stale wind-down
                // logic if the state machine drifts.
                assert!(
                    !matches!(slot.observer, Observer::Orphaned)
                        || !request.orphan_stops_progress(),
                    "orphan-stopping request staged while active"
                );
                assert!(
                    !slot.in_flight,
                    "stage called for waiter with op already in flight"
                );
                slot.in_flight = true;
                StageOutcome::Submit(request.build_sqe(waiter_id))
            }
        }
    }

    /// Process one CQE for a waiter.
    ///
    /// Cancel CQEs are handled internally. Operation CQEs drive the request
    /// state machine and return a high-level loop action. Terminal results are
    /// parked for an ordinary op, transferred toward a ticket completion
    /// entry, or dropped when the observer is already gone.
    ///
    /// Panics if a non-cancel CQE does not refer to a currently tracked waiter,
    /// if it uses a stale waiter generation, or if the waiter has no operation
    /// SQE outstanding.
    #[inline]
    pub fn on_completion(&mut self, user_data: UserData, result: i32) -> CompletionOutcome {
        let (waiter_id, is_cancel) = WaiterId::from_user_data(user_data);
        let index = waiter_id.index() as usize;

        let Some(slot) = self.entries.get_mut(index).and_then(Option::as_mut) else {
            assert!(is_cancel, "operation CQE for untracked waiter");
            return CompletionOutcome::Cancel;
        };
        if slot.id != waiter_id {
            assert!(is_cancel, "operation CQE for stale waiter generation");
            return CompletionOutcome::Cancel;
        }

        if is_cancel {
            if result == 0 {
                // Cancellation successful.
            } else if result == -libc::EALREADY {
                // Cancellation is no longer possible at this stage. The target
                // operation CQE should follow shortly.
            } else if result == -libc::ENOENT {
                // Not found can mean the target already completed (common race) or
                // stale/invalid user_data.
            } else if result == -libc::EINVAL {
                panic!("async cancel SQE rejected by kernel: EINVAL");
            } else {
                warn!(result, "unexpected async cancel CQE result");
            }

            // Cancel CQEs acknowledge cancel requests but do not complete waiters.
            return CompletionOutcome::Cancel;
        }

        let Lifecycle::Pending(request) = &mut slot.lifecycle else {
            panic!("operation CQE for completed waiter");
        };

        // The operation CQE retires the currently in-flight SQE, regardless of
        // whether the request completes or is requeued for another one.
        assert!(slot.in_flight);
        slot.in_flight = false;

        let state = slot.state;
        let orphaned = matches!(slot.observer, Observer::Orphaned);
        let orphan_stops = request.orphan_stops_progress();
        let output = request.on_cqe(state, result);
        if output.is_none() && !(orphaned && orphan_stops) {
            return CompletionOutcome::Requeue(waiter_id);
        }

        // Either the request reached a terminal state, or the current SQE
        // made non-terminal progress for a ticket that is already gone. In
        // both cases, stop issuing SQEs for this waiter now.
        let target_tick = match state {
            WaiterState::Active { target_tick } => target_tick,
            WaiterState::CancelRequested { .. } => None,
        };

        if orphaned {
            // Free the slot (dropping the request shell in place) and drop
            // the output: closing any owned resources (e.g. an accepted fd)
            // without an observer.
            let _ = self.take(index);
            drop(output);
            CompletionOutcome::Complete {
                waker: None,
                target_tick,
                freed: true,
            }
        } else {
            let output = output.expect("non-orphaned completion is terminal");
            match self.finish_output_at(waiter_id, output) {
                FinishedOutput::Op { waker } => CompletionOutcome::Complete {
                    waker,
                    target_tick,
                    freed: false,
                },
                FinishedOutput::Ticket {
                    completion_id,
                    output,
                } => CompletionOutcome::Ticket {
                    waiter_id,
                    completion_id,
                    output,
                    target_tick,
                },
            }
        }
    }

    /// Commit a non-orphaned terminal output to its owner.
    fn finish_output_at(&mut self, waiter_id: WaiterId, output: Output) -> FinishedOutput {
        let index = waiter_id.index() as usize;
        let slot = self.entries[index]
            .as_mut()
            .expect("tracked waiter missing");
        assert_eq!(slot.id, waiter_id, "finish_output_at with stale waiter id");
        match &mut slot.observer {
            Observer::Op(waker) => {
                slot.lifecycle = Lifecycle::Ready(output);
                self.pending -= 1;
                FinishedOutput::Op {
                    waker: waker.take(),
                }
            }
            Observer::Ticket(completion_id) => {
                let completion_id = *completion_id;
                slot.lifecycle = Lifecycle::TicketComplete;
                self.pending -= 1;
                FinishedOutput::Ticket {
                    completion_id,
                    output,
                }
            }
            Observer::Orphaned => panic!("orphaned output reached observer publication"),
        }
    }

    /// Take the parked result for an ordinary op, freeing the slot, or refresh
    /// the stored waker when the request is still progressing.
    ///
    /// Panics if the waiter is not tracked or the id is stale: only the owning
    /// ordinary op frees a non-orphaned slot, so a miss is an invariant
    /// violation.
    #[inline]
    pub fn poll_take(&mut self, waiter_id: WaiterId, waker: &Waker) -> Option<Output> {
        let index = waiter_id.index() as usize;
        let slot = self
            .entries
            .get_mut(index)
            .and_then(Option::as_mut)
            .expect("poll_take called for untracked waiter");
        assert_eq!(slot.id, waiter_id, "poll_take called with stale waiter id");
        assert!(
            matches!(slot.observer, Observer::Op(_)),
            "poll_take called for ticket waiter"
        );

        match &mut slot.lifecycle {
            Lifecycle::Ready(_) => {
                let Lifecycle::Ready(output) = self.take(index) else {
                    unreachable!("lifecycle verified ready above");
                };
                Some(output)
            }
            Lifecycle::Pending(_) => {
                let Observer::Op(stored) = &mut slot.observer else {
                    unreachable!("observer verified op above");
                };
                match stored {
                    Some(existing) => existing.clone_from(waker),
                    None => *stored = Some(waker.clone()),
                }
                None
            }
            Lifecycle::TicketComplete => panic!("op waiter reached ticket terminal state"),
        }
    }

    /// Recycle a terminal ticket waiter after its output is published.
    pub fn finish_ticket(&mut self, waiter_id: WaiterId, completion_id: CompletionId) {
        let index = waiter_id.index() as usize;
        let slot = self
            .entries
            .get(index)
            .and_then(Option::as_ref)
            .expect("finish_ticket called for untracked waiter");
        assert_eq!(
            slot.id, waiter_id,
            "finish_ticket called with stale waiter id"
        );
        assert!(
            matches!(slot.lifecycle, Lifecycle::TicketComplete),
            "finish_ticket called before terminal ticket output"
        );
        let Observer::Ticket(stored_completion) = slot.observer else {
            panic!("finish_ticket called for non-ticket waiter");
        };
        assert_eq!(
            stored_completion, completion_id,
            "finish_ticket called with wrong completion id"
        );
        let _ = self.take(index);
    }

    /// Mark a waiter's observer as dropped and resolve how its slot winds down.
    ///
    /// Parked results are dropped and their slot freed immediately. Requests
    /// whose kind stops progressing without an observer transition to
    /// cancellation. Storage writes and syncs detach and keep running.
    ///
    /// Panics if the waiter is not tracked or the id is stale.
    pub fn mark_orphaned(&mut self, waiter_id: WaiterId) -> DropOutcome {
        let index = waiter_id.index() as usize;
        let slot = self
            .entries
            .get_mut(index)
            .and_then(Option::as_mut)
            .expect("mark_orphaned called for untracked waiter");
        assert_eq!(
            slot.id, waiter_id,
            "mark_orphaned called with stale waiter id"
        );

        let Lifecycle::Pending(request) = &slot.lifecycle else {
            assert!(
                matches!(slot.lifecycle, Lifecycle::Ready(_)),
                "ticket-terminal waiter escaped driver commit"
            );
            let _ = self.take(index);
            return DropOutcome::Freed;
        };

        slot.observer = Observer::Orphaned;
        if !request.orphan_stops_progress() {
            return DropOutcome::Detached;
        }
        match slot.state {
            WaiterState::Active { target_tick } => {
                // The ticket is gone, so the parked result (and its reason)
                // is never observed.
                slot.state = WaiterState::CancelRequested {
                    reason: CancelReason::Deadline,
                };
                DropOutcome::Cancel {
                    needs_sqe: slot.in_flight,
                    target_tick,
                }
            }
            // Cancellation was already requested (e.g. by timeout expiry,
            // which released deadline accounting), so the existing wind-down
            // path retires the slot.
            WaiterState::CancelRequested { .. } => DropOutcome::Cancel {
                needs_sqe: false,
                target_tick: None,
            },
        }
    }

    /// Return whether a waiter currently has an operation SQE in flight.
    pub fn is_in_flight(&self, waiter_id: WaiterId) -> bool {
        let index = waiter_id.index() as usize;
        self.entries
            .get(index)
            .and_then(Option::as_ref)
            .is_some_and(|slot| slot.id == waiter_id && slot.in_flight)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        IoBuf, IoBufMut, IoBufs,
        iouring::driver::request::{
            Cache, ReadAtRequest, RecvRequest, SendRequest, SyncRequest, WriteAtRequest,
            WriteAtState,
        },
    };
    use futures::task::noop_waker;
    use std::{
        os::fd::OwnedFd,
        panic::{AssertUnwindSafe, catch_unwind},
        sync::Arc,
    };

    /// Build a `Sync` request backed by a socket fd so waiter tests can
    /// exercise slot lifecycle without touching the filesystem.
    fn make_sync_request() -> Request {
        let (sock_left, _sock_right) =
            std::os::unix::net::UnixStream::pair().expect("failed to create unix socket pair");
        let file = std::fs::File::from(OwnedFd::from(sock_left));
        Request::Sync(SyncRequest {
            file: Arc::new(file),
        })
    }

    fn make_send_request() -> Request {
        Request::Send(SendRequest {
            fd: Arc::new(std::os::unix::net::UnixStream::pair().unwrap().0.into()),
            write: IoBufs::from(IoBuf::from(b"hello")).into(),
            deadline: None,
        })
    }

    fn make_recv_request() -> Request {
        Request::Recv(RecvRequest {
            fd: Arc::new(std::os::unix::net::UnixStream::pair().unwrap().0.into()),
            buf: IoBufMut::with_capacity(5),
            offset: 0,
            len: 5,
            exact: true,
            deadline: None,
        })
    }

    fn make_read_at_request() -> Request {
        let (sock_left, _sock_right) =
            std::os::unix::net::UnixStream::pair().expect("failed to create unix socket pair");
        let file = std::fs::File::from(OwnedFd::from(sock_left));
        Request::ReadAt(ReadAtRequest {
            file: Arc::new(file),
            offset: 0,
            len: 8,
            read: 0,
            buf: IoBufMut::with_capacity(8),
            cache: Cache::Enabled,
        })
    }

    fn make_write_at_request() -> Request {
        let (sock_left, _sock_right) =
            std::os::unix::net::UnixStream::pair().expect("failed to create unix socket pair");
        let file = std::fs::File::from(OwnedFd::from(sock_left));
        Request::WriteAt(WriteAtRequest {
            file: Arc::new(file),
            offset: 0,
            written: 0,
            write: IoBufs::from(IoBuf::from(b"hello")).into(),
            state: WriteAtState::Writing,
            cache: Cache::Enabled,
        })
    }

    fn insert(waiters: &mut Waiters, request: Request, tick: Option<Tick>) -> WaiterId {
        let id = waiters.insert(request, noop_waker());
        if let Some(tick) = tick {
            waiters.set_target_tick(id, tick);
        }
        id
    }

    fn waiter_state(waiters: &Waiters, waiter_id: WaiterId) -> Option<WaiterState> {
        let index = waiter_id.index() as usize;
        let slot = waiters.entries.get(index)?.as_ref()?;
        (slot.id == waiter_id).then_some(slot.state)
    }

    fn remove_waiter(waiters: &mut Waiters, waiter_id: WaiterId) -> Lifecycle {
        let index = waiter_id.index() as usize;
        let slot = waiters
            .entries
            .get(index)
            .and_then(Option::as_ref)
            .expect("remove_waiter called for untracked waiter");
        assert_eq!(
            slot.id, waiter_id,
            "remove_waiter called with stale waiter id"
        );
        waiters.take(index)
    }

    fn insert_ticket(
        completions: &mut TicketCompletions,
        waiters: &mut Waiters,
        request: Request,
    ) -> (CompletionId, WaiterId) {
        completions.insert_pending(noop_waker(), |completion_id| {
            waiters.insert_ticket(request, completion_id)
        })
    }

    #[test]
    fn test_ticket_output_survives_waiter_reuse() {
        let mut waiters = Waiters::new(1);
        let mut completions = TicketCompletions::new();
        let (completion_id, waiter_id) =
            insert_ticket(&mut completions, &mut waiters, make_sync_request());
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        let CompletionOutcome::Ticket {
            waiter_id: completed_waiter,
            completion_id: completed_completion,
            output,
            target_tick: None,
        } = waiters.on_completion(waiter_id.user_data(), 0)
        else {
            panic!("sync ticket did not produce detached output");
        };

        let _ = completions.publish_ready(completed_completion, completed_waiter, output);
        waiters.finish_ticket(completed_waiter, completed_completion);
        assert_eq!(waiters.len(), 0);
        assert_eq!(completions.ready(), 1);

        // Reuse the only waiter before consuming the first ticket. The Ready
        // output remains addressed solely by its independent completion ID.
        let (second_completion, second_waiter) =
            insert_ticket(&mut completions, &mut waiters, make_sync_request());
        assert_eq!(second_waiter.index(), waiter_id.index());
        assert_ne!(second_waiter, waiter_id);
        assert_ne!(second_completion, completion_id);
        assert!(matches!(
            completions.poll_take(completion_id, &noop_waker()),
            Some(Output::Sync(Ok(())))
        ));

        assert!(matches!(
            completions.mark_orphaned(second_completion),
            CompletionDropOutcome::Pending { waiter_id, .. } if waiter_id == second_waiter
        ));
        let _ = remove_waiter(&mut waiters, second_waiter);
    }

    #[test]
    fn test_publish_ready_rejects_duplicate_without_replacing_output() {
        let mut waiters = Waiters::new(1);
        let mut completions = TicketCompletions::new();
        let (completion_id, waiter_id) =
            insert_ticket(&mut completions, &mut waiters, make_sync_request());
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        let CompletionOutcome::Ticket {
            waiter_id: completed_waiter,
            completion_id: completed_completion,
            output,
            target_tick: None,
        } = waiters.on_completion(waiter_id.user_data(), 0)
        else {
            panic!("sync ticket did not produce detached output");
        };
        let _ = completions.publish_ready(completed_completion, completed_waiter, output);
        waiters.finish_ticket(completed_waiter, completed_completion);

        let duplicate = catch_unwind(AssertUnwindSafe(|| {
            let _ = completions.publish_ready(
                completion_id,
                waiter_id,
                Output::Sync(Err(Box::new(Error::Closed))),
            );
        }));
        assert!(duplicate.is_err());
        assert_eq!(completions.ready(), 1);
        assert!(matches!(
            completions.poll_take(completion_id, &noop_waker()),
            Some(Output::Sync(Ok(())))
        ));
    }

    #[test]
    fn test_completion_generation_reuse_rejects_stale_id() {
        let mut waiters = Waiters::new(1);
        let mut completions = TicketCompletions::new();
        let (first, first_waiter) =
            insert_ticket(&mut completions, &mut waiters, make_sync_request());
        assert!(matches!(
            completions.mark_orphaned(first),
            CompletionDropOutcome::Pending { waiter_id, .. } if waiter_id == first_waiter
        ));
        let _ = remove_waiter(&mut waiters, first_waiter);

        let (reused, reused_waiter) =
            insert_ticket(&mut completions, &mut waiters, make_sync_request());
        assert_eq!(reused.index(), first.index());
        assert_eq!(reused.generation(), first.generation().wrapping_add(1));
        assert_eq!(completions.arena_len(), 1);

        let stale = catch_unwind(AssertUnwindSafe(|| {
            let _ = completions.poll_take(first, &noop_waker());
        }));
        assert!(stale.is_err());
        assert!(matches!(
            completions.mark_orphaned(reused),
            CompletionDropOutcome::Pending { waiter_id, .. } if waiter_id == reused_waiter
        ));
        let _ = remove_waiter(&mut waiters, reused_waiter);
    }

    #[test]
    fn test_ticket_local_timeout_publishes_then_recycles_waiter() {
        let mut waiters = Waiters::new(1);
        let mut completions = TicketCompletions::new();
        let (completion_id, waiter_id) =
            insert_ticket(&mut completions, &mut waiters, make_recv_request());
        assert!(waiters.cancel(waiter_id));
        let StageOutcome::Ticket {
            waiter_id: completed_waiter,
            completion_id: completed_completion,
            output,
        } = waiters.stage(waiter_id)
        else {
            panic!("locally timed out ticket did not produce detached output");
        };
        assert_eq!(completed_waiter, waiter_id);
        assert_eq!(completed_completion, completion_id);

        let _ = completions.publish_ready(completed_completion, completed_waiter, output);
        waiters.finish_ticket(completed_waiter, completed_completion);
        assert!(waiters.is_empty());
        let Some(Output::Recv(Err(error))) = completions.poll_take(completion_id, &noop_waker())
        else {
            panic!("locally timed out ticket did not retain recv failure");
        };
        let (_, error) = *error;
        assert!(matches!(error, Error::Timeout));
    }

    #[test]
    fn test_pending_sync_ticket_drop_detaches_through_completion_id() {
        let mut waiters = Waiters::new(1);
        let mut completions = TicketCompletions::new();
        let (completion_id, waiter_id) =
            insert_ticket(&mut completions, &mut waiters, make_sync_request());
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(matches!(
            completions.mark_orphaned(completion_id),
            CompletionDropOutcome::Pending {
                waiter_id: pending_waiter,
                ..
            } if pending_waiter == waiter_id
        ));
        assert!(matches!(
            waiters.mark_orphaned(waiter_id),
            DropOutcome::Detached
        ));
        assert_eq!(completions.ready(), 0);
        assert_eq!(waiters.pending(), 1);

        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), 0),
            CompletionOutcome::Complete {
                waker: None,
                freed: true,
                ..
            }
        ));
        assert!(waiters.is_empty());
    }

    #[test]
    fn test_waiter_id_encoding_and_generation_wrap() {
        // Verify waiter ids round-trip through user_data encoding and wrap their generation field
        // without corrupting the slot index bits.
        let wrapped = WaiterId::new(7, (WaiterId::GENERATION_MASK as u32).wrapping_add(5));
        assert_eq!(wrapped.generation(), 4);

        let max = WaiterId::new(7, WaiterId::GENERATION_MASK as u32);
        assert_eq!(max.next_generation().generation(), 0);

        let waiter_id = WaiterId::new(7, 3);
        assert_eq!(waiter_id.index(), 7);
        assert_eq!(waiter_id.generation(), 3);

        let (decoded_op, is_cancel_op) = WaiterId::from_user_data(waiter_id.user_data());
        assert_eq!(decoded_op, waiter_id);
        assert!(!is_cancel_op);

        let (decoded_cancel, is_cancel) = WaiterId::from_user_data(waiter_id.cancel_user_data());
        assert_eq!(decoded_cancel, waiter_id);
        assert!(is_cancel);
    }

    #[test]
    fn test_waiters_lifecycle_and_slot_reuse() {
        // Verify waiter insertion, completion, removal, and slot reuse all preserve generations.
        let mut waiters = Waiters::new(3);
        assert_eq!(waiters.entries.len(), 3);
        assert_eq!(waiters.len(), 0);
        assert!(waiters.is_empty());

        // Populate two slots so the test can later free and reuse one of them.
        let id0 = insert(&mut waiters, make_sync_request(), Some(5));
        let id1 = insert(&mut waiters, make_sync_request(), Some(9));
        assert_eq!((id0.index(), id1.index()), (0, 1));
        assert_eq!(waiters.len(), 2);
        assert_eq!(waiters.pending(), 2);
        assert!(!waiters.is_full());

        // A stale operation CQE should panic because only cancel CQEs are
        // expected to arrive after slot reuse.
        let stale = WaiterId::new(id1.index(), id1.generation().wrapping_add(1));
        let stale_completion = catch_unwind(AssertUnwindSafe(|| {
            let _ = waiters.on_completion(stale.user_data(), 0);
        }));
        assert!(stale_completion.is_err());

        // Complete id1: the result parks in the slot until taken.
        assert!(matches!(waiters.stage(id1), StageOutcome::Submit(_)));
        assert!(matches!(
            waiters.on_completion(id1.user_data(), 0),
            CompletionOutcome::Complete {
                target_tick: Some(9),
                freed: false,
                ..
            }
        ));
        assert_eq!(waiters.len(), 2);
        assert_eq!(waiters.pending(), 1);
        assert!(matches!(
            waiters.poll_take(id1, &noop_waker()),
            Some(Output::Sync(Ok(())))
        ));
        assert_eq!(waiters.len(), 1);

        // Next allocation reuses the freed slot with incremented generation.
        let id2 = insert(&mut waiters, make_sync_request(), Some(11));
        assert_eq!(id2.index(), id1.index());
        assert_eq!(
            id2.generation(),
            id1.generation().wrapping_add(1) & (WaiterId::GENERATION_MASK as u32)
        );

        // All live waiters should still complete and remove cleanly after slot reuse.
        assert!(matches!(waiters.stage(id0), StageOutcome::Submit(_)));
        let _ = waiters.on_completion(id0.user_data(), 0);
        assert!(waiters.poll_take(id0, &noop_waker()).is_some());
        assert!(matches!(waiters.stage(id2), StageOutcome::Submit(_)));
        let _ = waiters.on_completion(id2.user_data(), 0);
        assert!(waiters.poll_take(id2, &noop_waker()).is_some());
        assert!(waiters.is_empty());
    }

    #[test]
    fn test_waiters_cancel_paths() {
        // Verify cancel requests transition waiter state, ignore cancel CQEs for completion, and
        // discard late cancel CQEs once the original operation has already completed.
        let mut waiters = Waiters::new(3);

        let waiter_id = insert(&mut waiters, make_sync_request(), Some(2));

        let stale = WaiterId::new(waiter_id.index(), waiter_id.generation().wrapping_add(1));
        assert!(!waiters.cancel(stale));

        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(
            waiters.cancel(waiter_id),
            "cancel should transition active waiter"
        );

        // Cancel CQE does not complete the waiter.
        assert!(matches!(
            waiters.on_completion(waiter_id.cancel_user_data(), -libc::ECANCELED),
            CompletionOutcome::Cancel
        ));

        // Op CQE completes the waiter.
        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), 0),
            CompletionOutcome::Complete {
                target_tick: None,
                freed: false,
                ..
            }
        ));
        assert_eq!(waiters.pending(), 0);
        assert!(waiters.poll_take(waiter_id, &noop_waker()).is_some());
        assert!(waiters.is_empty());

        // Late cancel CQE for the already-completed waiter should be ignored.
        assert!(matches!(
            waiters.on_completion(waiter_id.cancel_user_data(), -libc::ECANCELED),
            CompletionOutcome::Cancel
        ));
        let missing_op_cqe = catch_unwind(AssertUnwindSafe(|| {
            let _ = waiters.on_completion(0, 1);
        }));
        assert!(missing_op_cqe.is_err());
    }

    #[test]
    fn test_waiters_stale_cancel_after_slot_reuse() {
        // Property: a cancel-tagged CQE carrying a stale generation is
        // tolerated after its slot index was reused by a new waiter, leaving
        // the new waiter untouched. This is the documented late-cancel race
        // the generation field exists for (only the empty-slot half was
        // covered before).
        // Setup: complete and take a waiter so its slot frees, then insert a
        // new waiter that reuses the same index with a new generation and
        // stage it.
        // Action: feed the old generation's cancel user_data with ECANCELED.
        // Expected: CompletionOutcome::Cancel, and the new waiter keeps its
        // identity, active state, and in-flight marker.
        let mut waiters = Waiters::new(1);

        // Insert, stage, complete, and take the first waiter.
        let old = insert(&mut waiters, make_sync_request(), None);
        assert!(matches!(waiters.stage(old), StageOutcome::Submit(_)));
        assert!(matches!(
            waiters.on_completion(old.user_data(), 0),
            CompletionOutcome::Complete { .. }
        ));
        assert!(waiters.poll_take(old, &noop_waker()).is_some());
        assert!(waiters.is_empty());

        // Reuse the slot index under a new generation and stage the waiter.
        let new = insert(&mut waiters, make_sync_request(), None);
        assert_eq!(new.index(), old.index(), "slot index must be reused");
        assert_ne!(new, old, "reused slot must carry a new generation");
        assert!(matches!(waiters.stage(new), StageOutcome::Submit(_)));

        // The old generation's late cancel CQE is tolerated and changes
        // nothing about the new waiter.
        assert!(matches!(
            waiters.on_completion(old.cancel_user_data(), -libc::ECANCELED),
            CompletionOutcome::Cancel
        ));
        assert!(matches!(
            waiter_state(&waiters, new),
            Some(WaiterState::Active { .. })
        ));
        assert!(waiters.is_in_flight(new), "in-flight marker must survive");
    }

    #[test]
    fn test_waiters_track_in_flight_state() {
        // Verify `stage` tracks a staged operation and that the bit is
        // cleared again when the matching op CQE is processed.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), Some(4));

        assert!(waiters.is_full());
        assert!(!waiters.is_in_flight(waiter_id));
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(waiters.is_in_flight(waiter_id));

        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), 0),
            CompletionOutcome::Complete { .. }
        ));
        assert!(!waiters.is_in_flight(waiter_id));
    }

    #[test]
    fn test_waiters_reject_stale_in_flight_queries() {
        // Verify stale waiter ids cannot observe in-flight state after
        // their slot has been recycled to a new generation.
        let mut waiters = Waiters::new(1);
        let stale_id = insert(&mut waiters, make_sync_request(), Some(1));
        let _ = remove_waiter(&mut waiters, stale_id);

        let deadline = std::time::Instant::now();
        let active_id = insert(
            &mut waiters,
            Request::Send(SendRequest {
                fd: Arc::new(std::os::unix::net::UnixStream::pair().unwrap().0.into()),
                write: IoBufs::from(IoBuf::from(b"hello")).into(),
                deadline: Some(deadline),
            }),
            None,
        );
        assert_ne!(active_id, stale_id);

        assert!(!waiters.is_in_flight(stale_id));
        assert!(waiters.deadline_to_schedule(stale_id).is_none());
        assert_eq!(waiters.deadline_to_schedule(active_id), Some(deadline));
        assert!(matches!(waiters.stage(active_id), StageOutcome::Submit(_)));
        assert!(waiters.is_in_flight(active_id));
    }

    #[test]
    fn test_waiters_completed_results_cannot_be_scheduled_or_staged() {
        let mut waiters = Waiters::new(1);
        let deadline = std::time::Instant::now();
        let waiter_id = waiters.insert(
            Request::Send(SendRequest {
                fd: Arc::new(std::os::unix::net::UnixStream::pair().unwrap().0.into()),
                write: IoBufs::from(IoBuf::from(b"hello")).into(),
                deadline: Some(deadline),
            }),
            noop_waker(),
        );
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), 5),
            CompletionOutcome::Complete { freed: false, .. }
        ));

        assert!(waiters.deadline_to_schedule(waiter_id).is_none());
        let restage = catch_unwind(AssertUnwindSafe(|| {
            let _ = waiters.stage(waiter_id);
        }));
        assert!(restage.is_err());
        assert!(matches!(
            waiters.poll_take(waiter_id, &noop_waker()),
            Some(Output::Send(Ok(())))
        ));
    }

    #[test]
    fn test_waiters_stage_panics_for_out_of_range_and_empty_slots() {
        // Verify `stage` treats impossible waiter ids as invariant failures,
        // while the tolerant query/cancel paths still reject them cleanly.
        let mut waiters = Waiters::new(1);
        let out_of_range = WaiterId::new(7, 0);
        assert!(!waiters.cancel(out_of_range));
        let out_of_range_stage = catch_unwind(AssertUnwindSafe(|| {
            let _ = waiters.stage(out_of_range);
        }));
        assert!(out_of_range_stage.is_err());

        let empty_slot = WaiterId::new(0, 0);
        assert!(!waiters.cancel(empty_slot));
        let empty_slot_stage = catch_unwind(AssertUnwindSafe(|| {
            let _ = waiters.stage(empty_slot);
        }));
        assert!(empty_slot_stage.is_err());
    }

    #[test]
    fn test_waiters_cancel_and_in_flight_reject_out_of_range_and_empty_slots() {
        // Verify cancel and in-flight tracking reject waiter ids that point
        // outside the table or at currently empty slots.
        let mut waiters = Waiters::new(1);
        let out_of_range = WaiterId::new(7, 0);
        assert!(!waiters.cancel(out_of_range));
        assert!(!waiters.is_in_flight(out_of_range));

        let empty_slot = WaiterId::new(0, 0);
        assert!(!waiters.cancel(empty_slot));
        assert!(!waiters.is_in_flight(empty_slot));
    }

    #[test]
    fn test_waiters_cancel_stage_only_when_in_flight() {
        // Verify timeout processing can distinguish between:
        // - a waiter whose current SQE is still in flight
        // - a waiter that is only parked in the backlog
        let mut waiters = Waiters::new(2);

        // First build a waiter that still has an operation SQE outstanding.
        let active = insert(&mut waiters, make_sync_request(), Some(2));
        assert!(matches!(waiters.stage(active), StageOutcome::Submit(_)));
        assert!(waiters.cancel(active));
        assert!(waiters.is_in_flight(active));
        let active_state = waiter_state(&waiters, active).expect("active waiter missing");
        assert!(matches!(active_state, WaiterState::CancelRequested { .. }));

        // Then build a waiter that has been canceled before any SQE was staged.
        let ready = insert(&mut waiters, make_sync_request(), Some(3));
        assert!(waiters.cancel(ready));
        assert!(!waiters.is_in_flight(ready));
        let ready_state = waiter_state(&waiters, ready).expect("ready waiter missing");
        assert!(matches!(ready_state, WaiterState::CancelRequested { .. }));
    }

    #[test]
    fn test_waiters_stage_orphans_dropped_ops() {
        // Verify orphaned send and read-at requests are removed locally before
        // their first SQE is ever staged.
        for (request, tick) in [(make_send_request(), 7), (make_read_at_request(), 8)] {
            let mut waiters = Waiters::new(1);
            let waiter_id = insert(&mut waiters, request, Some(tick));
            assert!(matches!(
                waiters.mark_orphaned(waiter_id),
                DropOutcome::Cancel {
                    needs_sqe: false,
                    target_tick: Some(_),
                }
            ));

            match waiters.stage(waiter_id) {
                StageOutcome::Complete {
                    waker: None,
                    freed: true,
                } => {}
                _ => panic!("orphaned waiter should be retired before staging"),
            }
            assert!(waiters.is_empty());
        }
    }

    #[test]
    fn test_waiters_orphan_dropped_ops_after_nonterminal_completion() {
        // Verify retryable and partial-progress send, recv, and read-at CQEs
        // remove the waiter instead of requeueing once the op is gone.
        for (request, tick, result) in [
            // Retryable CQE.
            (make_send_request(), 5, -libc::EAGAIN),
            // Partial-progress CQE.
            (make_send_request(), 5, 2),
            (make_recv_request(), 6, -libc::EAGAIN),
            (make_recv_request(), 6, 3),
            (make_read_at_request(), 9, 3),
        ] {
            let mut waiters = Waiters::new(1);
            let waiter_id = insert(&mut waiters, request, Some(tick));
            assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
            assert!(matches!(
                waiters.mark_orphaned(waiter_id),
                DropOutcome::Cancel {
                    needs_sqe: true,
                    ..
                }
            ));

            match waiters.on_completion(waiter_id.user_data(), result) {
                CompletionOutcome::Complete {
                    waker: None,
                    // Cancellation transitioned the waiter, so deadline
                    // tracking was already released.
                    target_tick: None,
                    freed: true,
                } => {}
                _ => panic!("orphaned waiter should be freed after CQE"),
            }
            assert!(waiters.is_empty());
        }
    }

    #[test]
    fn test_waiters_detach_write_and_sync_on_drop() {
        // Verify write/sync requests keep progressing after their op is
        // dropped and free their slot at the terminal CQE.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), None);
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(matches!(
            waiters.mark_orphaned(waiter_id),
            DropOutcome::Detached
        ));

        // The waiter is still active: no cancellation was requested.
        let state = waiter_state(&waiters, waiter_id).expect("waiter should remain tracked");
        assert!(matches!(state, WaiterState::Active { .. }));

        // The terminal CQE frees the slot without parking a result.
        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), 0),
            CompletionOutcome::Complete {
                waker: None,
                freed: true,
                ..
            }
        ));
        assert!(waiters.is_empty());
    }

    #[test]
    fn test_waiters_requeue_partial_detached_write() {
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_write_at_request(), None);
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(matches!(
            waiters.mark_orphaned(waiter_id),
            DropOutcome::Detached
        ));

        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), 2),
            CompletionOutcome::Requeue(id) if id == waiter_id
        ));
        assert!(!waiters.is_in_flight(waiter_id));
        assert_eq!(waiters.pending(), 1);

        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), 3),
            CompletionOutcome::Complete {
                waker: None,
                freed: true,
                ..
            }
        ));
        assert!(waiters.is_empty());
    }

    #[test]
    fn test_waiters_drop_after_completion_frees_slot() {
        // Verify dropping an op whose result is already parked frees the
        // slot and drops the output.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), None);
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), 0),
            CompletionOutcome::Complete { freed: false, .. }
        ));
        assert_eq!(waiters.pending(), 0);
        assert_eq!(waiters.len(), 1);

        assert!(matches!(
            waiters.mark_orphaned(waiter_id),
            DropOutcome::Freed
        ));
        assert!(waiters.is_empty());
    }

    #[test]
    fn test_waiters_deadline_scheduling() {
        // Verify deadline bookkeeping: only unscheduled deadlines are
        // reported, and recording a tick transitions the waiter.
        let mut waiters = Waiters::new(2);

        // Sync requests carry no deadline.
        let sync_id = waiters.insert(make_sync_request(), noop_waker());
        assert!(waiters.deadline_to_schedule(sync_id).is_none());

        // Send requests with a deadline report it exactly once.
        let deadline = std::time::Instant::now();
        let send_id = waiters.insert(
            Request::Send(SendRequest {
                fd: Arc::new(std::os::unix::net::UnixStream::pair().unwrap().0.into()),
                write: IoBufs::from(IoBuf::from(b"hello")).into(),
                deadline: Some(deadline),
            }),
            noop_waker(),
        );
        assert_eq!(waiters.deadline_to_schedule(send_id), Some(deadline));
        waiters.set_target_tick(send_id, 3);
        assert!(waiters.deadline_to_schedule(send_id).is_none());
        assert!(matches!(
            waiter_state(&waiters, send_id),
            Some(WaiterState::Active {
                target_tick: Some(3)
            })
        ));

        // Rescheduling a scheduled waiter is an invariant violation.
        let double_schedule = catch_unwind(AssertUnwindSafe(|| {
            waiters.set_target_tick(send_id, 4);
        }));
        assert!(double_schedule.is_err());
    }

    #[test]
    fn test_waiters_poll_take_refreshes_waker() {
        // Verify pending polls refresh the stored waker rather than taking
        // the slot.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), None);
        assert!(waiters.poll_take(waiter_id, &noop_waker()).is_none());
        assert_eq!(waiters.pending(), 1);

        // Stale ids panic rather than observing a reused slot.
        let _ = remove_waiter(&mut waiters, waiter_id);
        let stale_take = catch_unwind(AssertUnwindSafe(|| {
            let _ = waiters.poll_take(waiter_id, &noop_waker());
        }));
        assert!(stale_take.is_err());
    }

    #[test]
    fn test_waiters_accept_expected_cancel_cqe_results() {
        // Verify the expected kernel cancel CQE results leave the waiter alive
        // for the original operation CQE to finish it later.
        for result in [0, -libc::EALREADY, -libc::ENOENT] {
            let mut waiters = Waiters::new(1);
            let waiter_id = insert(&mut waiters, make_sync_request(), Some(2));
            assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
            assert!(waiters.cancel(waiter_id));

            assert!(matches!(
                waiters.on_completion(waiter_id.cancel_user_data(), result),
                CompletionOutcome::Cancel
            ));
            let state = waiter_state(&waiters, waiter_id).expect("waiter should remain tracked");
            assert!(matches!(state, WaiterState::CancelRequested { .. }));
        }
    }

    #[test]
    fn test_waiters_tolerate_unexpected_negative_cancel_result() {
        // Verify unexpected negative cancel CQEs are ignored rather than
        // corrupting waiter state.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), Some(2));
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(waiters.cancel(waiter_id));

        assert!(matches!(
            waiters.on_completion(waiter_id.cancel_user_data(), -libc::EPERM),
            CompletionOutcome::Cancel
        ));
        let state = waiter_state(&waiters, waiter_id).expect("waiter should remain tracked");
        assert!(matches!(state, WaiterState::CancelRequested { .. }));
    }

    #[test]
    fn test_waiters_cancel_cqe_einval_panics() {
        // Verify `EINVAL` remains a hard invariant failure because the kernel
        // rejected our async cancel SQE.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), Some(2));
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(waiters.cancel(waiter_id));

        let result = catch_unwind(AssertUnwindSafe(|| {
            let _ = waiters.on_completion(waiter_id.cancel_user_data(), -libc::EINVAL);
        }));
        assert!(result.is_err());
    }

    #[test]
    fn test_waiters_cancel_rejects_parked_results() {
        // Verify parked results can no longer transition to cancellation
        // (e.g. from a stale timeout-wheel entry).
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), None);
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), 0),
            CompletionOutcome::Complete { freed: false, .. }
        ));
        assert!(!waiters.cancel(waiter_id));
        assert!(waiters.poll_take(waiter_id, &noop_waker()).is_some());
    }

    #[test]
    fn test_waiters_stale_ids_cannot_remove_reused_slots() {
        // Verify stale waiter ids cannot observe state or remove a reused slot.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), Some(1));
        let _ = remove_waiter(&mut waiters, waiter_id);

        let reused_id = insert(&mut waiters, make_sync_request(), Some(2));
        assert_ne!(reused_id, waiter_id);
        assert!(waiter_state(&waiters, waiter_id).is_none());
        let stale_remove = catch_unwind(AssertUnwindSafe(|| {
            let _ = remove_waiter(&mut waiters, waiter_id);
        }));
        assert!(stale_remove.is_err());
    }

    #[test]
    fn test_waiters_insert_and_cancel_invariants() {
        // Verify waiter capacity is enforced and that cancel remains valid even for waiters that
        // were inserted without a deadline.
        let mut waiters = Waiters::new(2);

        // Inserting beyond configured capacity should panic.
        let _ = waiters.insert(make_sync_request(), noop_waker());
        let _ = waiters.insert(make_sync_request(), noop_waker());
        assert!(waiters.is_full());
        let insert_overflow = catch_unwind(AssertUnwindSafe(|| {
            let _ = waiters.insert(make_sync_request(), noop_waker());
        }));
        assert!(insert_overflow.is_err());

        // Cancellation is allowed even when no deadline is tracked.
        let mut waiters = Waiters::new(2);
        let no_deadline = waiters.insert(make_sync_request(), noop_waker());
        assert!(
            waiters.cancel(no_deadline),
            "cancel should support active waiter without deadline"
        );

        // Repeated cancel on the same waiter must be ignored.
        let active = insert(&mut waiters, make_sync_request(), Some(3));
        assert!(waiters.cancel(active));
        assert!(!waiters.cancel(active));
    }

    #[test]
    fn test_waiters_cancel_active_skips_parked_results() {
        // Verify shutdown-time cancel-all only transitions progressing
        // waiters.
        let mut waiters = Waiters::new(3);

        // One parked result, one in-flight waiter, one already cancelled.
        let parked = insert(&mut waiters, make_sync_request(), None);
        assert!(matches!(waiters.stage(parked), StageOutcome::Submit(_)));
        assert!(matches!(
            waiters.on_completion(parked.user_data(), 0),
            CompletionOutcome::Complete { .. }
        ));

        let in_flight = insert(&mut waiters, make_sync_request(), Some(2));
        assert!(matches!(waiters.stage(in_flight), StageOutcome::Submit(_)));

        let cancelled = insert(&mut waiters, make_sync_request(), Some(3));
        assert!(waiters.cancel(cancelled));

        let transitioned = waiters.cancel_active();
        assert_eq!(transitioned.len(), 1);
        assert_eq!(transitioned[0].0, in_flight);
        assert_eq!(transitioned[0].1, Some(2));
        assert!(transitioned[0].2);
    }

    #[test]
    fn test_shutdown_cancellation_is_not_reported_as_deadline_timeout() {
        // `cancel_active` is the shutdown-budget path. Its cancellation must
        // remain distinguishable from `cancel`, which is also used by the
        // request deadline path: a shutdown surfaces as closed, not as an
        // ordinary operation timeout.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_recv_request(), Some(7));
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert_eq!(waiters.cancel_active().len(), 1);

        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), -libc::ECANCELED),
            CompletionOutcome::Complete { .. }
        ));
        let Some(Output::Recv(Err(error))) = waiters.poll_take(waiter_id, &noop_waker()) else {
            panic!("shutdown-cancelled recv did not produce an error");
        };
        let (_, error) = *error;
        assert!(
            matches!(error, Error::Closed),
            "expected shutdown cancellation to be Closed, got {error:?}"
        );
    }
}
