//! Waiter identity and lifecycle state for tracked io_uring requests.
//!
//! This module manages waiter IDs, request lifecycle transitions, and
//! outstanding-operation tracking. It is the source of truth for which logical
//! requests are still tracked, whether each currently has an operation SQE
//! outstanding, and which terminal results are parked awaiting their ticket.

use super::{
    Tick, UserData,
    request::{Output, Request},
};
use crate::Error;
use io_uring::squeue::Entry as SqueueEntry;
use std::task::Waker;
use tracing::warn;

/// Stable waiter identity packed into SQE/CQE `user_data`.
///
/// Layout:
/// - bits 0..31: slot index
/// - bits 32..62: generation (31 bits, wraps at 2^31)
/// - bit 63: reserved as cancel-tag in completion `user_data`
///
/// The generation counter detects stale CQEs that arrive after a slot has been
/// recycled. In normal (non-cancel) operation this cannot happen: a slot is
/// only freed after its CQE is processed, so the slot cannot be reused before
/// the CQE is consumed. With cancellation, the original op CQE can arrive
/// before the cancel CQE. When this happens the slot is freed and may be
/// recycled while the cancel CQE is still pending. The generation check
/// discards that stale cancel CQE. The 31-bit generation wraps after ~2 billion
/// reuses of the same slot, but cancellation is run synchronously on the kernel
/// side (a CQE is always generated by the time the cancel request has been
/// submitted, see
/// <https://man7.org/linux/man-pages/man3/io_uring_prep_cancel.3.html#NOTES>),
/// so a wrap-around collision is not feasible in practice.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct WaiterId(UserData);

impl WaiterId {
    /// Number of low-order bits reserved for the waiter slot index.
    const INDEX_BITS: u32 = 32;
    /// Number of bits reserved for the generation field.
    const GENERATION_BITS: u32 = 31;
    /// Bitmask that extracts the waiter slot index from packed user data.
    const INDEX_MASK: UserData = (1u64 << Self::INDEX_BITS) - 1;
    /// Bitmask that extracts the 31-bit generation from packed user data.
    const GENERATION_MASK: UserData = (1u64 << Self::GENERATION_BITS) - 1;
    /// High-bit tag used to mark cancellation CQE user data.
    const CANCEL_TAG: UserData = 1u64 << 63;

    /// Build a waiter id from slot index and generation components.
    pub const fn new(index: u32, generation: u32) -> Self {
        let index = index as UserData;
        let generation = generation as UserData;
        Self((generation & Self::GENERATION_MASK) << Self::INDEX_BITS | index)
    }

    /// Return the slot index component of this waiter id.
    pub const fn index(self) -> u32 {
        (self.0 & Self::INDEX_MASK) as u32
    }

    /// Return the generation component of this waiter id.
    const fn generation(self) -> u32 {
        ((self.0 >> Self::INDEX_BITS) & Self::GENERATION_MASK) as u32
    }

    /// Return the waiter id for the same slot with incremented generation.
    const fn next_generation(self) -> Self {
        let generation = ((self.generation() as UserData).wrapping_add(1)) & Self::GENERATION_MASK;
        Self::new(self.index(), generation as u32)
    }

    /// Encode this waiter id as `user_data` for the operation SQE/CQE.
    ///
    /// This value contains only the packed waiter identity (slot + generation),
    /// with the cancel tag bit clear.
    pub const fn user_data(self) -> UserData {
        self.0
    }

    /// Encode this waiter id as `user_data` for the cancel SQE/CQE.
    ///
    /// This preserves the waiter identity and sets the high cancel-tag bit so
    /// completion handling can distinguish cancel CQEs from operation CQEs.
    pub const fn cancel_user_data(self) -> UserData {
        self.0 | Self::CANCEL_TAG
    }

    /// Decode `user_data` into waiter identity and cancel-tag state.
    ///
    /// The returned waiter id always has the cancel-tag bit stripped. The
    /// boolean reports whether that bit was set in the input value.
    const fn from_user_data(user_data: UserData) -> (Self, bool) {
        let is_cancel = (user_data & Self::CANCEL_TAG) != 0;
        (Self(user_data & !Self::CANCEL_TAG), is_cancel)
    }
}

/// Why a request's cancellation was requested.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CancelReason {
    /// The request's deadline elapsed: the observer sees [Error::Timeout].
    ///
    /// Also used for drop-orphaned requests, whose parked result is never
    /// observed (the reason is immaterial there).
    Deadline,
    /// The runtime is shutting down: the observer sees [Error::Closed],
    /// distinguishing shutdown from an ordinary operation timeout or a
    /// genuine kernel failure.
    Shutdown,
}

impl CancelReason {
    /// The error a cancelled request surfaces to its observer.
    pub const fn into_error(self) -> Error {
        match self {
            Self::Deadline => Error::Timeout,
            Self::Shutdown => Error::Closed,
        }
    }
}

/// Lifecycle state of a tracked request.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WaiterState {
    /// Request is still tracked and has not transitioned to cancellation.
    Active {
        /// Absolute wheel tick by which the request must complete.
        ///
        /// If completion has not been observed by this tick, cancellation is
        /// requested. `None` means this request has no scheduled deadline yet,
        /// either because it carries none or because its first staging has not
        /// converted the deadline to a wheel tick.
        target_tick: Option<Tick>,
    },
    /// Cancellation was requested.
    ///
    /// If the request still has an operation SQE in flight, the loop stages an
    /// async cancel. If the request is only parked in the staged queue, the
    /// loop completes it locally with the reason's error when that entry is
    /// revisited.
    CancelRequested {
        /// Why cancellation was requested (selects the observer's error).
        reason: CancelReason,
    },
}

/// Progress state of the logical request stored in a slot.
enum Lifecycle {
    /// The request is still progressing and owns all operation resources.
    Pending(Request),
    /// The terminal result is parked until the owning ticket takes it.
    ///
    /// The kernel has fully retired the operation before this state is
    /// entered, so the buffers inside the output are exclusively
    /// userspace-owned again.
    Ready(Output),
}

/// State for one tracked logical request.
struct Waiter {
    /// Stable identity of this waiter slot instance.
    id: WaiterId,
    /// Lifecycle state for the logical request stored in this slot.
    state: WaiterState,
    /// Whether the logical request currently has an operation SQE in flight.
    in_flight: bool,
    /// Whether the owning ticket was dropped.
    ///
    /// Orphaned slots deliver no result: terminal outputs are dropped and the
    /// slot is freed as soon as the kernel retires the operation.
    orphaned: bool,
    /// Waker of the task awaiting the ticket, refreshed on every poll.
    waker: Option<Waker>,
    /// Progress state and owned resources.
    lifecycle: Lifecycle,
}

/// Outcome produced when staging the next SQE for a waiter.
pub enum StageOutcome {
    /// The waiter was canceled while parked in the staged queue and completed
    /// locally with timeout.
    Timeout {
        /// Waker to invoke outside any state borrow, when a ticket still
        /// observes the parked result.
        waker: Option<Waker>,
        /// Whether the slot was freed because the ticket was already dropped.
        freed: bool,
    },
    /// The waiter is still active and produced an SQE for submission.
    Submit(SqueueEntry),
}

/// Outcome produced when handling an operation CQE for a waiter.
pub enum CompletionOutcome {
    /// The CQE belonged to an async cancel SQE and was handled internally.
    Cancel,
    /// The logical request needs another SQE and should be placed back in the
    /// staged queue.
    Requeue(WaiterId),
    /// The logical request reached a terminal state.
    ///
    /// The result was parked in the slot for the owning ticket, or dropped
    /// (and the slot freed) when the ticket was already gone.
    Complete {
        /// Waker to invoke outside any state borrow, if a ticket is waiting.
        waker: Option<Waker>,
        /// Active deadline tracking to remove from the timeout wheel, when
        /// completion happened before cancellation was requested.
        target_tick: Option<Tick>,
        /// Whether the slot was freed because the ticket was already dropped.
        freed: bool,
    },
}

/// Outcome produced when a ticket is dropped.
pub enum DropOutcome {
    /// The parked result was dropped and the slot freed.
    Freed,
    /// The request was transitioned to cancellation.
    Cancel {
        /// Whether an async-cancel SQE must be staged because an operation
        /// SQE is in flight.
        needs_sqe: bool,
        /// Scheduled deadline tick leaving active timeout tracking, if any.
        target_tick: Option<Tick>,
    },
    /// The request keeps running to completion without an observer (storage
    /// writes and syncs preserve durability semantics on caller drop).
    Detached,
}

/// Tracks logical requests and the state needed to complete them.
pub struct Waiters {
    /// Waiters indexed by slot index.
    ///
    /// Free slots have no waiter (`None`).
    entries: Vec<Option<Waiter>>,
    /// Stack of reusable waiter ids.
    free: Vec<WaiterId>,
    /// Number of tracked waiters currently stored in `entries`.
    len: usize,
    /// Number of tracked waiters still in [Lifecycle::Pending].
    pending: usize,
}

impl Waiters {
    /// Create an empty waiter set that can track at most `capacity` logical
    /// requests at once.
    pub fn new(capacity: usize) -> Self {
        let mut entries = Vec::with_capacity(capacity);
        entries.resize_with(capacity, || None);

        let mut free = Vec::with_capacity(capacity);
        free.extend((0..capacity).rev().map(|index| {
            let index = u32::try_from(index).expect("slot index overflow");
            WaiterId::new(index, 0)
        }));

        Self {
            entries,
            free,
            len: 0,
            pending: 0,
        }
    }

    /// Return the number of currently tracked waiters.
    pub const fn len(&self) -> usize {
        self.len
    }

    /// Return whether there are no tracked waiters.
    #[cfg_attr(not(test), allow(dead_code))]
    pub const fn is_empty(&self) -> bool {
        self.len == 0
    }

    /// Return the number of tracked waiters whose request is still
    /// progressing (staged, in flight, or awaiting cancellation).
    ///
    /// Parked terminal results are excluded: they hold no kernel resources
    /// and are reclaimed by their ticket, so drain termination keys on this
    /// count rather than [Self::len].
    pub const fn pending(&self) -> usize {
        self.pending
    }

    /// Return whether all waiter slots are currently occupied.
    pub const fn is_full(&self) -> bool {
        self.len == self.entries.len()
    }

    /// Insert a request and return its assigned id.
    ///
    /// The waker is stored eagerly so a completion always has an observer to
    /// wake. Deadline scheduling happens separately at first staging.
    ///
    /// Panics if no free slot is available.
    #[inline]
    pub fn insert(&mut self, request: Request, waker: Waker) -> WaiterId {
        let id = self
            .free
            .pop()
            .expect("waiters should not exceed configured capacity");
        let index = id.index() as usize;
        let replaced = self.entries[index].replace(Waiter {
            id,
            state: WaiterState::Active { target_tick: None },
            in_flight: false,
            orphaned: false,
            waker: Some(waker),
            lifecycle: Lifecycle::Pending(request),
        });
        assert!(replaced.is_none(), "free slot should not contain waiter");
        self.len += 1;
        self.pending += 1;
        id
    }

    /// Free the slot at `index`, returning its final lifecycle state.
    ///
    /// Panics if `index` is out of bounds or the slot is empty. Callers must
    /// already have validated that the slot still belongs to the expected
    /// waiter.
    fn take(&mut self, index: usize) -> Lifecycle {
        let slot = self.entries[index].take().expect("tracked waiter missing");
        self.free.push(slot.id.next_generation());
        self.len -= 1;
        if matches!(slot.lifecycle, Lifecycle::Pending(_)) {
            self.pending -= 1;
        }
        slot.lifecycle
    }

    /// Return the deadline that still needs wheel scheduling for a waiter.
    ///
    /// This is `Some` only for the first staging of a request that carries a
    /// deadline: later stagings observe the recorded tick.
    pub fn deadline_to_schedule(&self, waiter_id: WaiterId) -> Option<std::time::Instant> {
        let slot = self
            .entries
            .get(waiter_id.index() as usize)
            .and_then(Option::as_ref)?;
        if slot.id != waiter_id {
            return None;
        }
        let WaiterState::Active { target_tick: None } = slot.state else {
            return None;
        };
        let Lifecycle::Pending(request) = &slot.lifecycle else {
            return None;
        };
        request.deadline()
    }

    /// Record the scheduled wheel tick for a waiter's deadline.
    ///
    /// Panics if the waiter is not tracked, already scheduled, or already
    /// cancel-requested.
    pub fn set_target_tick(&mut self, waiter_id: WaiterId, tick: Tick) {
        let slot = self
            .entries
            .get_mut(waiter_id.index() as usize)
            .and_then(Option::as_mut)
            .expect("set_target_tick called for untracked waiter");
        assert_eq!(slot.id, waiter_id, "set_target_tick with stale waiter id");
        assert!(
            matches!(slot.state, WaiterState::Active { target_tick: None }),
            "set_target_tick called for scheduled or cancelled waiter"
        );
        slot.state = WaiterState::Active {
            target_tick: Some(tick),
        };
    }

    /// Request cancellation for an active waiter.
    ///
    /// Returns `true` when the waiter was successfully transitioned to
    /// cancel-requested. Returns `false` when the waiter id is stale, not
    /// present, already cancel-requested, or already completed.
    pub fn cancel(&mut self, waiter_id: WaiterId) -> bool {
        let Some(slot) = self.entries.get_mut(waiter_id.index() as usize) else {
            return false;
        };
        let Some(slot) = slot.as_mut() else {
            return false;
        };
        if slot.id != waiter_id {
            // Slot was reused, this CQE belongs to an older waiter generation.
            return false;
        }
        if matches!(slot.lifecycle, Lifecycle::Ready(_)) {
            // The parked result is no longer cancellable.
            return false;
        }
        match slot.state {
            WaiterState::Active { .. } => {
                slot.state = WaiterState::CancelRequested {
                    reason: CancelReason::Deadline,
                };
                true
            }
            WaiterState::CancelRequested { .. } => false,
        }
    }

    /// Request cancellation for every progressing waiter.
    ///
    /// Returns, for each transitioned waiter, its id, its deadline tick (so
    /// the caller can release timeout-wheel accounting), and whether it has an
    /// operation SQE in flight (requiring an async-cancel SQE). Waiters that
    /// are not in flight retire locally when restaged.
    pub fn cancel_active(&mut self) -> Vec<(WaiterId, Option<Tick>, bool)> {
        let mut cancelled = Vec::new();
        for slot in self.entries.iter_mut().filter_map(Option::as_mut) {
            if matches!(slot.lifecycle, Lifecycle::Ready(_)) {
                continue;
            }
            let WaiterState::Active { target_tick } = slot.state else {
                continue;
            };
            slot.state = WaiterState::CancelRequested {
                reason: CancelReason::Shutdown,
            };
            cancelled.push((slot.id, target_tick, slot.in_flight));
        }
        cancelled
    }

    /// Stage the next SQE for a waiter.
    ///
    /// This either returns the next SQE to issue, or resolves the waiter
    /// locally:
    ///
    /// - [`StageOutcome::Submit`] leaves the waiter tracked and yields the next SQE.
    /// - [`StageOutcome::Timeout`] completes the waiter locally with timeout.
    ///
    /// When this returns [`StageOutcome::Submit`], the waiter is marked as having an
    /// operation SQE outstanding immediately, so [`Waiters::is_in_flight`] will return
    /// `true` for that waiter.
    ///
    /// Panics if `waiter_id` does not refer to a currently tracked pending
    /// waiter or if the waiter already has an operation SQE outstanding.
    #[inline]
    pub fn stage(&mut self, waiter_id: WaiterId) -> StageOutcome {
        let index = waiter_id.index() as usize;
        let slot = self
            .entries
            .get_mut(index)
            .and_then(Option::as_mut)
            .expect("stage called for untracked waiter");
        assert_eq!(slot.id, waiter_id, "stage called with stale waiter id");
        let Lifecycle::Pending(request) = &mut slot.lifecycle else {
            panic!("stage called for completed waiter");
        };

        match slot.state {
            WaiterState::CancelRequested { reason } => {
                // Cancellation marked while the request sat in the staged
                // queue: an in-flight request is never restaged (its CQE
                // requeues it with `in_flight` already cleared), and freeing
                // an in-flight slot below would release kernel-referenced
                // buffers.
                assert!(
                    !slot.in_flight,
                    "stage called for cancelled waiter with op in flight"
                );
                if slot.orphaned {
                    // Nobody can take the parked result, so free the slot.
                    let _ = self.take(index);
                    StageOutcome::Timeout {
                        waker: None,
                        freed: true,
                    }
                } else {
                    // The output moves the owned buffer out of the request,
                    // so the emptied shell drops in place. The reason selects
                    // what the observer sees: a deadline expiry surfaces as
                    // timeout, a shutdown as closed.
                    let output = request.interrupt(reason.into_error());
                    let waker = self.park_output_at(index, output);
                    StageOutcome::Timeout {
                        waker,
                        freed: false,
                    }
                }
            }
            WaiterState::Active { .. } => {
                // An orphaned request whose kind stops on orphaning is moved
                // to `CancelRequested` by `mark_orphaned` before it can ever
                // be staged again, so it must never surface here: retiring it
                // from this arm would silently resurrect stale wind-down
                // logic if the state machine drifts.
                assert!(
                    !slot.orphaned || !request.orphan_stops_progress(),
                    "orphan-stopping request staged while active"
                );
                assert!(
                    !slot.in_flight,
                    "stage called for waiter with op already in flight"
                );
                slot.in_flight = true;
                StageOutcome::Submit(request.build_sqe(waiter_id))
            }
        }
    }

    /// Process one CQE for a waiter.
    ///
    /// Cancel CQEs are handled internally. Operation CQEs drive the request
    /// state machine and return a high-level loop action. Terminal results are
    /// parked in the slot for the owning ticket, or dropped (freeing the slot)
    /// when the ticket is already gone.
    ///
    /// Panics if a non-cancel CQE does not refer to a currently tracked waiter,
    /// if it uses a stale waiter generation, or if the waiter has no operation
    /// SQE outstanding.
    #[inline]
    pub fn on_completion(&mut self, user_data: UserData, result: i32) -> CompletionOutcome {
        let (waiter_id, is_cancel) = WaiterId::from_user_data(user_data);
        let index = waiter_id.index() as usize;

        let Some(slot) = self.entries.get_mut(index).and_then(Option::as_mut) else {
            assert!(is_cancel, "operation CQE for untracked waiter");
            return CompletionOutcome::Cancel;
        };
        if slot.id != waiter_id {
            assert!(is_cancel, "operation CQE for stale waiter generation");
            return CompletionOutcome::Cancel;
        }

        if is_cancel {
            if result == 0 {
                // Cancellation successful.
            } else if result == -libc::EALREADY {
                // Cancellation is no longer possible at this stage. The target
                // operation CQE should follow shortly.
            } else if result == -libc::ENOENT {
                // Not found can mean the target already completed (common race) or
                // stale/invalid user_data.
            } else if result == -libc::EINVAL {
                panic!("async cancel SQE rejected by kernel: EINVAL");
            } else {
                warn!(result, "unexpected async cancel CQE result");
            }

            // Cancel CQEs acknowledge cancel requests but do not complete waiters.
            return CompletionOutcome::Cancel;
        }

        let Lifecycle::Pending(request) = &mut slot.lifecycle else {
            panic!("operation CQE for completed waiter");
        };

        // The operation CQE retires the currently in-flight SQE, regardless of
        // whether the request completes or is requeued for another one.
        assert!(slot.in_flight);
        slot.in_flight = false;

        let state = slot.state;
        let orphaned = slot.orphaned;
        let orphan_stops = request.orphan_stops_progress();
        let output = request.on_cqe(state, result);
        if output.is_none() && !(orphaned && orphan_stops) {
            return CompletionOutcome::Requeue(waiter_id);
        }

        // Either the request reached a terminal state, or the current SQE
        // made non-terminal progress for a ticket that is already gone. In
        // both cases, stop issuing SQEs for this waiter now.
        let target_tick = match state {
            WaiterState::Active { target_tick } => target_tick,
            WaiterState::CancelRequested { .. } => None,
        };

        if orphaned {
            // Free the slot (dropping the request shell in place) and drop
            // the output: closing any owned resources (e.g. an accepted fd)
            // without an observer.
            let _ = self.take(index);
            drop(output);
            CompletionOutcome::Complete {
                waker: None,
                target_tick,
                freed: true,
            }
        } else {
            let output = output.expect("non-orphaned completion is terminal");
            let waker = self.park_output_at(index, output);
            CompletionOutcome::Complete {
                waker,
                target_tick,
                freed: false,
            }
        }
    }

    /// Park `output` in the slot at `index`, dropping the pending request
    /// shell in place, and return the parked waker.
    fn park_output_at(&mut self, index: usize, output: Output) -> Option<Waker> {
        let slot = self.entries[index]
            .as_mut()
            .expect("tracked waiter missing");
        slot.lifecycle = Lifecycle::Ready(output);
        self.pending -= 1;
        slot.waker.take()
    }

    /// Take the parked result for a ticket, freeing the slot, or refresh the
    /// stored waker when the request is still progressing.
    ///
    /// Panics if the waiter is not tracked or the id is stale: only the owning
    /// ticket frees a non-orphaned slot, so a miss is an invariant violation.
    #[inline]
    pub fn poll_take(&mut self, waiter_id: WaiterId, waker: &Waker) -> Option<Output> {
        let index = waiter_id.index() as usize;
        let slot = self
            .entries
            .get_mut(index)
            .and_then(Option::as_mut)
            .expect("poll_take called for untracked waiter");
        assert_eq!(slot.id, waiter_id, "poll_take called with stale waiter id");

        match &mut slot.lifecycle {
            Lifecycle::Ready(_) => {
                let Lifecycle::Ready(output) = self.take(index) else {
                    unreachable!("lifecycle verified ready above");
                };
                Some(output)
            }
            Lifecycle::Pending(_) => {
                match &mut slot.waker {
                    Some(existing) => existing.clone_from(waker),
                    None => slot.waker = Some(waker.clone()),
                }
                None
            }
        }
    }

    /// Mark a waiter's ticket as dropped and resolve how its slot winds down.
    ///
    /// Parked results are dropped and their slot freed immediately. Requests
    /// whose kind stops progressing without an observer transition to
    /// cancellation. Storage writes and syncs detach and keep running.
    ///
    /// Panics if the waiter is not tracked or the id is stale.
    pub fn mark_orphaned(&mut self, waiter_id: WaiterId) -> DropOutcome {
        let index = waiter_id.index() as usize;
        let slot = self
            .entries
            .get_mut(index)
            .and_then(Option::as_mut)
            .expect("mark_orphaned called for untracked waiter");
        assert_eq!(
            slot.id, waiter_id,
            "mark_orphaned called with stale waiter id"
        );

        let Lifecycle::Pending(request) = &slot.lifecycle else {
            let _ = self.take(index);
            return DropOutcome::Freed;
        };

        slot.orphaned = true;
        slot.waker = None;
        if !request.orphan_stops_progress() {
            return DropOutcome::Detached;
        }
        match slot.state {
            WaiterState::Active { target_tick } => {
                // The ticket is gone, so the parked result (and its reason)
                // is never observed.
                slot.state = WaiterState::CancelRequested {
                    reason: CancelReason::Deadline,
                };
                DropOutcome::Cancel {
                    needs_sqe: slot.in_flight,
                    target_tick,
                }
            }
            // Cancellation was already requested (e.g. by timeout expiry,
            // which released deadline accounting), so the existing wind-down
            // path retires the slot.
            WaiterState::CancelRequested { .. } => DropOutcome::Cancel {
                needs_sqe: false,
                target_tick: None,
            },
        }
    }

    /// Return whether a waiter currently has an operation SQE in flight.
    pub fn is_in_flight(&self, waiter_id: WaiterId) -> bool {
        let index = waiter_id.index() as usize;
        self.entries
            .get(index)
            .and_then(Option::as_ref)
            .is_some_and(|slot| slot.id == waiter_id && slot.in_flight)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        IoBuf, IoBufMut, IoBufs,
        iouring::driver::request::{ReadAtRequest, RecvRequest, SendRequest, SyncRequest},
    };
    use futures::task::noop_waker;
    use std::{
        os::fd::{FromRawFd, IntoRawFd},
        panic::{AssertUnwindSafe, catch_unwind},
        sync::Arc,
    };

    /// Build a `Sync` request backed by a socket fd so waiter tests can
    /// exercise slot lifecycle without touching the filesystem.
    fn make_sync_request() -> Request {
        let (sock_left, _sock_right) =
            std::os::unix::net::UnixStream::pair().expect("failed to create unix socket pair");
        // SAFETY: sock_left is a valid fd that we own.
        let file = unsafe { std::fs::File::from_raw_fd(sock_left.into_raw_fd()) };
        Request::Sync(SyncRequest {
            file: Arc::new(file),
        })
    }

    fn make_send_request() -> Request {
        Request::Send(SendRequest {
            fd: Arc::new(std::os::unix::net::UnixStream::pair().unwrap().0.into()),
            write: IoBufs::from(IoBuf::from(b"hello")).into(),
            deadline: None,
        })
    }

    fn make_recv_request() -> Request {
        Request::Recv(RecvRequest {
            fd: Arc::new(std::os::unix::net::UnixStream::pair().unwrap().0.into()),
            buf: IoBufMut::with_capacity(5),
            offset: 0,
            len: 5,
            exact: true,
            deadline: None,
        })
    }

    fn make_read_at_request() -> Request {
        let (sock_left, _sock_right) =
            std::os::unix::net::UnixStream::pair().expect("failed to create unix socket pair");
        // SAFETY: sock_left is a valid fd that we own.
        let file = unsafe { std::fs::File::from_raw_fd(sock_left.into_raw_fd()) };
        Request::ReadAt(ReadAtRequest {
            file: Arc::new(file),
            offset: 0,
            len: 8,
            read: 0,
            buf: IoBufMut::with_capacity(8),
        })
    }

    fn insert(waiters: &mut Waiters, request: Request, tick: Option<Tick>) -> WaiterId {
        let id = waiters.insert(request, noop_waker());
        if let Some(tick) = tick {
            waiters.set_target_tick(id, tick);
        }
        id
    }

    fn waiter_state(waiters: &Waiters, waiter_id: WaiterId) -> Option<WaiterState> {
        let index = waiter_id.index() as usize;
        let slot = waiters.entries.get(index)?.as_ref()?;
        (slot.id == waiter_id).then_some(slot.state)
    }

    fn remove_waiter(waiters: &mut Waiters, waiter_id: WaiterId) -> Lifecycle {
        let index = waiter_id.index() as usize;
        let slot = waiters
            .entries
            .get(index)
            .and_then(Option::as_ref)
            .expect("remove_waiter called for untracked waiter");
        assert_eq!(
            slot.id, waiter_id,
            "remove_waiter called with stale waiter id"
        );
        waiters.take(index)
    }

    #[test]
    fn test_waiter_id_encoding_and_generation_wrap() {
        // Verify waiter ids round-trip through user_data encoding and wrap their generation field
        // without corrupting the slot index bits.
        let wrapped = WaiterId::new(7, (WaiterId::GENERATION_MASK as u32).wrapping_add(5));
        assert_eq!(wrapped.generation(), 4);

        let max = WaiterId::new(7, WaiterId::GENERATION_MASK as u32);
        assert_eq!(max.next_generation().generation(), 0);

        let waiter_id = WaiterId::new(7, 3);
        assert_eq!(waiter_id.index(), 7);
        assert_eq!(waiter_id.generation(), 3);

        let (decoded_op, is_cancel_op) = WaiterId::from_user_data(waiter_id.user_data());
        assert_eq!(decoded_op, waiter_id);
        assert!(!is_cancel_op);

        let (decoded_cancel, is_cancel) = WaiterId::from_user_data(waiter_id.cancel_user_data());
        assert_eq!(decoded_cancel, waiter_id);
        assert!(is_cancel);
    }

    #[test]
    fn test_waiters_lifecycle_and_slot_reuse() {
        // Verify waiter insertion, completion, removal, and slot reuse all preserve generations.
        let mut waiters = Waiters::new(3);
        assert_eq!(waiters.entries.len(), 3);
        assert_eq!(waiters.len(), 0);
        assert!(waiters.is_empty());

        // Populate two slots so the test can later free and reuse one of them.
        let id0 = insert(&mut waiters, make_sync_request(), Some(5));
        let id1 = insert(&mut waiters, make_sync_request(), Some(9));
        assert_eq!((id0.index(), id1.index()), (0, 1));
        assert_eq!(waiters.len(), 2);
        assert_eq!(waiters.pending(), 2);
        assert!(!waiters.is_full());

        // A stale operation CQE should panic because only cancel CQEs are
        // expected to arrive after slot reuse.
        let stale = WaiterId::new(id1.index(), id1.generation().wrapping_add(1));
        let stale_completion = catch_unwind(AssertUnwindSafe(|| {
            let _ = waiters.on_completion(stale.user_data(), 0);
        }));
        assert!(stale_completion.is_err());

        // Complete id1: the result parks in the slot until taken.
        assert!(matches!(waiters.stage(id1), StageOutcome::Submit(_)));
        assert!(matches!(
            waiters.on_completion(id1.user_data(), 0),
            CompletionOutcome::Complete {
                target_tick: Some(9),
                freed: false,
                ..
            }
        ));
        assert_eq!(waiters.len(), 2);
        assert_eq!(waiters.pending(), 1);
        assert!(matches!(
            waiters.poll_take(id1, &noop_waker()),
            Some(Output::Sync(Ok(())))
        ));
        assert_eq!(waiters.len(), 1);

        // Next allocation reuses the freed slot with incremented generation.
        let id2 = insert(&mut waiters, make_sync_request(), Some(11));
        assert_eq!(id2.index(), id1.index());
        assert_eq!(
            id2.generation(),
            id1.generation().wrapping_add(1) & (WaiterId::GENERATION_MASK as u32)
        );

        // All live waiters should still complete and remove cleanly after slot reuse.
        assert!(matches!(waiters.stage(id0), StageOutcome::Submit(_)));
        let _ = waiters.on_completion(id0.user_data(), 0);
        assert!(waiters.poll_take(id0, &noop_waker()).is_some());
        assert!(matches!(waiters.stage(id2), StageOutcome::Submit(_)));
        let _ = waiters.on_completion(id2.user_data(), 0);
        assert!(waiters.poll_take(id2, &noop_waker()).is_some());
        assert!(waiters.is_empty());
    }

    #[test]
    fn test_waiters_cancel_paths() {
        // Verify cancel requests transition waiter state, ignore cancel CQEs for completion, and
        // discard late cancel CQEs once the original operation has already completed.
        let mut waiters = Waiters::new(3);

        let waiter_id = insert(&mut waiters, make_sync_request(), Some(2));

        let stale = WaiterId::new(waiter_id.index(), waiter_id.generation().wrapping_add(1));
        assert!(!waiters.cancel(stale));

        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(
            waiters.cancel(waiter_id),
            "cancel should transition active waiter"
        );

        // Cancel CQE does not complete the waiter.
        assert!(matches!(
            waiters.on_completion(waiter_id.cancel_user_data(), -libc::ECANCELED),
            CompletionOutcome::Cancel
        ));

        // Op CQE completes the waiter.
        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), 0),
            CompletionOutcome::Complete {
                target_tick: None,
                freed: false,
                ..
            }
        ));
        assert_eq!(waiters.pending(), 0);
        assert!(waiters.poll_take(waiter_id, &noop_waker()).is_some());
        assert!(waiters.is_empty());

        // Late cancel CQE for the already-completed waiter should be ignored.
        assert!(matches!(
            waiters.on_completion(waiter_id.cancel_user_data(), -libc::ECANCELED),
            CompletionOutcome::Cancel
        ));
        let missing_op_cqe = catch_unwind(AssertUnwindSafe(|| {
            let _ = waiters.on_completion(0, 1);
        }));
        assert!(missing_op_cqe.is_err());
    }

    #[test]
    fn test_waiters_track_in_flight_state() {
        // Verify `stage` tracks a staged operation and that the bit is
        // cleared again when the matching op CQE is processed.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), Some(4));

        assert!(waiters.is_full());
        assert!(!waiters.is_in_flight(waiter_id));
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(waiters.is_in_flight(waiter_id));

        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), 0),
            CompletionOutcome::Complete { .. }
        ));
        assert!(!waiters.is_in_flight(waiter_id));
    }

    #[test]
    fn test_waiters_reject_stale_in_flight_queries() {
        // Verify stale waiter ids cannot observe in-flight state after
        // their slot has been recycled to a new generation.
        let mut waiters = Waiters::new(1);
        let stale_id = insert(&mut waiters, make_sync_request(), Some(1));
        let _ = remove_waiter(&mut waiters, stale_id);

        let active_id = insert(&mut waiters, make_sync_request(), Some(2));
        assert_ne!(active_id, stale_id);

        assert!(!waiters.is_in_flight(stale_id));
        assert!(matches!(waiters.stage(active_id), StageOutcome::Submit(_)));
        assert!(waiters.is_in_flight(active_id));
    }

    #[test]
    fn test_waiters_stage_panics_for_out_of_range_and_empty_slots() {
        // Verify `stage` treats impossible waiter ids as invariant failures,
        // while the tolerant query/cancel paths still reject them cleanly.
        let mut waiters = Waiters::new(1);
        let out_of_range = WaiterId::new(7, 0);
        assert!(!waiters.cancel(out_of_range));
        let out_of_range_stage = catch_unwind(AssertUnwindSafe(|| {
            let _ = waiters.stage(out_of_range);
        }));
        assert!(out_of_range_stage.is_err());

        let empty_slot = WaiterId::new(0, 0);
        assert!(!waiters.cancel(empty_slot));
        let empty_slot_stage = catch_unwind(AssertUnwindSafe(|| {
            let _ = waiters.stage(empty_slot);
        }));
        assert!(empty_slot_stage.is_err());
    }

    #[test]
    fn test_waiters_cancel_and_in_flight_reject_out_of_range_and_empty_slots() {
        // Verify cancel and in-flight tracking reject waiter ids that point
        // outside the table or at currently empty slots.
        let mut waiters = Waiters::new(1);
        let out_of_range = WaiterId::new(7, 0);
        assert!(!waiters.cancel(out_of_range));
        assert!(!waiters.is_in_flight(out_of_range));

        let empty_slot = WaiterId::new(0, 0);
        assert!(!waiters.cancel(empty_slot));
        assert!(!waiters.is_in_flight(empty_slot));
    }

    #[test]
    fn test_waiters_cancel_stage_only_when_in_flight() {
        // Verify timeout processing can distinguish between:
        // - a waiter whose current SQE is still in flight
        // - a waiter that is only parked in the staged queue
        let mut waiters = Waiters::new(2);

        // First build a waiter that still has an operation SQE outstanding.
        let active = insert(&mut waiters, make_sync_request(), Some(2));
        assert!(matches!(waiters.stage(active), StageOutcome::Submit(_)));
        assert!(waiters.cancel(active));
        assert!(waiters.is_in_flight(active));
        let active_state = waiter_state(&waiters, active).expect("active waiter missing");
        assert!(matches!(active_state, WaiterState::CancelRequested { .. }));

        // Then build a waiter that has been canceled before any SQE was staged.
        let ready = insert(&mut waiters, make_sync_request(), Some(3));
        assert!(waiters.cancel(ready));
        assert!(!waiters.is_in_flight(ready));
        let ready_state = waiter_state(&waiters, ready).expect("ready waiter missing");
        assert!(matches!(ready_state, WaiterState::CancelRequested { .. }));
    }

    #[test]
    fn test_waiters_stage_orphans_dropped_tickets() {
        // Verify orphaned send and read-at requests are removed locally before
        // their first SQE is ever staged.
        for (request, tick) in [(make_send_request(), 7), (make_read_at_request(), 8)] {
            let mut waiters = Waiters::new(1);
            let waiter_id = insert(&mut waiters, request, Some(tick));
            assert!(matches!(
                waiters.mark_orphaned(waiter_id),
                DropOutcome::Cancel {
                    needs_sqe: false,
                    target_tick: Some(_),
                }
            ));

            match waiters.stage(waiter_id) {
                StageOutcome::Timeout {
                    waker: None,
                    freed: true,
                } => {}
                _ => panic!("orphaned waiter should be retired before staging"),
            }
            assert!(waiters.is_empty());
        }
    }

    #[test]
    fn test_waiters_orphan_dropped_tickets_after_nonterminal_completion() {
        // Verify retryable and partial-progress send, recv, and read-at CQEs
        // remove the waiter instead of requeueing once the ticket is gone.
        for (request, tick, result) in [
            // Retryable CQE.
            (make_send_request(), 5, -libc::EAGAIN),
            // Partial-progress CQE.
            (make_send_request(), 5, 2),
            (make_recv_request(), 6, -libc::EAGAIN),
            (make_recv_request(), 6, 3),
            (make_read_at_request(), 9, 3),
        ] {
            let mut waiters = Waiters::new(1);
            let waiter_id = insert(&mut waiters, request, Some(tick));
            assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
            assert!(matches!(
                waiters.mark_orphaned(waiter_id),
                DropOutcome::Cancel {
                    needs_sqe: true,
                    ..
                }
            ));

            match waiters.on_completion(waiter_id.user_data(), result) {
                CompletionOutcome::Complete {
                    waker: None,
                    // Cancellation transitioned the waiter, so deadline
                    // tracking was already released.
                    target_tick: None,
                    freed: true,
                } => {}
                _ => panic!("orphaned waiter should be freed after CQE"),
            }
            assert!(waiters.is_empty());
        }
    }

    #[test]
    fn test_waiters_detach_write_and_sync_on_drop() {
        // Verify write/sync requests keep progressing after their ticket is
        // dropped and free their slot at the terminal CQE.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), None);
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(matches!(
            waiters.mark_orphaned(waiter_id),
            DropOutcome::Detached
        ));

        // The waiter is still active: no cancellation was requested.
        let state = waiter_state(&waiters, waiter_id).expect("waiter should remain tracked");
        assert!(matches!(state, WaiterState::Active { .. }));

        // The terminal CQE frees the slot without parking a result.
        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), 0),
            CompletionOutcome::Complete {
                waker: None,
                freed: true,
                ..
            }
        ));
        assert!(waiters.is_empty());
    }

    #[test]
    fn test_waiters_drop_after_completion_frees_slot() {
        // Verify dropping a ticket whose result is already parked frees the
        // slot and drops the output.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), None);
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), 0),
            CompletionOutcome::Complete { freed: false, .. }
        ));
        assert_eq!(waiters.pending(), 0);
        assert_eq!(waiters.len(), 1);

        assert!(matches!(
            waiters.mark_orphaned(waiter_id),
            DropOutcome::Freed
        ));
        assert!(waiters.is_empty());
    }

    #[test]
    fn test_waiters_deadline_scheduling() {
        // Verify deadline bookkeeping: only unscheduled deadlines are
        // reported, and recording a tick transitions the waiter.
        let mut waiters = Waiters::new(2);

        // Sync requests carry no deadline.
        let sync_id = waiters.insert(make_sync_request(), noop_waker());
        assert!(waiters.deadline_to_schedule(sync_id).is_none());

        // Send requests with a deadline report it exactly once.
        let deadline = std::time::Instant::now();
        let send_id = waiters.insert(
            Request::Send(SendRequest {
                fd: Arc::new(std::os::unix::net::UnixStream::pair().unwrap().0.into()),
                write: IoBufs::from(IoBuf::from(b"hello")).into(),
                deadline: Some(deadline),
            }),
            noop_waker(),
        );
        assert_eq!(waiters.deadline_to_schedule(send_id), Some(deadline));
        waiters.set_target_tick(send_id, 3);
        assert!(waiters.deadline_to_schedule(send_id).is_none());
        assert!(matches!(
            waiter_state(&waiters, send_id),
            Some(WaiterState::Active {
                target_tick: Some(3)
            })
        ));

        // Rescheduling a scheduled waiter is an invariant violation.
        let double_schedule = catch_unwind(AssertUnwindSafe(|| {
            waiters.set_target_tick(send_id, 4);
        }));
        assert!(double_schedule.is_err());
    }

    #[test]
    fn test_waiters_poll_take_refreshes_waker() {
        // Verify pending polls refresh the stored waker rather than taking
        // the slot.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), None);
        assert!(waiters.poll_take(waiter_id, &noop_waker()).is_none());
        assert_eq!(waiters.pending(), 1);

        // Stale ids panic rather than observing a reused slot.
        let _ = remove_waiter(&mut waiters, waiter_id);
        let stale_take = catch_unwind(AssertUnwindSafe(|| {
            let _ = waiters.poll_take(waiter_id, &noop_waker());
        }));
        assert!(stale_take.is_err());
    }

    #[test]
    fn test_waiters_accept_expected_cancel_cqe_results() {
        // Verify the expected kernel cancel CQE results leave the waiter alive
        // for the original operation CQE to finish it later.
        for result in [0, -libc::EALREADY, -libc::ENOENT] {
            let mut waiters = Waiters::new(1);
            let waiter_id = insert(&mut waiters, make_sync_request(), Some(2));
            assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
            assert!(waiters.cancel(waiter_id));

            assert!(matches!(
                waiters.on_completion(waiter_id.cancel_user_data(), result),
                CompletionOutcome::Cancel
            ));
            let state = waiter_state(&waiters, waiter_id).expect("waiter should remain tracked");
            assert!(matches!(state, WaiterState::CancelRequested { .. }));
        }
    }

    #[test]
    fn test_waiters_tolerate_unexpected_negative_cancel_result() {
        // Verify unexpected negative cancel CQEs are ignored rather than
        // corrupting waiter state.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), Some(2));
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(waiters.cancel(waiter_id));

        assert!(matches!(
            waiters.on_completion(waiter_id.cancel_user_data(), -libc::EPERM),
            CompletionOutcome::Cancel
        ));
        let state = waiter_state(&waiters, waiter_id).expect("waiter should remain tracked");
        assert!(matches!(state, WaiterState::CancelRequested { .. }));
    }

    #[test]
    fn test_waiters_cancel_cqe_einval_panics() {
        // Verify `EINVAL` remains a hard invariant failure because the kernel
        // rejected our async cancel SQE.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), Some(2));
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(waiters.cancel(waiter_id));

        let result = catch_unwind(AssertUnwindSafe(|| {
            let _ = waiters.on_completion(waiter_id.cancel_user_data(), -libc::EINVAL);
        }));
        assert!(result.is_err());
    }

    #[test]
    fn test_waiters_cancel_rejects_parked_results() {
        // Verify parked results can no longer transition to cancellation
        // (e.g. from a stale timeout-wheel entry).
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), None);
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), 0),
            CompletionOutcome::Complete { freed: false, .. }
        ));
        assert!(!waiters.cancel(waiter_id));
        assert!(waiters.poll_take(waiter_id, &noop_waker()).is_some());
    }

    #[test]
    fn test_waiters_stale_ids_cannot_remove_reused_slots() {
        // Verify stale waiter ids cannot observe state or remove a reused slot.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_sync_request(), Some(1));
        let _ = remove_waiter(&mut waiters, waiter_id);

        let reused_id = insert(&mut waiters, make_sync_request(), Some(2));
        assert_ne!(reused_id, waiter_id);
        assert!(waiter_state(&waiters, waiter_id).is_none());
        let stale_remove = catch_unwind(AssertUnwindSafe(|| {
            let _ = remove_waiter(&mut waiters, waiter_id);
        }));
        assert!(stale_remove.is_err());
    }

    #[test]
    fn test_waiters_insert_and_cancel_invariants() {
        // Verify waiter capacity is enforced and that cancel remains valid even for waiters that
        // were inserted without a deadline.
        let mut waiters = Waiters::new(2);

        // Inserting beyond configured capacity should panic.
        let _ = waiters.insert(make_sync_request(), noop_waker());
        let _ = waiters.insert(make_sync_request(), noop_waker());
        assert!(waiters.is_full());
        let insert_overflow = catch_unwind(AssertUnwindSafe(|| {
            let _ = waiters.insert(make_sync_request(), noop_waker());
        }));
        assert!(insert_overflow.is_err());

        // Cancellation is allowed even when no deadline is tracked.
        let mut waiters = Waiters::new(2);
        let no_deadline = waiters.insert(make_sync_request(), noop_waker());
        assert!(
            waiters.cancel(no_deadline),
            "cancel should support active waiter without deadline"
        );

        // Repeated cancel on the same waiter must be ignored.
        let active = insert(&mut waiters, make_sync_request(), Some(3));
        assert!(waiters.cancel(active));
        assert!(!waiters.cancel(active));
    }

    #[test]
    fn test_waiters_cancel_active_skips_parked_results() {
        // Verify shutdown-time cancel-all only transitions progressing
        // waiters.
        let mut waiters = Waiters::new(3);

        // One parked result, one in-flight waiter, one already cancelled.
        let parked = insert(&mut waiters, make_sync_request(), None);
        assert!(matches!(waiters.stage(parked), StageOutcome::Submit(_)));
        assert!(matches!(
            waiters.on_completion(parked.user_data(), 0),
            CompletionOutcome::Complete { .. }
        ));

        let in_flight = insert(&mut waiters, make_sync_request(), Some(2));
        assert!(matches!(waiters.stage(in_flight), StageOutcome::Submit(_)));

        let cancelled = insert(&mut waiters, make_sync_request(), Some(3));
        assert!(waiters.cancel(cancelled));

        let transitioned = waiters.cancel_active();
        assert_eq!(transitioned.len(), 1);
        assert_eq!(transitioned[0].0, in_flight);
        assert_eq!(transitioned[0].1, Some(2));
        assert!(transitioned[0].2);
    }

    #[test]
    fn test_shutdown_cancellation_is_not_reported_as_deadline_timeout() {
        // `cancel_active` is the shutdown-budget path. Its cancellation must
        // remain distinguishable from `cancel`, which is also used by the
        // request deadline path: a shutdown surfaces as closed, not as an
        // ordinary operation timeout.
        let mut waiters = Waiters::new(1);
        let waiter_id = insert(&mut waiters, make_recv_request(), Some(7));
        assert!(matches!(waiters.stage(waiter_id), StageOutcome::Submit(_)));
        assert_eq!(waiters.cancel_active().len(), 1);

        assert!(matches!(
            waiters.on_completion(waiter_id.user_data(), -libc::ECANCELED),
            CompletionOutcome::Complete { .. }
        ));
        let Some(Output::Recv(Err(error))) = waiters.poll_take(waiter_id, &noop_waker()) else {
            panic!("shutdown-cancelled recv did not produce an error");
        };
        let (_, error) = *error;
        assert!(
            matches!(error, Error::Closed),
            "expected shutdown cancellation to be Closed, got {error:?}"
        );
    }
}
