[package]
name = "commonware-fmt"
edition.workspace = true
publish = false
version.workspace = true
license.workspace = true
description = "Format Commonware macro invocations."
homepage.workspace = true
repository = "https://github.com/commonwarexyz/monorepo/tree/main/fmt"

[lints]
workspace = true

[lib]
bench = false

[dependencies]
clap = { workspace = true, features = ["derive"] }
commonware-macros-grammar.workspace = true
proc-macro2 = { workspace = true, features = ["span-locations"] }
quote.workspace = true
syn = { workspace = true, features = ["full", "visit", "visit-mut"] }
tempfile.workspace = true
thiserror.workspace = true
