// @generated by sandblaster from `samples/patterns/mod.rs`. Do not edit.
// STATUS: UNVERIFIED (phase 1): proofs, obligations and the optimizer have NOT run.
// This code was only type checked and validated against the sandblaster subset.
#[cfg(not(target_pointer_width = "64"))]
compile_error!("sandblaster requires a 64-bit target");
#[deny(unsafe_code, overflowing_literals, unconditional_recursion)]
#[allow(arithmetic_overflow, unconditional_panic, dead_code, unused_variables, unused_mut, unused_assignments, unused_parens, unused_braces, unused_unsafe, unreachable_patterns, unreachable_code, irrefutable_let_patterns, non_snake_case, non_camel_case_types, non_upper_case_globals, clippy::all)]
mod __sandblaster {
    #[doc = " Nested or-patterns with a guard: every matching alternative is tried."]
    pub fn nested_or(l0_a: ::core::option::Option<u8>, l1_b: ::core::option::Option<u8>, l2_c: u8) -> u8 {
        {
            let t1__scrut: ((::core::option::Option<u8>, ::core::option::Option<u8>), u8) = ((l0_a, l1_b), l2_c);
            match t1__scrut {
                ((::core::option::Option::Some(l3_x), _), 0u8) => if l3_x > 2u8 { l3_x } else {
                    match t1__scrut {
                        ((::core::option::Option::Some(l3_x), _), 1u8) => if l3_x > 2u8 { l3_x } else {
                            match t1__scrut {
                                ((_, ::core::option::Option::Some(l3_x)), 0u8) => if l3_x > 2u8 { l3_x } else {
                                    match t1__scrut {
                                        ((_, ::core::option::Option::Some(l3_x)), 1u8) => if l3_x > 2u8 { l3_x } else {
                                            match t1__scrut {
                                                ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                                                    match t1__scrut {
                                                        _ => 0u8,
                                                    }
                                                },
                                                _ => 0u8,
                                            }
                                        },
                                        ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                                            match t1__scrut {
                                                _ => 0u8,
                                            }
                                        },
                                        _ => 0u8,
                                    }
                                },
                                ((_, ::core::option::Option::Some(l3_x)), 1u8) => if l3_x > 2u8 { l3_x } else {
                                    match t1__scrut {
                                        ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                                            match t1__scrut {
                                                _ => 0u8,
                                            }
                                        },
                                        _ => 0u8,
                                    }
                                },
                                ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                                    match t1__scrut {
                                        _ => 0u8,
                                    }
                                },
                                _ => 0u8,
                            }
                        },
                        ((_, ::core::option::Option::Some(l3_x)), 0u8) => if l3_x > 2u8 { l3_x } else {
                            match t1__scrut {
                                ((_, ::core::option::Option::Some(l3_x)), 1u8) => if l3_x > 2u8 { l3_x } else {
                                    match t1__scrut {
                                        ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                                            match t1__scrut {
                                                _ => 0u8,
                                            }
                                        },
                                        _ => 0u8,
                                    }
                                },
                                ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                                    match t1__scrut {
                                        _ => 0u8,
                                    }
                                },
                                _ => 0u8,
                            }
                        },
                        ((_, ::core::option::Option::Some(l3_x)), 1u8) => if l3_x > 2u8 { l3_x } else {
                            match t1__scrut {
                                ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                                    match t1__scrut {
                                        _ => 0u8,
                                    }
                                },
                                _ => 0u8,
                            }
                        },
                        ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                            match t1__scrut {
                                _ => 0u8,
                            }
                        },
                        _ => 0u8,
                    }
                },
                ((::core::option::Option::Some(l3_x), _), 1u8) => if l3_x > 2u8 { l3_x } else {
                    match t1__scrut {
                        ((_, ::core::option::Option::Some(l3_x)), 0u8) => if l3_x > 2u8 { l3_x } else {
                            match t1__scrut {
                                ((_, ::core::option::Option::Some(l3_x)), 1u8) => if l3_x > 2u8 { l3_x } else {
                                    match t1__scrut {
                                        ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                                            match t1__scrut {
                                                _ => 0u8,
                                            }
                                        },
                                        _ => 0u8,
                                    }
                                },
                                ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                                    match t1__scrut {
                                        _ => 0u8,
                                    }
                                },
                                _ => 0u8,
                            }
                        },
                        ((_, ::core::option::Option::Some(l3_x)), 1u8) => if l3_x > 2u8 { l3_x } else {
                            match t1__scrut {
                                ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                                    match t1__scrut {
                                        _ => 0u8,
                                    }
                                },
                                _ => 0u8,
                            }
                        },
                        ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                            match t1__scrut {
                                _ => 0u8,
                            }
                        },
                        _ => 0u8,
                    }
                },
                ((_, ::core::option::Option::Some(l3_x)), 0u8) => if l3_x > 2u8 { l3_x } else {
                    match t1__scrut {
                        ((_, ::core::option::Option::Some(l3_x)), 1u8) => if l3_x > 2u8 { l3_x } else {
                            match t1__scrut {
                                ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                                    match t1__scrut {
                                        _ => 0u8,
                                    }
                                },
                                _ => 0u8,
                            }
                        },
                        ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                            match t1__scrut {
                                _ => 0u8,
                            }
                        },
                        _ => 0u8,
                    }
                },
                ((_, ::core::option::Option::Some(l3_x)), 1u8) => if l3_x > 2u8 { l3_x } else {
                    match t1__scrut {
                        ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                            match t1__scrut {
                                _ => 0u8,
                            }
                        },
                        _ => 0u8,
                    }
                },
                ((::core::option::Option::None, ::core::option::Option::None), l4_k) => if l4_k > 5u8 { l4_k } else {
                    match t1__scrut {
                        _ => 0u8,
                    }
                },
                _ => 0u8,
            }
        }
    }
    #[doc = " The order in which nested alternatives are tried is observable."]
    pub fn order(l0_p: (::core::option::Option<u8>, ::core::option::Option<u8>), l1_q: (::core::option::Option<u8>, ::core::option::Option<u8>)) -> u16 {
        {
            let t1__scrut: ((::core::option::Option<u8>, ::core::option::Option<u8>), (::core::option::Option<u8>, ::core::option::Option<u8>)) = (l0_p, l1_q);
            match t1__scrut {
                ((::core::option::Option::Some(l2_x), _), (::core::option::Option::Some(l3_y), _)) => if ((l2_x as u16) + (l3_y as u16)) > 10u16 { (((l2_x as u16) * 256u16) + (l3_y as u16)) } else {
                    match t1__scrut {
                        ((::core::option::Option::Some(l2_x), _), (_, ::core::option::Option::Some(l3_y))) => if ((l2_x as u16) + (l3_y as u16)) > 10u16 { (((l2_x as u16) * 256u16) + (l3_y as u16)) } else {
                            match t1__scrut {
                                ((_, ::core::option::Option::Some(l2_x)), (::core::option::Option::Some(l3_y), _)) => if ((l2_x as u16) + (l3_y as u16)) > 10u16 { (((l2_x as u16) * 256u16) + (l3_y as u16)) } else {
                                    match t1__scrut {
                                        ((_, ::core::option::Option::Some(l2_x)), (_, ::core::option::Option::Some(l3_y))) => if ((l2_x as u16) + (l3_y as u16)) > 10u16 { (((l2_x as u16) * 256u16) + (l3_y as u16)) } else {
                                            match t1__scrut {
                                                _ => 0u16,
                                            }
                                        },
                                        _ => 0u16,
                                    }
                                },
                                ((_, ::core::option::Option::Some(l2_x)), (_, ::core::option::Option::Some(l3_y))) => if ((l2_x as u16) + (l3_y as u16)) > 10u16 { (((l2_x as u16) * 256u16) + (l3_y as u16)) } else {
                                    match t1__scrut {
                                        _ => 0u16,
                                    }
                                },
                                _ => 0u16,
                            }
                        },
                        ((_, ::core::option::Option::Some(l2_x)), (::core::option::Option::Some(l3_y), _)) => if ((l2_x as u16) + (l3_y as u16)) > 10u16 { (((l2_x as u16) * 256u16) + (l3_y as u16)) } else {
                            match t1__scrut {
                                ((_, ::core::option::Option::Some(l2_x)), (_, ::core::option::Option::Some(l3_y))) => if ((l2_x as u16) + (l3_y as u16)) > 10u16 { (((l2_x as u16) * 256u16) + (l3_y as u16)) } else {
                                    match t1__scrut {
                                        _ => 0u16,
                                    }
                                },
                                _ => 0u16,
                            }
                        },
                        ((_, ::core::option::Option::Some(l2_x)), (_, ::core::option::Option::Some(l3_y))) => if ((l2_x as u16) + (l3_y as u16)) > 10u16 { (((l2_x as u16) * 256u16) + (l3_y as u16)) } else {
                            match t1__scrut {
                                _ => 0u16,
                            }
                        },
                        _ => 0u16,
                    }
                },
                ((::core::option::Option::Some(l2_x), _), (_, ::core::option::Option::Some(l3_y))) => if ((l2_x as u16) + (l3_y as u16)) > 10u16 { (((l2_x as u16) * 256u16) + (l3_y as u16)) } else {
                    match t1__scrut {
                        ((_, ::core::option::Option::Some(l2_x)), (::core::option::Option::Some(l3_y), _)) => if ((l2_x as u16) + (l3_y as u16)) > 10u16 { (((l2_x as u16) * 256u16) + (l3_y as u16)) } else {
                            match t1__scrut {
                                ((_, ::core::option::Option::Some(l2_x)), (_, ::core::option::Option::Some(l3_y))) => if ((l2_x as u16) + (l3_y as u16)) > 10u16 { (((l2_x as u16) * 256u16) + (l3_y as u16)) } else {
                                    match t1__scrut {
                                        _ => 0u16,
                                    }
                                },
                                _ => 0u16,
                            }
                        },
                        ((_, ::core::option::Option::Some(l2_x)), (_, ::core::option::Option::Some(l3_y))) => if ((l2_x as u16) + (l3_y as u16)) > 10u16 { (((l2_x as u16) * 256u16) + (l3_y as u16)) } else {
                            match t1__scrut {
                                _ => 0u16,
                            }
                        },
                        _ => 0u16,
                    }
                },
                ((_, ::core::option::Option::Some(l2_x)), (::core::option::Option::Some(l3_y), _)) => if ((l2_x as u16) + (l3_y as u16)) > 10u16 { (((l2_x as u16) * 256u16) + (l3_y as u16)) } else {
                    match t1__scrut {
                        ((_, ::core::option::Option::Some(l2_x)), (_, ::core::option::Option::Some(l3_y))) => if ((l2_x as u16) + (l3_y as u16)) > 10u16 { (((l2_x as u16) * 256u16) + (l3_y as u16)) } else {
                            match t1__scrut {
                                _ => 0u16,
                            }
                        },
                        _ => 0u16,
                    }
                },
                ((_, ::core::option::Option::Some(l2_x)), (_, ::core::option::Option::Some(l3_y))) => if ((l2_x as u16) + (l3_y as u16)) > 10u16 { (((l2_x as u16) * 256u16) + (l3_y as u16)) } else {
                    match t1__scrut {
                        _ => 0u16,
                    }
                },
                _ => 0u16,
            }
        }
    }
    pub fn let_or(l0_p: (u8, u8)) -> u8 {
        let l1_a: u8 = match l0_p {
            (l1_a, 0u8) => l1_a,
            (0u8, l1_a) => l1_a,
            _ => {
                return 255u8;
            }
        };
        l1_a
    }
    pub fn if_let_chain(l0_o: ::core::option::Option<u8>, l1_s: &[u8]) -> u8 {
        match l0_o {
            ::core::option::Option::Some(l2_v) => {
                l2_v
            },
            _ => (match l1_s {
                &[ref l3_h, ..] => {
                    (*l3_h)
                },
                _ => {
                    0u8
                },
            }),
        }
    }
    pub fn try_chain(l0_s: &[u8]) -> ::core::option::Option<u16> {
        let (l1_a, l2_rest): (&u8, &[u8]) = match <[u8]>::split_first(l0_s) { ::core::option::Option::Some(t1__v) => t1__v, ::core::option::Option::None => return ::core::option::Option::<u16>::None };
        let (l3_b, _): (&u8, &[u8]) = match <[u8]>::split_first(l2_rest) { ::core::option::Option::Some(t2__v) => t2__v, ::core::option::Option::None => return ::core::option::Option::<u16>::None };
        ::core::option::Option::<u16>::Some((((*l1_a) as u16) << 8u32) | ((*l3_b) as u16))
    }
    pub fn slices(l0_s: &[u8]) -> u32 {
        match l0_s {
            &[] => 0u32,
            &[ref l1_a] => ((*l1_a) as u32),
            &[ref l2_a, ref l3_b] => (((*l2_a) as u32) + (((*l3_b) as u32) * 2u32)),
            &[ref l4_first, .., ref l5_last] => ((((*l4_first) as u32) * 1000u32) + ((*l5_last) as u32)),
        }
    }
    pub fn tail_sum(mut a0__arg: &[u8], mut a1__arg: u32) -> u32 {
        loop {
            let l0_s: &[u8] = a0__arg;
            let l1_acc: u32 = a1__arg;
            {
                match l0_s {
                    &[] => { return l1_acc; },
                    &[ref l2_h, ref l3_t @ ..] => { let t1__next = l3_t; let t2__next = <u32>::wrapping_add(l1_acc, (*l2_h) as u32); a0__arg = t1__next; a1__arg = t2__next; continue; },
                }
            }
        }
    }
    #[doc = " Generic over the element type, so not a boundary function: host code"]
    #[doc = " could instantiate it with a zero-sized type (DESIGN.md §3.1). The"]
    #[doc = " boundary exports monomorphic instances."]
    fn count<T: ::core::marker::Copy>(mut a0__arg: &[T], mut a1__arg: usize) -> usize {
        loop {
            let l0_s: &[T] = a0__arg;
            let l1_n: usize = a1__arg;
            {
                match l0_s {
                    &[] => { return l1_n; },
                    &[_, ref l2_t @ ..] => { let t1__next = l2_t; let t2__next = l1_n + 1usize; a0__arg = t1__next; a1__arg = t2__next; continue; },
                }
            }
        }
    }
    pub fn count_u64(l0_s: &[u64], l1_n: usize) -> usize {
        crate::__sandblaster::count::<u64>(l0_s, l1_n)
    }
    pub fn count_u8(l0_s: &[u8], l1_n: usize) -> usize {
        crate::__sandblaster::count::<u8>(l0_s, l1_n)
    }
    pub fn gcd(mut a0__arg: u64, mut a1__arg: u64) -> u64 {
        loop {
            let l0_a: u64 = a0__arg;
            let l1_b: u64 = a1__arg;
            {
                if l1_b == 0u64 {
                    { return l0_a; }
                } else {
                    { let t1__next = l1_b; let t2__next = l0_a % l1_b; a0__arg = t1__next; a1__arg = t2__next; continue; }
                }
            }
        }
    }
    pub fn init_last(l0_s: &[u8]) -> u8 {
        match l0_s {
            &[ref l1_init @ .., ref l2_last] => ((*l2_last) ^ (<[u8]>::len(l1_init) as u8)),
            &[] => 0u8,
        }
    }
    pub fn arrays(l0_a: [u8; 4usize]) -> u8 {
        let [l1_x, l2_y, l3_rest @ ..]: [u8; 4usize] = l0_a;
        (((l1_x ^ l2_y) ^ l3_rest[0usize]) ^ l3_rest[1usize])
    }
    pub fn ranges(l0_x: u64) -> u8 {
        match l0_x {
            0u64 => 0u8,
            1u64..=9u64 => 1u8,
            10u64..=99u64 => 2u8,
            _ => 3u8,
        }
    }
    #[doc = " `for i in k..n` runs zero times when `k > n`; `..=MAX` does not overflow."]
    pub fn range_loops(l0_k: u32, l1_n: u32) -> u32 {
        let mut l2_c: u32 = 0u32;
        for l3__i in l0_k..l1_n {
            l2_c += 1u32;
        };
        for l4_j in 250u8..=u8::MAX {
            l2_c += l4_j as u32;
        };
        l2_c
    }
    pub fn guards_fallthrough(l0_x: u8) -> u8 {
        match l0_x {
            l1_v => if (l1_v % 2u8) == 0u8 { 1u8 } else {
                match l0_x {
                    3u8 => if l0_x > 3u8 { 2u8 } else {
                        match l0_x {
                            5u8 => if l0_x > 3u8 { 2u8 } else {
                                match l0_x {
                                    l2_v => l2_v,
                                }
                            },
                            l2_v => l2_v,
                        }
                    },
                    5u8 => if l0_x > 3u8 { 2u8 } else {
                        match l0_x {
                            l2_v => l2_v,
                        }
                    },
                    l2_v => l2_v,
                }
            },
            3u8 => if l0_x > 3u8 { 2u8 } else {
                match l0_x {
                    5u8 => if l0_x > 3u8 { 2u8 } else {
                        match l0_x {
                            l2_v => l2_v,
                        }
                    },
                    l2_v => l2_v,
                }
            },
            5u8 => if l0_x > 3u8 { 2u8 } else {
                match l0_x {
                    l2_v => l2_v,
                }
            },
            l2_v => l2_v,
        }
    }
    pub fn bool_ops(l0_a: bool, l1_b: bool, l2_x: u8) -> u8 {
        let l3_c: bool = l0_a && ((l2_x > 3u8) || (!l1_b));
        let l4_d: bool = l0_a ^ (l1_b & (!l3_c));
        (((l3_c as u8) + ((l4_d as u8) << 1u32)) + ((l0_a | l1_b) as u8))
    }
    pub fn nested_loops(l0_n: u8) -> u32 {
        let mut l1_total: u32 = 0u32;
        let mut l2_grid: [[u8; 3usize]; 3usize] = [[0u8; 3usize]; 3usize];
        for l3_i in 0usize..3usize {
            for l4_j in 0usize..3usize {
                l2_grid[l3_i][l4_j] = (((l3_i as u8) * 3u8) + (l4_j as u8)) + l0_n;
                l1_total += l2_grid[l3_i][l4_j] as u32;
            }
        };
        (l1_total + (l2_grid[2usize][1usize] as u32))
    }
}
pub use __sandblaster::arrays as arrays;
pub use __sandblaster::bool_ops as bool_ops;
pub use __sandblaster::count_u64 as count_u64;
pub use __sandblaster::count_u8 as count_u8;
pub use __sandblaster::gcd as gcd;
pub use __sandblaster::guards_fallthrough as guards_fallthrough;
pub use __sandblaster::if_let_chain as if_let_chain;
pub use __sandblaster::init_last as init_last;
pub use __sandblaster::let_or as let_or;
pub use __sandblaster::nested_loops as nested_loops;
pub use __sandblaster::nested_or as nested_or;
pub use __sandblaster::order as order;
pub use __sandblaster::range_loops as range_loops;
pub use __sandblaster::ranges as ranges;
pub use __sandblaster::slices as slices;
pub use __sandblaster::tail_sum as tail_sum;
pub use __sandblaster::try_chain as try_chain;
