// @generated by sandblaster from `samples/simd/mod.rs`. Do not edit.
// STATUS: UNVERIFIED (phase 1): proofs, obligations and the optimizer have NOT run.
// This code was only type checked and validated against the sandblaster subset.
#[cfg(not(target_pointer_width = "64"))]
compile_error!("sandblaster requires a 64-bit target");
#[deny(unsafe_code, overflowing_literals, unconditional_recursion)]
#[allow(arithmetic_overflow, unconditional_panic, dead_code, unused_variables, unused_mut, unused_assignments, unused_parens, unused_braces, unused_unsafe, unreachable_patterns, unreachable_code, irrefutable_let_patterns, non_snake_case, non_camel_case_types, non_upper_case_globals, clippy::all)]
mod __sandblaster {
    #[doc = " Portable lane-wise wrapping addition."]
    pub fn add4_portable(l0_a: [u32; 4usize], l1_b: [u32; 4usize]) -> [u32; 4usize] {
        let mut l2_out: [u32; 4usize] = [0u32; 4usize];
        for l3_i in 0usize..4usize {
            l2_out[l3_i] = <u32>::wrapping_add(l0_a[l3_i], l1_b[l3_i]);
        };
        l2_out
    }
    #[doc = " NEON / SHA2 variants."]
    #[cfg(target_arch = "aarch64")]
    pub(crate) mod hw {
        #[target_feature(enable = "neon")]
        pub fn add4(l0_a: [u32; 4usize], l1_b: [u32; 4usize]) -> [u32; 4usize] {
            crate::__sandblaster::__arch::store_u32x4(::core::arch::aarch64::vaddq_u32(crate::__sandblaster::__arch::load_u32x4(&l0_a), crate::__sandblaster::__arch::load_u32x4(&l1_b)))
        }
        #[target_feature(enable = "sha2")]
        pub fn mix(l0_block: &[u8; 16usize], l1_w: [u32; 4usize]) -> ([u8; 16usize], u32, [u32; 4usize]) {
            let l2_v: ::core::arch::aarch64::uint8x16_t = ::core::arch::aarch64::vrev32q_u8(crate::__sandblaster::__arch::load_u8x16(l0_block));
            let l3_x: ::core::arch::aarch64::uint32x4_t = ::core::arch::aarch64::vreinterpretq_u32_u8(l2_v);
            let l4_s: ::core::arch::aarch64::uint32x4_t = ::core::arch::aarch64::vsha256su0q_u32(l3_x, crate::__sandblaster::__arch::load_u32x4(&l1_w));
            let l5_t: ::core::arch::aarch64::uint32x4_t = ::core::arch::aarch64::vextq_u32::<1>(l4_s, ::core::arch::aarch64::vshlq_n_u32::<3>(l3_x));
            let l6_lane: u32 = ::core::arch::aarch64::vgetq_lane_u32::<2>(l5_t);
            (crate::__sandblaster::__arch::store_u8x16(l2_v), l6_lane, crate::__sandblaster::__arch::store_u32x4(::core::arch::aarch64::vsetq_lane_u32::<0>(7u32, l5_t)))
        }
    }
    #[cfg(target_arch = "aarch64")]
    pub(crate) mod __arch {
        // Trusted glue (DESIGN.md §9.2): safe unaligned load/store helpers.
        #[target_feature(enable = "neon")]
        #[inline]
        #[allow(unsafe_code)]
        pub(crate) fn load_u8x16(a: &[u8; 16usize]) -> ::core::arch::aarch64::uint8x16_t { unsafe { ::core::arch::aarch64::vld1q_u8(a.as_ptr()) } }
        #[target_feature(enable = "neon")]
        #[inline]
        #[allow(unsafe_code)]
        pub(crate) fn load_u32x4(a: &[u32; 4usize]) -> ::core::arch::aarch64::uint32x4_t { unsafe { ::core::arch::aarch64::vld1q_u32(a.as_ptr()) } }
        #[target_feature(enable = "neon")]
        #[inline]
        #[allow(unsafe_code)]
        pub(crate) fn store_u8x16(a: ::core::arch::aarch64::uint8x16_t) -> [u8; 16usize] { let mut out = [0u8; 16]; unsafe { ::core::arch::aarch64::vst1q_u8(out.as_mut_ptr(), a) }; out }
        #[target_feature(enable = "neon")]
        #[inline]
        #[allow(unsafe_code)]
        pub(crate) fn store_u32x4(a: ::core::arch::aarch64::uint32x4_t) -> [u32; 4usize] { let mut out = [0u32; 4]; unsafe { ::core::arch::aarch64::vst1q_u32(out.as_mut_ptr(), a) }; out }
    }
}
pub use __sandblaster::hw::add4 as add4;
pub use __sandblaster::add4_portable as add4_portable;
pub use __sandblaster::hw::mix as mix;
