//! The theorem gate's trusted check (`docs/checked-structuring.md`,
//! amendment (e); DESIGN.md §1.1 item 8; AUDIT.md §21.1). **TRUSTED**: this
//! module alone decides whether a lifted exec function whose body was read
//! from rustc's MIR has its theorem.
//!
//! # What it checks
//!
//! For every function the lift lists (`LiftFacts::mir_contracts`: each
//! lifted exec function read from MIR, with its declared contract):
//!
//! 0. **The MIR instance is the function itself.** The lift finds a
//!    function's instance by its lifted name alone (`Decoder__u32::feed`),
//!    which a function of another extracted module may share; the instance
//!    must be the listed function: its lifted name in the DSL module of its
//!    item (`ModuleNames::instance_global`). Else the theorem would be about
//!    another function's MIR.
//! 1. **L was generated by `literal.rs` from this MIR and accepted by the
//!    kernel.** The literal reading enters the kernel environment only
//!    through [`Ledger::load`], which runs the generator and `load_core` and
//!    records the range of globals and inductives it loaded and the MIR text
//!    of every instance it read. The check confirms that the instance and
//!    every instance its reading runs were read from the MIR it is given
//!    (an instance read from another extraction is refused).
//! 2. **The kernel holds `L::thm::<id>` with exactly the trusted statement.**
//!    The statement is generated afresh by [`stmt::statement`] (from L's
//!    `run`, `init` and `erase`, the declared contract and `S_f`) and parsed;
//!    the declaration's type must be α-equal to it, ignoring binder names
//!    and proofs (`Env::alpha_eq_relevant`, which compares every relevant
//!    position, preconditions' types included). A declaration in the
//!    environment was checked by the kernel when it was added.
//! 3. **What the statement means rests only on trusted definitions**: every
//!    global it reaches (the kernel's `refs_closure`) was defined before the
//!    first literal reading was loaded (the elaboration), by the load of L's
//!    library, or by a load of this extraction's reading, and no inductive
//!    was added since but by a load. So a declaration made by untrusted code
//!    (a walker's lemma, a replayed cache entry) can never stand in for
//!    `S_f`, L or the prelude, under any name; nor can another extraction's
//!    reading (L's names restart with each extraction's reading, and the
//!    kernel lets a later definition take over a name).
//! 4. **L and `S_f` name the same fields.** Kernel field names are
//!    positional: L reads field `i` of a module type as the MIR numbers it,
//!    `S_f` as the subset's declaration does. So every module type the
//!    function's MIR instances reach must be declared in the lifted crate
//!    (the HIR the elaborator declared it from) with the MIR's variants
//!    (names, order, discriminants `0, 1, ..`: the subset has no explicit
//!    ones) and fields (names, order).
//!
//! `S_f`'s preconditions are its declared contract's by the elaborator's
//! check (`elab::items`: each α-equal to the elaboration of the declared
//! clause, which the lift carries apart, `hir::FnDef::declared`).
//!
//! # What it trusts
//!
//! The kernel; the generator `literal.rs` and `literal.core`; the statement
//! `stmt.rs`; the parse `ir.rs`/`sexp.rs`; the names of `mod.rs`; the lift's
//! list of the functions read from MIR (which instance each is, check 0
//! checks); and the elaborator, with its check of preconditions.
//!
//! # What it does not trust
//!
//! Everything that produces the declarations it checks: the walker
//! (`simproof.rs`) and its driver (`checked.rs`: planning, dependency order,
//! loop and model lemmas, the theorems' construction), the verdict cache
//! (an entry is a list of declarations replayed through `add_def`, so the
//! kernel re-checks it and this module checks its statement like any other),
//! and the reports and diagnostics. A bug there leaves a theorem missing or
//! refused, never accepted with another meaning.

use std::collections::BTreeMap;
use std::time::Instant;

use sandblaster_kernel::api::Env;
use sandblaster_kernel::term::{GlobalId, IndId};
use sandblaster_kernel::value::Budget;

use super::ir::{AdtDef, Callee, Sbmir, Term, Ty};
use super::literal::{self, Gen, GenState, KNames};
use super::{stmt, ModuleNames};
use crate::hir::{Crate, FieldDef, ItemKind};
use crate::lift::{LiftFacts, MirContract};

/// The literal readings loaded into one kernel environment, and what the
/// environment held before the first of them.
#[derive(Default)]
pub struct Ledger {
    /// Globals and inductives before the first load (the elaboration).
    start: Option<(u32, u32)>,
    /// Each load's MIR module (`""`: the library), its globals `[g0, g1)` and
    /// inductives `[i0, i1)`.
    loads: Vec<(String, [u32; 4])>,
    /// Per MIR module: the generator's state and the MIR text of each
    /// instance it read.
    readings: BTreeMap<String, (GenState, BTreeMap<String, String>)>,
}

/// What one load generated.
pub struct Loaded {
    pub refused: Vec<(String, String)>,
    pub items: usize,
    pub lines: usize,
    pub bytes: usize,
    pub secs: f64,
}

/// The gate's verdict on one listed function.
pub struct Verdict {
    pub global: String,
    pub key: String,
    pub result: Result<(), String>,
}

impl Ledger {
    /// The generator's state of `module`'s reading.
    pub fn state(&self, module: &str) -> Option<&GenState> {
        self.readings.get(module).map(|r| &r.0)
    }

    /// Generates the literal reading of `keys` (and of what they run) from
    /// `m`, continuing `m.module`'s reading, and loads it with its library.
    pub fn load(&mut self, env: &mut Env, m: &Sbmir, names: &ModuleNames, keys: &[String], dump: Option<&std::path::Path>) -> Result<Loaded, String> {
        let t0 = Instant::now();
        self.start.get_or_insert((env.num_globals(), num_inds(env)));
        if env.lookup_global("mir::bind").is_none() {
            let (g0, i0) = (env.num_globals(), num_inds(env));
            env.load_core(&literal::library(), &mut Budget { steps: 4_000_000_000 }).map_err(|e| format!("the literal reading's library: {e}"))?;
            self.loads.push((String::new(), [g0, env.num_globals(), i0, num_inds(env)]));
        }
        let (g0, i0) = (env.num_globals(), num_inds(env));
        let (prev, mut read) = self.readings.remove(&m.module).unwrap_or_default();
        let (text, state, refused) = {
            let k = KNames { names, env };
            let mut g = Gen::resume(m, &k, prev);
            let refused: Vec<(String, String)> = keys.iter().filter_map(|key| g.function(key).err().map(|e| (key.clone(), e))).collect();
            (g.out.clone(), g.state(), refused)
        };
        if let Some(d) = dump {
            let _ = std::fs::write(d, &text);
        }
        let n = env.load_core(&text, &mut Budget { steps: 40_000_000_000 }).map_err(|e| format!("the kernel rejected the literal reading: {}", e.to_string().chars().take(4000).collect::<String>()))?;
        self.loads.push((m.module.clone(), [g0, env.num_globals(), i0, num_inds(env)]));
        for k in state.fns.keys() {
            read.entry(k.clone()).or_insert_with(|| format!("{:?}", m.fns.get(k)));
        }
        self.readings.insert(m.module.clone(), (state, read));
        Ok(Loaded { refused, items: n.len(), lines: text.lines().count(), bytes: text.len(), secs: t0.elapsed().as_secs_f64() })
    }

    /// The verdict on every function the lift read from MIR.
    pub fn verdicts(&self, env: &Env, krate: &Crate, facts: &LiftFacts) -> Vec<Verdict> {
        let inds = self.inductives_trusted(env);
        let accept = |c: &MirContract| {
            inds.clone()?;
            let mm = facts.mir_loaded.iter().find(|mm| mm.loaded.m.fns.contains_key(&c.key)).ok_or("its MIR instance is in no loaded extraction")?;
            let is = mm.loaded.names.instance_global(&mm.loaded.m, &mm.loaded.m.fns[&c.key]);
            if is.as_deref() != Some(c.global.as_str()) {
                return Err(format!("its MIR instance `{}` is {}, not this function", c.key, is.map_or("no lifted function".into(), |g| format!("`{g}`"))));
            }
            self.accept(env, krate, &mm.loaded.m, &mm.loaded.names, c, &c.key, "L::thm::", &c.global)
        };
        facts.mir_contracts.iter().map(|c| Verdict { global: c.global.clone(), key: c.key.clone(), result: accept(c) }).collect()
    }

    /// `<prefix><id>`, `id` the literal reading of `m`'s instance `key`, is
    /// a kernel declaration of the statement of `subject` (`c.global`) under
    /// `c`.
    #[allow(clippy::too_many_arguments)]
    fn accept(&self, env: &Env, krate: &Crate, m: &Sbmir, names: &ModuleNames, _c: &MirContract, key: &str, prefix: &str, subject: &str) -> Result<(), String> {
        let (state, read) = self.readings.get(&m.module).ok_or("the literal reading of its module was not loaded")?;
        let lf = state.fns.get(key).ok_or_else(|| format!("no literal reading of `{key}`"))?;
        let f = m.fns.get(key).ok_or_else(|| format!("no MIR of `{key}`"))?;
        let mut adts = std::collections::BTreeSet::new();
        for k in closure(m, key) {
            if read.get(&k).is_some_and(|t| *t != format!("{:?}", m.fns.get(&k))) {
                return Err(format!("the literal reading of `{k}` was generated from another MIR than this extraction's"));
            }
            m.fns.get(&k).into_iter().flat_map(|g| &g.locals).for_each(|(t, _)| adts_in(m, t, &mut adts));
        }
        for (d, name) in adts.iter().filter_map(|k| m.adts.get(k)).filter(|d| names.local(&d.path)).filter_map(|d| Some((d, names.kernel_adt(m, &d.key)?))) {
            same_declaration(krate, d, &name)?;
        }
        let kn = KNames { names, env };
        let mut g = Gen::resume(m, &kn, state.clone());
        let st = stmt::statement(env, &mut g, lf, f, subject)?;
        let want = env.parse_term(&[], &st.theorem_ty()).map_err(|e| format!("its statement: {e}"))?;
        let name = format!("{prefix}{}", lf.id);
        let got = env.lookup_global(&name).and_then(|g| env.global_type(g)).ok_or_else(|| format!("the kernel holds no `{name}`"))?;
        if !env.alpha_eq_relevant(&got, &want, &|a: GlobalId, b: GlobalId| a == b) {
            return Err(format!("the kernel's `{name}` states something else than the statement of `{subject}` against `{key}`"));
        }
        let stop: Vec<GlobalId> = (0..env.num_globals()).map(GlobalId).filter(|g| !self.loaded(g.0)).collect();
        if let Some(g) = env.refs_closure(&want, &stop).into_iter().find(|g| !self.trusted(g.0, &m.module)) {
            return Err(format!("its statement reaches `{}`, which neither the elaboration nor this extraction's literal reading defined", env.global_name(g).unwrap_or_default()));
        }
        Ok(())
    }

    /// Defined by a load of this ledger.
    fn loaded(&self, g: u32) -> bool {
        self.loads.iter().any(|(_, l)| l[0] <= g && g < l[1])
    }

    /// Defined before the first load, or by the load of the library or of
    /// `module`'s reading (L's names restart with each extraction's reading,
    /// and a later definition takes over a name).
    fn trusted(&self, g: u32, module: &str) -> bool {
        self.start.is_some_and(|s| g < s.0) || self.loads.iter().any(|(mm, l)| (mm.is_empty() || mm == module) && l[0] <= g && g < l[1])
    }

    /// No inductive was added since the first load but by a load.
    fn inductives_trusted(&self, env: &Env) -> Result<(), String> {
        let i0 = self.start.ok_or("no literal reading was loaded")?.1;
        match (i0..num_inds(env)).find(|i| !self.loads.iter().any(|(_, l)| l[2] <= *i && *i < l[3])) {
            Some(i) => Err(format!("the inductive `{}` was added outside the literal reading", env.inductive_decl(IndId(i)).map(|d| d.name.to_string()).unwrap_or_default())),
            None => Ok(()),
        }
    }
}

/// The ADTs `t` reaches (through arguments, fields, references, closures).
fn adts_in(m: &Sbmir, t: &Ty, out: &mut std::collections::BTreeSet<String>) {
    let inner: Vec<&Ty> = match t {
        Ty::Tuple(ts) | Ty::FnDef(_, ts) => ts.iter().collect(),
        Ty::Array(x, _) | Ty::Slice(x) | Ty::Ref(_, x) | Ty::Closure(_, x) => vec![x],
        Ty::Adt(k) if out.insert(k.clone()) => m.adts.get(k).into_iter().flat_map(|d| d.args.iter().chain(d.variants.iter().flat_map(|v| v.fields.iter().map(|f| &f.1)))).collect(),
        _ => vec![],
    };
    inner.into_iter().for_each(|x| adts_in(m, x, out));
}

/// The module type `d` as the MIR declares it and as the subset declares
/// it under `name`: the same variants and fields, by name and in order, and
/// variant `i` with discriminant `i`. (A struct's one variant is unnamed.)
fn same_declaration(krate: &Crate, d: &AdtDef, name: &str) -> Result<(), String> {
    let show = |v: &str, i: i128, fs: Vec<String>| format!("{v}={i}({})", fs.join(", "));
    let fields = |fs: &[FieldDef]| fs.iter().enumerate().map(|(i, f)| f.name.clone().unwrap_or_else(|| i.to_string())).collect();
    let mir: Vec<String> = d.variants.iter().map(|v| show(if d.is_enum { &v.name } else { "" }, v.discr, v.fields.iter().map(|f| f.0.clone()).collect())).collect();
    let path: Vec<&str> = name.strip_prefix("crate::").unwrap_or(name).split("::").collect();
    let subset: Vec<String> = match krate.items.iter().find(|it| it.path.0 == path).map(|it| &it.kind) {
        Some(ItemKind::Struct(s)) if !d.is_enum => vec![show("", 0, fields(&s.fields))],
        Some(ItemKind::Enum(e)) if d.is_enum => e.variants.iter().enumerate().map(|(i, v)| show(&v.name, i as i128, fields(&v.fields))).collect(),
        _ => vec!["no such type".into()],
    };
    if mir != subset {
        return Err(format!("the MIR declares `{}` as {{{}}} and the subset `{name}` as {{{}}}: kernel fields are positional, so L and the structured reading would name different fields", d.path, mir.join(" | "), subset.join(" | ")));
    }
    Ok(())
}

/// The number of inductives in `env`.
fn num_inds(env: &Env) -> u32 {
    (0u32..).find(|i| env.inductive_decl(IndId(*i)).is_none()).unwrap_or(0)
}

/// The MIR instances a function's literal reading runs: itself and what it
/// calls, transitively.
pub(crate) fn closure(m: &Sbmir, key: &str) -> Vec<String> {
    let mut seen = std::collections::BTreeSet::new();
    let mut work = vec![key.to_string()];
    while let Some(k) = work.pop() {
        if seen.insert(k.clone())
            && let Some(f) = m.fns.get(&k)
        {
            for b in &f.blocks {
                if let Term::Call(Callee::Fn(k2), ..) = &b.term {
                    work.push(k2.clone());
                }
            }
        }
    }
    seen.into_iter().collect()
}
