//! The kernel core-text transcriptions of the target models and their
//! registry (DESIGN.md §9.2 "core-text transcription", §5.12 core syntax).
//!
//! `core/aarch64.core` and `core/x86_64.core` transcribe every executable
//! model of [`crate::aarch64`] / [`crate::x86_64`] into kernel core text as a
//! `def[intrinsic]` global over the prelude's `Array` types, lane-level,
//! following `MODELS.md`. They load with `Env::load_core` after
//! `Env::with_prelude()` (see `crate::kernel`, feature `kernel`). This
//! module needs no kernel: it embeds the text ([`core_text`]), describes each
//! global's signature for the front end / elaborator ([`CoreModel`],
//! [`CoreHelper`]), and hashes the text of each model's core items for the
//! evidence records ([`core_hash`], [`core_items`]).
//!
//! **Signature convention** (normative; `MODELS.md` "Core text"):
//!
//! * vectors are `Array <lane> <N>usize` (NEON `uint32x4_t` = `Array U32
//!   4usize`, `uint8x16_t` = `Array U8 16usize`, `uint8x8_t` = `Array U8
//!   8usize`; x86 `__m128i` = `Array U8 16usize` little-endian);
//! * immediates (stdarch `const N: i32`) come **first**, as relevant `U32`
//!   parameters, each followed by its irrelevant range proofs — `(.hN0 :
//!   Eq(Bool, #le_u32(lo, N), true))` only if `lo > 0`, then `(.hN :
//!   Eq(Bool, #le_u32(N, hi), true))`. The caller passes `.refl(Bool, true)`
//!   for a literal in range ([`CoreModel::apply_text`] does); an out-of-range
//!   immediate is ill-typed;
//! * then the value parameters in stdarch order; `&[T; N]` arguments of the
//!   pointer-free loads are arrays (`&T` is `T` in the core, §3.5);
//! * signed stdarch scalars (`_mm_set_epi32`, `_mm_set_epi64x`) are passed as
//!   their two's-complement bits (`U32` / `U64`).
#![forbid(unsafe_code)]

use crate::fips;
use crate::registry::{self, Arch, Model};

/// `core/aarch64.core`: the aarch64 NEON + SHA2 core models.
pub const AARCH64_CORE: &str = include_str!("../core/aarch64.core");

/// `core/x86_64.core`: the x86_64 SSE + SHA-NI core models (hand-written).
pub const X86_64_CORE_SSE: &str = include_str!("../core/x86_64.core");

/// `core/x86_64_avx.core`: the x86_64 256/512-bit core models (AVX-512F/BW/
/// VL/DQ, IFMA, GFNI, VBMI/VBMI2, VPOPCNTDQ/BITALG, AVX2), generated by
/// `gen/x86_64_avx.py`. It reuses helpers of `core/x86_64.core`.
pub const X86_64_CORE_AVX: &str = include_str!("../core/x86_64_avx.core");

/// The x86_64 core text: `core/x86_64.core` followed by
/// `core/x86_64_avx.core`, loaded as one text. (Appending items leaves every
/// earlier model's [`core_hash`] unchanged: an item's hashed text is its own
/// comment-free text, and only comments separate the two files.)
pub const X86_64_CORE: &str = concat!(include_str!("../core/x86_64.core"), include_str!("../core/x86_64_avx.core"));

/// The core text of an architecture's models (load after the prelude).
pub fn core_text(arch: Arch) -> &'static str {
    match arch {
        Arch::Aarch64 => AARCH64_CORE,
        Arch::X86_64 => X86_64_CORE,
    }
}

/// Path of an architecture's (first) core file relative to the crate root.
pub fn core_path(arch: Arch) -> &'static str {
    match arch {
        Arch::Aarch64 => "core/aarch64.core",
        Arch::X86_64 => "core/x86_64.core",
    }
}

/// The core files of an architecture, in load order, with their texts
/// ([`core_text`] is their concatenation).
pub fn core_files(arch: Arch) -> &'static [(&'static str, &'static str)] {
    match arch {
        Arch::Aarch64 => &[("core/aarch64.core", AARCH64_CORE)],
        Arch::X86_64 => &[("core/x86_64.core", X86_64_CORE_SSE), ("core/x86_64_avx.core", X86_64_CORE_AVX)],
    }
}

/// The core file defining item `name` of `arch`.
pub fn core_file_of(arch: Arch, name: &str) -> Option<&'static str> {
    core_files(arch).iter().find(|(_, text)| item_names(text).contains(&name)).map(|(path, _)| *path)
}

/// The global-name prefix of an architecture's core items (`aarch64::`).
pub fn global_prefix(arch: Arch) -> &'static str {
    match arch {
        Arch::Aarch64 => "aarch64::",
        Arch::X86_64 => "x86_64::",
    }
}

/// Untrusted core-text test fixtures for the compression cross-checks
/// (`core/checks/`): a plain FIPS 180-4 compression and the two hardware
/// compressions assembled from the core models.
pub mod checks {
    /// `core/checks/fips180_4.core`: `checks::fips::compress` (needs only the prelude).
    pub const FIPS180_4: &str = include_str!("../core/checks/fips180_4.core");
    /// `core/checks/aarch64_sha2_compress.core`: `checks::aarch64::compress_sha2`
    /// (needs `core/aarch64.core`).
    pub const AARCH64_SHA2_COMPRESS: &str = include_str!("../core/checks/aarch64_sha2_compress.core");
    /// `core/checks/x86_64_shani_compress.core`: `checks::x86_64::compress_shani`
    /// (needs `core/x86_64.core`).
    pub const X86_64_SHANI_COMPRESS: &str = include_str!("../core/checks/x86_64_shani_compress.core");

    use crate::registry::Arch;

    /// Names of the kernel compression cross-checks (`kernel::compress_checks`).
    pub const COMPRESS_CHECKS: [&str; 5] = [
        "core_fips_vs_executable_fips",
        "core_compress_sha2_vs_core_fips",
        "core_compress_sha2_vs_executable_model",
        "core_compress_shani_vs_core_fips",
        "core_compress_shani_vs_executable_model",
    ];

    /// The architecture a compression check concerns (`None`: both).
    pub fn compress_check_arch(name: &str) -> Option<Arch> {
        if name.contains("sha2") {
            Some(Arch::Aarch64)
        } else if name.contains("shani") {
            Some(Arch::X86_64)
        } else {
            None
        }
    }
}

// ---------------------------------------------------------------------------
// Signatures

/// A lane (machine word) type of the kernel.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Lane {
    /// `U8`.
    U8,
    /// `U16`.
    U16,
    /// `U32`.
    U32,
    /// `U64`.
    U64,
}

impl Lane {
    /// The core type name (`U32`).
    pub fn core_name(self) -> &'static str {
        match self {
            Lane::U8 => "U8",
            Lane::U16 => "U16",
            Lane::U32 => "U32",
            Lane::U64 => "U64",
        }
    }

    /// The literal suffix (`u32`).
    pub fn suffix(self) -> &'static str {
        match self {
            Lane::U8 => "u8",
            Lane::U16 => "u16",
            Lane::U32 => "u32",
            Lane::U64 => "u64",
        }
    }

    /// Width in bits.
    pub fn bits(self) -> u32 {
        match self {
            Lane::U8 => 8,
            Lane::U16 => 16,
            Lane::U32 => 32,
            Lane::U64 => 64,
        }
    }
}

/// The core type of a value parameter or result.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum CoreTy {
    /// A machine word (`U32`).
    Word(Lane),
    /// A fixed-length array of lanes, lane 0 first (`Array U32 4usize`).
    Vector(Lane, u32),
}

impl CoreTy {
    /// The type in core text.
    pub fn text(self) -> String {
        match self {
            CoreTy::Word(l) => l.core_name().to_string(),
            CoreTy::Vector(l, n) => format!("Array {} {n}usize", l.core_name()),
        }
    }
}

use CoreTy::{Vector, Word};

/// NEON `uint8x16_t` / x86 `__m128i`.
const U8X16: CoreTy = Vector(Lane::U8, 16);
/// NEON `uint8x8_t`.
const U8X8: CoreTy = Vector(Lane::U8, 8);
/// NEON `uint32x4_t` (also `[u32; 4]`).
const U32X4: CoreTy = Vector(Lane::U32, 4);
/// NEON `uint16x8_t`.
const U16X8: CoreTy = Vector(Lane::U16, 8);
/// NEON `uint64x2_t`.
const U64X2: CoreTy = Vector(Lane::U64, 2);
/// NEON `uint32x2_t`.
const U32X2: CoreTy = Vector(Lane::U32, 2);
/// x86 `__m256i`.
const U8X32: CoreTy = Vector(Lane::U8, 32);
/// `[u32; 8]` (the AVX2 lane kernels' pack/unpack arrays).
const U32X8: CoreTy = Vector(Lane::U32, 8);
/// `[u32; 16]` (the AVX-512 lane kernels' pack/unpack arrays).
const U32X16: CoreTy = Vector(Lane::U32, 16);
/// x86 `__m512i`.
const U8X64: CoreTy = Vector(Lane::U8, 64);

/// An immediate parameter (a stdarch `const` generic) and its accepted range.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct CoreImm {
    /// Parameter name (`N`, `LANE`, `IMM8`).
    pub name: &'static str,
    /// Smallest accepted value.
    pub lo: u32,
    /// Largest accepted value.
    pub hi: u32,
}

/// One binder of a core global's Π telescope.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Binder {
    /// Binder name.
    pub name: String,
    /// `false` for the irrelevant range proofs.
    pub relevant: bool,
    /// The binder's type in core text.
    pub ty: String,
    /// What the argument is.
    pub role: Role,
}

/// The role of a binder, telling a caller what to pass.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Role {
    /// The immediate itself: a `U32` literal in range.
    Imm {
        /// Index into [`CoreModel::imms`].
        index: usize,
    },
    /// A range proof of the preceding immediate: pass `.refl(Bool, true)`.
    ImmProof {
        /// Index into [`CoreModel::imms`].
        index: usize,
    },
    /// A value argument.
    Value {
        /// Index into [`CoreModel::params`].
        index: usize,
    },
}

/// A core-text model: the `def[intrinsic]` global transcribing one
/// intrinsic of the registry, and its signature.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CoreModel {
    /// Architecture.
    pub arch: Arch,
    /// The stdarch name (the registry's [`Model::name`]).
    pub name: &'static str,
    /// The core global name (`aarch64::vaddq_u32`).
    pub global: &'static str,
    /// Immediates, in order (they come first in the telescope).
    pub imms: &'static [CoreImm],
    /// Value parameters `(name, type)` in stdarch order.
    pub params: &'static [(&'static str, CoreTy)],
    /// Result type.
    pub ret: CoreTy,
}

impl CoreModel {
    /// The registry entry of the executable model.
    pub fn model(&self) -> &'static Model {
        registry::find(self.arch, self.name).expect("every core model has a registry entry (tested)")
    }

    /// The `core::arch` path the intrinsic prints as.
    pub fn rust_path(&self) -> &'static str {
        self.model().rust_path
    }

    /// The full telescope: immediates with their range proofs, then values.
    pub fn telescope(&self) -> Vec<Binder> {
        let mut out = Vec::new();
        for (index, imm) in self.imms.iter().enumerate() {
            out.push(Binder {
                name: imm.name.to_string(),
                relevant: true,
                ty: "U32".to_string(),
                role: Role::Imm { index },
            });
            if imm.lo > 0 {
                out.push(Binder {
                    name: format!("h{}0", imm.name),
                    relevant: false,
                    ty: format!("Eq(Bool, #le_u32({}u32, {}), true)", imm.lo, imm.name),
                    role: Role::ImmProof { index },
                });
            }
            out.push(Binder {
                name: format!("h{}", imm.name),
                relevant: false,
                ty: format!("Eq(Bool, #le_u32({}, {}u32), true)", imm.name, imm.hi),
                role: Role::ImmProof { index },
            });
        }
        for (index, (name, ty)) in self.params.iter().enumerate() {
            out.push(Binder {
                name: name.to_string(),
                relevant: true,
                ty: ty.text(),
                role: Role::Value { index },
            });
        }
        out
    }

    /// The global's type in core text, e.g.
    /// `(N : U32) -> (.hN : Eq(Bool, #le_u32(N, 31u32), true)) -> (a : Array U32 4usize) -> Array U32 4usize`.
    pub fn type_text(&self) -> String {
        let mut s = String::new();
        for b in self.telescope() {
            let dot = if b.relevant { "" } else { "." };
            s.push_str(&format!("({dot}{} : {}) -> ", b.name, b.ty));
        }
        s.push_str(&self.ret.text());
        s
    }

    /// A call in core text: `imms` are the immediate values (checked against
    /// their ranges), `args` the core text of the value arguments.
    pub fn apply_text(&self, imms: &[u32], args: &[&str]) -> Result<String, String> {
        if imms.len() != self.imms.len() || args.len() != self.params.len() {
            return Err(format!(
                "{} takes {} immediate(s) and {} argument(s), got {} and {}",
                self.global,
                self.imms.len(),
                self.params.len(),
                imms.len(),
                args.len()
            ));
        }
        let mut s = self.global.to_string();
        for b in self.telescope() {
            match b.role {
                Role::Imm { index } => {
                    let (v, imm) = (imms[index], self.imms[index]);
                    if v < imm.lo || v > imm.hi {
                        return Err(format!("{}: immediate {} = {v} out of range {}..={}", self.global, imm.name, imm.lo, imm.hi));
                    }
                    s.push_str(&format!(" {v}u32"));
                }
                Role::ImmProof { .. } => s.push_str(" .refl(Bool, true)"),
                Role::Value { index } => s.push_str(&format!(" ({})", args[index])),
            }
        }
        Ok(s)
    }

    /// The core items defining this model: the global first, then every
    /// helper it uses (transitively), in file order.
    pub fn items(&self) -> Vec<&'static str> {
        core_items(self.arch, self.global)
    }

    /// The core hash of this model ([`core_hash`]).
    pub fn hash(&self) -> String {
        core_hash(self.arch, self.global)
    }
}

const fn imm(name: &'static str, lo: u32, hi: u32) -> CoreImm {
    CoreImm { name, lo, hi }
}

macro_rules! core_model {
    ($arch:ident, $prefix:literal, $name:ident, [$($imm:expr),*], [$($p:ident : $t:expr),*], $ret:expr) => {
        CoreModel {
            arch: Arch::$arch,
            name: stringify!($name),
            global: concat!($prefix, stringify!($name)),
            imms: &[$($imm),*],
            params: &[$((stringify!($p), $t)),*],
            ret: $ret,
        }
    };
}

macro_rules! a64 {
    ($name:ident, [$($imm:expr),*], [$($p:ident : $t:expr),*], $ret:expr) => {
        core_model!(Aarch64, "aarch64::", $name, [$($imm),*], [$($p : $t),*], $ret)
    };
}

macro_rules! x86 {
    ($name:ident, [$($imm:expr),*], [$($p:ident : $t:expr),*], $ret:expr) => {
        core_model!(X86_64, "x86_64::", $name, [$($imm),*], [$($p : $t),*], $ret)
    };
}

/// The aarch64 core models, one per [`registry::AARCH64`] entry, in the same order.
pub static AARCH64_CORE_MODELS: &[CoreModel] = &[
    a64!(vld1q_u8, [], [mem: U8X16], U8X16),
    a64!(vld1q_u32, [], [mem: U32X4], U32X4),
    a64!(vld1_u8, [], [mem: U8X8], U8X8),
    a64!(vst1q_u8, [], [a: U8X16], U8X16),
    a64!(vst1q_u32, [], [a: U32X4], U32X4),
    a64!(vrev32q_u8, [], [a: U8X16], U8X16),
    a64!(vreinterpretq_u32_u8, [], [a: U8X16], U32X4),
    a64!(vreinterpretq_u8_u32, [], [a: U32X4], U8X16),
    a64!(vaddq_u32, [], [a: U32X4, b: U32X4], U32X4),
    a64!(veorq_u32, [], [a: U32X4, b: U32X4], U32X4),
    a64!(vandq_u32, [], [a: U32X4, b: U32X4], U32X4),
    a64!(vorrq_u32, [], [a: U32X4, b: U32X4], U32X4),
    a64!(vshlq_n_u32, [imm("N", 0, 31)], [a: U32X4], U32X4),
    a64!(vshrq_n_u32, [imm("N", 1, 32)], [a: U32X4], U32X4),
    a64!(vextq_u32, [imm("N", 0, 3)], [a: U32X4, b: U32X4], U32X4),
    a64!(vdupq_n_u32, [], [value: Word(Lane::U32)], U32X4),
    a64!(vgetq_lane_u32, [imm("LANE", 0, 3)], [v: U32X4], Word(Lane::U32)),
    a64!(vsetq_lane_u32, [imm("LANE", 0, 3)], [a: Word(Lane::U32), b: U32X4], U32X4),
    a64!(vsetq_lane_u8, [imm("LANE", 0, 15)], [a: Word(Lane::U8), b: U8X16], U8X16),
    a64!(vsha256hq_u32, [], [hash_abcd: U32X4, hash_efgh: U32X4, wk: U32X4], U32X4),
    a64!(vsha256h2q_u32, [], [hash_efgh: U32X4, hash_abcd: U32X4, wk: U32X4], U32X4),
    a64!(vsha256su0q_u32, [], [w0_3: U32X4, w4_7: U32X4], U32X4),
    a64!(vsha256su1q_u32, [], [tw0_3: U32X4, w8_11: U32X4, w12_15: U32X4], U32X4),
    // plan O10 (MODELS.md §3.1, §4.1)
    a64!(vld1q_u64, [], [mem: U64X2], U64X2),
    a64!(vst1q_u64, [], [a: U64X2], U64X2),
    a64!(veorq_u8, [], [a: U8X16, b: U8X16], U8X16),
    a64!(vandq_u8, [], [a: U8X16, b: U8X16], U8X16),
    a64!(vorrq_u8, [], [a: U8X16, b: U8X16], U8X16),
    a64!(vdupq_n_u8, [], [value: Word(Lane::U8)], U8X16),
    a64!(vshrq_n_u8, [imm("N", 1, 8)], [a: U8X16], U8X16),
    a64!(vcltq_u8, [], [a: U8X16, b: U8X16], U8X16),
    a64!(vcgeq_u8, [], [a: U8X16, b: U8X16], U8X16),
    a64!(vceqq_u8, [], [a: U8X16, b: U8X16], U8X16),
    a64!(vqtbl1q_u8, [], [t: U8X16, idx: U8X16], U8X16),
    a64!(vcntq_u8, [], [a: U8X16], U8X16),
    a64!(vaddvq_u8, [], [a: U8X16], Word(Lane::U8)),
    a64!(vmaxvq_u8, [], [a: U8X16], Word(Lane::U8)),
    a64!(vreinterpretq_u16_u8, [], [a: U8X16], U16X8),
    a64!(vreinterpretq_u64_u8, [], [a: U8X16], U64X2),
    a64!(vcombine_u8, [], [low: U8X8, high: U8X8], U8X16),
    a64!(vgetq_lane_u64, [imm("LANE", 0, 1)], [v: U64X2], Word(Lane::U64)),
    a64!(vshrn_n_u16, [imm("N", 1, 8)], [a: U16X8], U8X8),
    a64!(vshrn_n_u64, [imm("N", 1, 32)], [a: U64X2], U32X2),
    a64!(vmovn_u64, [], [a: U64X2], U32X2),
    a64!(vaddq_u64, [], [a: U64X2, b: U64X2], U64X2),
    a64!(vsraq_n_u64, [imm("N", 1, 64)], [a: U64X2, b: U64X2], U64X2),
    a64!(vbslq_u64, [], [a: U64X2, b: U64X2, c: U64X2], U64X2),
    a64!(vbslq_u32, [], [a: U32X4, b: U32X4, c: U32X4], U32X4),
    a64!(vmull_u32, [], [a: U32X2, b: U32X2], U64X2),
    a64!(vmlal_u32, [], [a: U64X2, b: U32X2, c: U32X2], U64X2),
    a64!(veor3q_u8, [], [a: U8X16, b: U8X16, c: U8X16], U8X16),
    a64!(vbcaxq_u8, [], [a: U8X16, b: U8X16, c: U8X16], U8X16),
    a64!(vrax1q_u64, [], [a: U64X2, b: U64X2], U64X2),
    a64!(vxarq_u64, [imm("IMM6", 0, 63)], [a: U64X2, b: U64X2], U64X2),
    a64!(vsha512hq_u64, [], [hash_ed: U64X2, hash_gf: U64X2, kwh_kwh2: U64X2], U64X2),
    a64!(vsha512h2q_u64, [], [sum_ab: U64X2, hash_c_: U64X2, hash_ab: U64X2], U64X2),
    a64!(vsha512su0q_u64, [], [w0_1: U64X2, w2_: U64X2], U64X2),
    a64!(vsha512su1q_u64, [], [s01_s02: U64X2, w14_15: U64X2, w9_10: U64X2], U64X2),
];

/// The x86_64 core models, one per [`registry::X86_64`] entry, in the same order.
pub static X86_64_CORE_MODELS: &[CoreModel] = &[
    x86!(_mm_loadu_si128, [], [mem: U8X16], U8X16),
    x86!(_mm_storeu_si128, [], [a: U8X16], U8X16),
    x86!(_mm_shuffle_epi8, [], [a: U8X16, b: U8X16], U8X16),
    x86!(_mm_shuffle_epi32, [imm("IMM8", 0, 255)], [a: U8X16], U8X16),
    x86!(_mm_alignr_epi8, [imm("IMM8", 0, 255)], [a: U8X16, b: U8X16], U8X16),
    x86!(_mm_blend_epi16, [imm("IMM8", 0, 255)], [a: U8X16, b: U8X16], U8X16),
    x86!(_mm_add_epi32, [], [a: U8X16, b: U8X16], U8X16),
    x86!(
        _mm_set_epi32,
        [],
        [e3: Word(Lane::U32), e2: Word(Lane::U32), e1: Word(Lane::U32), e0: Word(Lane::U32)],
        U8X16
    ),
    x86!(_mm_set_epi64x, [], [e1: Word(Lane::U64), e0: Word(Lane::U64)], U8X16),
    x86!(_mm_xor_si128, [], [a: U8X16, b: U8X16], U8X16),
    x86!(_mm_and_si128, [], [a: U8X16, b: U8X16], U8X16),
    x86!(_mm_or_si128, [], [a: U8X16, b: U8X16], U8X16),
    x86!(_mm_sha256rnds2_epu32, [], [a: U8X16, b: U8X16, k: U8X16], U8X16),
    x86!(_mm_sha256msg1_epu32, [], [a: U8X16, b: U8X16], U8X16),
    x86!(_mm_sha256msg2_epu32, [], [a: U8X16, b: U8X16], U8X16),
    // -- 256/512-bit families (core/x86_64_avx.core; generated rows of
    // `python3 gen/x86_64_avx.py coretext`).
    x86!(_mm512_loadu_si512, [], [mem: U8X64], U8X64),
    x86!(_mm512_storeu_si512, [], [a: U8X64], U8X64),
    x86!(_mm512_add_epi32, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_add_epi64, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_sub_epi32, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_sub_epi64, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_xor_si512, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_and_si512, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_or_si512, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_andnot_si512, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_ternarylogic_epi32, [imm("IMM8", 0, 255)], [a: U8X64, b: U8X64, c: U8X64], U8X64),
    x86!(_mm512_ternarylogic_epi64, [imm("IMM8", 0, 255)], [a: U8X64, b: U8X64, c: U8X64], U8X64),
    x86!(_mm512_rol_epi32, [imm("IMM8", 0, 255)], [a: U8X64], U8X64),
    x86!(_mm512_ror_epi32, [imm("IMM8", 0, 255)], [a: U8X64], U8X64),
    x86!(_mm512_rol_epi64, [imm("IMM8", 0, 255)], [a: U8X64], U8X64),
    x86!(_mm512_ror_epi64, [imm("IMM8", 0, 255)], [a: U8X64], U8X64),
    x86!(_mm512_rolv_epi32, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_rorv_epi32, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_rolv_epi64, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_rorv_epi64, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_slli_epi32, [imm("IMM8", 0, 255)], [a: U8X64], U8X64),
    x86!(_mm512_srli_epi32, [imm("IMM8", 0, 255)], [a: U8X64], U8X64),
    x86!(_mm512_slli_epi64, [imm("IMM8", 0, 255)], [a: U8X64], U8X64),
    x86!(_mm512_srli_epi64, [imm("IMM8", 0, 255)], [a: U8X64], U8X64),
    x86!(_mm512_sllv_epi64, [], [a: U8X64, count: U8X64], U8X64),
    x86!(_mm512_srlv_epi64, [], [a: U8X64, count: U8X64], U8X64),
    x86!(_mm512_shuffle_epi8, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_permutexvar_epi32, [], [idx: U8X64, a: U8X64], U8X64),
    x86!(_mm512_permutexvar_epi64, [], [idx: U8X64, a: U8X64], U8X64),
    x86!(_mm512_permutex2var_epi64, [], [a: U8X64, idx: U8X64, b: U8X64], U8X64),
    x86!(_mm512_shuffle_i32x4, [imm("MASK", 0, 255)], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_shuffle_i64x2, [imm("MASK", 0, 255)], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_unpacklo_epi32, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_unpackhi_epi32, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_unpacklo_epi64, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_unpackhi_epi64, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_set1_epi32, [], [a: Word(Lane::U32)], U8X64),
    x86!(_mm512_set1_epi64, [], [a: Word(Lane::U64)], U8X64),
    x86!(_mm512_mask_blend_epi32, [], [k: Word(Lane::U16), a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_mask_blend_epi64, [], [k: Word(Lane::U8), a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_cmplt_epu64_mask, [], [a: U8X64, b: U8X64], Word(Lane::U8)),
    x86!(_mm512_cmpeq_epi64_mask, [], [a: U8X64, b: U8X64], Word(Lane::U8)),
    x86!(_mm512_cmpeq_epi32_mask, [], [a: U8X64, b: U8X64], Word(Lane::U16)),
    x86!(_mm512_maskz_mov_epi32, [], [k: Word(Lane::U16), a: U8X64], U8X64),
    x86!(_mm512_mask_mov_epi32, [], [src: U8X64, k: Word(Lane::U16), a: U8X64], U8X64),
    x86!(_mm512_maskz_mov_epi64, [], [k: Word(Lane::U8), a: U8X64], U8X64),
    x86!(_mm512_mask_mov_epi64, [], [src: U8X64, k: Word(Lane::U8), a: U8X64], U8X64),
    x86!(_mm512_mullo_epi64, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_mul_epu32, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm256_ternarylogic_epi32, [imm("IMM8", 0, 255)], [a: U8X32, b: U8X32, c: U8X32], U8X32),
    x86!(_mm256_ternarylogic_epi64, [imm("IMM8", 0, 255)], [a: U8X32, b: U8X32, c: U8X32], U8X32),
    x86!(_mm256_rol_epi32, [imm("IMM8", 0, 255)], [a: U8X32], U8X32),
    x86!(_mm256_ror_epi32, [imm("IMM8", 0, 255)], [a: U8X32], U8X32),
    x86!(_mm256_rol_epi64, [imm("IMM8", 0, 255)], [a: U8X32], U8X32),
    x86!(_mm256_ror_epi64, [imm("IMM8", 0, 255)], [a: U8X32], U8X32),
    x86!(_mm512_madd52lo_epu64, [], [a: U8X64, b: U8X64, c: U8X64], U8X64),
    x86!(_mm512_madd52hi_epu64, [], [a: U8X64, b: U8X64, c: U8X64], U8X64),
    x86!(_mm256_madd52lo_epu64, [], [a: U8X32, b: U8X32, c: U8X32], U8X32),
    x86!(_mm256_madd52hi_epu64, [], [a: U8X32, b: U8X32, c: U8X32], U8X32),
    x86!(_mm512_gf2p8mul_epi8, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm256_gf2p8mul_epi8, [], [a: U8X32, b: U8X32], U8X32),
    x86!(_mm_gf2p8mul_epi8, [], [a: U8X16, b: U8X16], U8X16),
    x86!(_mm512_gf2p8affine_epi64_epi8, [imm("B", 0, 255)], [x: U8X64, a: U8X64], U8X64),
    x86!(_mm256_gf2p8affine_epi64_epi8, [imm("B", 0, 255)], [x: U8X32, a: U8X32], U8X32),
    x86!(_mm_gf2p8affine_epi64_epi8, [imm("B", 0, 255)], [x: U8X16, a: U8X16], U8X16),
    x86!(_mm512_gf2p8affineinv_epi64_epi8, [imm("B", 0, 255)], [x: U8X64, a: U8X64], U8X64),
    x86!(_mm256_gf2p8affineinv_epi64_epi8, [imm("B", 0, 255)], [x: U8X32, a: U8X32], U8X32),
    x86!(_mm_gf2p8affineinv_epi64_epi8, [imm("B", 0, 255)], [x: U8X16, a: U8X16], U8X16),
    x86!(_mm512_permutexvar_epi8, [], [idx: U8X64, a: U8X64], U8X64),
    x86!(_mm512_permutex2var_epi8, [], [a: U8X64, idx: U8X64, b: U8X64], U8X64),
    x86!(_mm512_multishift_epi64_epi8, [], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_shldv_epi64, [], [a: U8X64, b: U8X64, c: U8X64], U8X64),
    x86!(_mm512_shrdv_epi64, [], [a: U8X64, b: U8X64, c: U8X64], U8X64),
    x86!(_mm512_shldv_epi32, [], [a: U8X64, b: U8X64, c: U8X64], U8X64),
    x86!(_mm512_shrdv_epi32, [], [a: U8X64, b: U8X64, c: U8X64], U8X64),
    x86!(_mm512_shldi_epi64, [imm("IMM8", 0, 255)], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_shldi_epi32, [imm("IMM8", 0, 255)], [a: U8X64, b: U8X64], U8X64),
    x86!(_mm512_popcnt_epi64, [], [a: U8X64], U8X64),
    x86!(_mm512_popcnt_epi32, [], [a: U8X64], U8X64),
    x86!(_mm512_popcnt_epi8, [], [a: U8X64], U8X64),
    x86!(_mm512_popcnt_epi16, [], [a: U8X64], U8X64),
    x86!(_mm256_loadu_si256, [], [mem: U8X32], U8X32),
    x86!(_mm256_storeu_si256, [], [a: U8X32], U8X32),
    x86!(_mm256_add_epi32, [], [a: U8X32, b: U8X32], U8X32),
    x86!(_mm256_add_epi64, [], [a: U8X32, b: U8X32], U8X32),
    x86!(_mm256_xor_si256, [], [a: U8X32, b: U8X32], U8X32),
    x86!(_mm256_and_si256, [], [a: U8X32, b: U8X32], U8X32),
    x86!(_mm256_or_si256, [], [a: U8X32, b: U8X32], U8X32),
    x86!(_mm256_shuffle_epi8, [], [a: U8X32, b: U8X32], U8X32),
    x86!(_mm256_permutevar8x32_epi32, [], [a: U8X32, idx: U8X32], U8X32),
    x86!(_mm256_slli_epi32, [imm("IMM8", 0, 255)], [a: U8X32], U8X32),
    x86!(_mm256_srli_epi32, [imm("IMM8", 0, 255)], [a: U8X32], U8X32),
    x86!(_mm256_slli_epi64, [imm("IMM8", 0, 255)], [a: U8X32], U8X32),
    x86!(_mm256_srli_epi64, [imm("IMM8", 0, 255)], [a: U8X32], U8X32),
    x86!(_mm256_blend_epi32, [imm("IMM8", 0, 255)], [a: U8X32, b: U8X32], U8X32),
    x86!(_mm256_alignr_epi8, [imm("IMM8", 0, 255)], [a: U8X32, b: U8X32], U8X32),
    x86!(_mm256_set1_epi32, [], [a: Word(Lane::U32)], U8X32),
    x86!(_mm256_set1_epi64x, [], [a: Word(Lane::U64)], U8X32),
];

/// The core models of an architecture (same order as [`Arch::models`]).
pub fn models(arch: Arch) -> &'static [CoreModel] {
    match arch {
        Arch::Aarch64 => AARCH64_CORE_MODELS,
        Arch::X86_64 => X86_64_CORE_MODELS,
    }
}

/// The core model of `name` (a stdarch intrinsic name) on `arch`.
pub fn find(arch: Arch, name: &str) -> Option<&'static CoreModel> {
    models(arch).iter().find(|m| m.name == name)
}

/// Normalize a Rust path for lookup: drop a leading `::` and read `std::`
/// as `core::` (`::std::arch::aarch64::vaddq_u32` → `core::arch::aarch64::vaddq_u32`).
fn normalize_path(path: &str) -> String {
    let p = path.trim().trim_start_matches("::");
    match p.strip_prefix("std::") {
        Some(rest) => format!("core::{rest}"),
        None => p.to_string(),
    }
}

/// The core model of an intrinsic by its Rust path
/// (`core::arch::aarch64::vaddq_u32`, also with a leading `::` or `std::`).
pub fn find_by_path(path: &str) -> Option<&'static CoreModel> {
    let p = normalize_path(path);
    AARCH64_CORE_MODELS.iter().chain(X86_64_CORE_MODELS).find(|m| m.rust_path() == p)
}

/// A safe load/store helper of `sandblaster::arch::<arch>` (trusted glue,
/// DESIGN.md §9.2) and the core global giving its meaning.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CoreHelper {
    /// Architecture.
    pub arch: Arch,
    /// The helper's name (`load_u8x16`).
    pub name: &'static str,
    /// Its Rust path (`sandblaster::arch::aarch64::load_u8x16`).
    pub rust_path: &'static str,
    /// The core global it elaborates to (an intrinsic model, or a
    /// `def[intrinsic]` wrapper in the core file).
    pub global: &'static str,
    /// Value parameters (a `&[T; N]` parameter is the array itself).
    pub params: &'static [(&'static str, CoreTy)],
    /// Result type.
    pub ret: CoreTy,
    /// The registry model(s) its meaning uses (their evidence gates it).
    pub uses: &'static [&'static str],
}

/// The helpers of `sandblaster::arch` with a core meaning. (`load_u64x2` /
/// `store_u64x2` wrap `vld1q_u64` / `vst1q_u64`, which have no model yet.)
pub static CORE_HELPERS: &[CoreHelper] = &[
    CoreHelper {
        arch: Arch::Aarch64,
        name: "load_u8x16",
        rust_path: "sandblaster::arch::aarch64::load_u8x16",
        global: "aarch64::vld1q_u8",
        params: &[("mem", U8X16)],
        ret: U8X16,
        uses: &["vld1q_u8"],
    },
    CoreHelper {
        arch: Arch::Aarch64,
        name: "load_u32x4",
        rust_path: "sandblaster::arch::aarch64::load_u32x4",
        global: "aarch64::vld1q_u32",
        params: &[("mem", U32X4)],
        ret: U32X4,
        uses: &["vld1q_u32"],
    },
    CoreHelper {
        arch: Arch::Aarch64,
        name: "load_u8x8",
        rust_path: "sandblaster::arch::aarch64::load_u8x8",
        global: "aarch64::vld1_u8",
        params: &[("mem", U8X8)],
        ret: U8X8,
        uses: &["vld1_u8"],
    },
    CoreHelper {
        arch: Arch::Aarch64,
        name: "store_u8x16",
        rust_path: "sandblaster::arch::aarch64::store_u8x16",
        global: "aarch64::vst1q_u8",
        params: &[("a", U8X16)],
        ret: U8X16,
        uses: &["vst1q_u8"],
    },
    CoreHelper {
        arch: Arch::Aarch64,
        name: "store_u32x4",
        rust_path: "sandblaster::arch::aarch64::store_u32x4",
        global: "aarch64::vst1q_u32",
        params: &[("a", U32X4)],
        ret: U32X4,
        uses: &["vst1q_u32"],
    },
    CoreHelper {
        arch: Arch::X86_64,
        name: "load_u8x16",
        rust_path: "sandblaster::arch::x86_64::load_u8x16",
        global: "x86_64::_mm_loadu_si128",
        params: &[("mem", U8X16)],
        ret: U8X16,
        uses: &["_mm_loadu_si128"],
    },
    CoreHelper {
        arch: Arch::X86_64,
        name: "load_u32x4",
        rust_path: "sandblaster::arch::x86_64::load_u32x4",
        global: "x86_64::load_u32x4",
        params: &[("a", U32X4)],
        ret: U8X16,
        uses: &["_mm_loadu_si128"],
    },
    CoreHelper {
        arch: Arch::X86_64,
        name: "m128i_from_u32x4",
        rust_path: "sandblaster::arch::x86_64::m128i_from_u32x4",
        global: "x86_64::m128i_from_u32x4",
        params: &[("a", U32X4)],
        ret: U8X16,
        uses: &["_mm_loadu_si128"],
    },
    CoreHelper {
        arch: Arch::X86_64,
        name: "store_u8x16",
        rust_path: "sandblaster::arch::x86_64::store_u8x16",
        global: "x86_64::_mm_storeu_si128",
        params: &[("a", U8X16)],
        ret: U8X16,
        uses: &["_mm_storeu_si128"],
    },
    CoreHelper {
        arch: Arch::X86_64,
        name: "store_u32x4",
        rust_path: "sandblaster::arch::x86_64::store_u32x4",
        global: "x86_64::store_u32x4",
        params: &[("v", U8X16)],
        ret: U32X4,
        uses: &["_mm_storeu_si128"],
    },
    // plan O10: the lane kernels' pack and unpack
    CoreHelper {
        arch: Arch::X86_64,
        name: "load_u32x8",
        rust_path: "sandblaster::arch::x86_64::load_u32x8",
        global: "x86_64::load_u32x8",
        params: &[("a", U32X8)],
        ret: U8X32,
        uses: &["_mm256_loadu_si256"],
    },
    CoreHelper {
        arch: Arch::X86_64,
        name: "store_u32x8",
        rust_path: "sandblaster::arch::x86_64::store_u32x8",
        global: "x86_64::store_u32x8",
        params: &[("v", U8X32)],
        ret: U32X8,
        uses: &["_mm256_storeu_si256"],
    },
    CoreHelper {
        arch: Arch::X86_64,
        name: "load_u32x16",
        rust_path: "sandblaster::arch::x86_64::load_u32x16",
        global: "x86_64::load_u32x16",
        params: &[("a", U32X16)],
        ret: U8X64,
        uses: &["_mm512_loadu_si512"],
    },
    CoreHelper {
        arch: Arch::X86_64,
        name: "store_u32x16",
        rust_path: "sandblaster::arch::x86_64::store_u32x16",
        global: "x86_64::store_u32x16",
        params: &[("v", U8X64)],
        ret: U32X16,
        uses: &["_mm512_storeu_si512"],
    },
];

impl CoreHelper {
    /// The global's type in core text.
    pub fn type_text(&self) -> String {
        let mut s = String::new();
        for (name, ty) in self.params {
            s.push_str(&format!("({name} : {}) -> ", ty.text()));
        }
        s.push_str(&self.ret.text());
        s
    }
}

/// A helper by its Rust path (`sandblaster::arch::x86_64::load_u32x4`, also
/// with a leading `::`).
pub fn find_helper(path: &str) -> Option<&'static CoreHelper> {
    let p = normalize_path(path);
    CORE_HELPERS.iter().find(|h| h.rust_path == p)
}

// ---------------------------------------------------------------------------
// Items and hashes

/// Strip `--` line comments.
fn strip_comments(text: &str) -> String {
    text.lines()
        .map(|l| match l.find("--") {
            Some(i) => &l[..i],
            None => l,
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Normalize core text for hashing: comments removed, every whitespace run
/// replaced by one space. (Changing the spacing *between* two tokens that
/// had none, e.g. `f(x)` → `f (x)`, changes the hash: fail closed.)
pub fn normalize(text: &str) -> String {
    strip_comments(text).split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Is this line the start of a core item?
fn item_start(line: &str) -> bool {
    line.starts_with("def[") || line.starts_with("def ") || line.starts_with("inductive ")
}

/// The name declared by an item-start line (`def[intrinsic] aarch64::vaddq_u32 : ...`).
fn item_name(line: &str) -> Option<&str> {
    let rest = if let Some(r) = line.strip_prefix("inductive ") {
        r
    } else {
        let r = line.strip_prefix("def")?;
        match r.strip_prefix('[') {
            Some(r) => r.split_once(']')?.1,
            None => r,
        }
    };
    rest.split_whitespace().next()
}

/// The names of the items of a core file, in order.
pub fn item_names(src: &str) -> Vec<&str> {
    src.lines().filter(|l| item_start(l)).filter_map(item_name).collect()
}

/// The raw text of item `name` in `src`: from its `def` line up to the next
/// item (trailing comments included; [`normalize`] drops them).
pub fn item_text<'a>(src: &'a str, name: &str) -> Option<&'a str> {
    let mut start = None;
    let mut offset = 0;
    for line in src.split_inclusive('\n') {
        if item_start(line) {
            if let Some(s) = start {
                return Some(&src[s..offset]);
            }
            if item_name(line) == Some(name) {
                start = Some(offset);
            }
        }
        offset += line.len();
    }
    start.map(|s| &src[s..])
}

/// The identifiers of normalized text that name items of the same file
/// (`aarch64::...` / `x86_64::...`), in order of first occurrence.
fn referenced(arch: Arch, text: &str, defined: &[&str]) -> Vec<String> {
    let prefix = global_prefix(arch);
    let mut out: Vec<String> = Vec::new();
    let bytes = text.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        let c = bytes[i] as char;
        if c.is_ascii_alphabetic() || c == '_' {
            let start = i;
            while i < bytes.len() {
                let c = bytes[i] as char;
                if c.is_ascii_alphanumeric() || c == '_' || c == '\'' {
                    i += 1;
                } else if c == ':' && bytes.get(i + 1) == Some(&b':') {
                    i += 2;
                } else {
                    break;
                }
            }
            let id = &text[start..i];
            if id.starts_with(prefix) && defined.contains(&id) && !out.iter().any(|o| o == id) {
                out.push(id.to_string());
            }
        } else {
            i += 1;
        }
    }
    out
}

/// The core items defining global `global` of `arch`: the global itself,
/// then every item of the same file it references, transitively, in file
/// order. (Prelude globals are not included: they belong to the kernel's
/// TCB item 3 and are versioned with it.)
pub fn core_items(arch: Arch, global: &str) -> Vec<&'static str> {
    let src = core_text(arch);
    let defined = item_names(src);
    let mut seen: Vec<String> = vec![global.to_string()];
    let mut todo: Vec<String> = vec![global.to_string()];
    while let Some(g) = todo.pop() {
        let Some(text) = item_text(src, &g) else { continue };
        let body = normalize(text);
        // Skip the declared name itself.
        for r in referenced(arch, &body, &defined) {
            if !seen.contains(&r) {
                seen.push(r.clone());
                todo.push(r);
            }
        }
    }
    let mut out: Vec<&'static str> = vec![];
    if let Some(g) = defined.iter().find(|d| **d == global) {
        out.push(g);
    }
    out.extend(defined.iter().filter(|d| **d != global && seen.iter().any(|s| s == *d)));
    out
}

/// `sha256:<hex>` over the model's core items ([`core_items`]): the
/// concatenation of `"<name>\n<normalized item text>\n"`.
pub fn core_hash(arch: Arch, global: &str) -> String {
    // (memoized per process: the core text is compiled in)
    static MEMO: std::sync::Mutex<Vec<(Arch, String, String)>> = std::sync::Mutex::new(Vec::new());
    if let Some((_, _, h)) = MEMO.lock().unwrap_or_else(|e| e.into_inner()).iter().find(|(a, g, _)| *a == arch && g == global) {
        return h.clone();
    }
    let h = core_hash_uncached(arch, global);
    MEMO.lock().unwrap_or_else(|e| e.into_inner()).push((arch, global.to_string(), h.clone()));
    h
}

fn core_hash_uncached(arch: Arch, global: &str) -> String {
    let src = core_text(arch);
    let mut input = String::new();
    for name in core_items(arch, global) {
        input.push_str(name);
        input.push('\n');
        input.push_str(&normalize(item_text(src, name).unwrap_or("")));
        input.push('\n');
    }
    format!("sha256:{}", fips::hex(&fips::sha256(input.as_bytes())))
}

/// The declared type of item `name` (the text between the name and `:=`),
/// normalized.
pub fn declared_type(src: &str, name: &str) -> Option<String> {
    let text = normalize(item_text(src, name)?);
    let after = text.split_once(&format!(" {name} : "))?.1;
    Some(after.split_once(" :=")?.0.trim().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_registry_model_has_a_core_model_in_order() {
        for arch in [Arch::Aarch64, Arch::X86_64] {
            let reg = arch.models();
            let core = models(arch);
            assert_eq!(reg.len(), core.len(), "{}", arch.name());
            for (m, c) in reg.iter().zip(core) {
                assert_eq!(m.name, c.name);
                assert_eq!(c.arch, arch);
                assert_eq!(c.global, format!("{}{}", global_prefix(arch), m.name));
                // Immediates agree with the registry's (tested) ranges.
                match &m.immediates {
                    None => assert!(c.imms.is_empty(), "{}", m.name),
                    Some(r) => {
                        assert_eq!(c.imms.len(), 1, "{}", m.name);
                        assert_eq!((c.imms[0].lo as i32, c.imms[0].hi as i32), (*r.start(), *r.end()), "{}", m.name);
                    }
                }
                assert_eq!(find_by_path(m.rust_path), Some(c));
                assert_eq!(find_by_path(&format!("::{}", m.rust_path)), Some(c));
            }
        }
        assert_eq!(
            find_by_path("::std::arch::aarch64::vsha256h2q_u32").map(|m| m.global),
            Some("aarch64::vsha256h2q_u32")
        );
        assert!(find_by_path("core::arch::aarch64::vsha512rq_u64").is_none());
    }

    #[test]
    fn declared_types_match_the_registry_signatures() {
        for arch in [Arch::Aarch64, Arch::X86_64] {
            let src = core_text(arch);
            for c in models(arch) {
                let text = item_text(src, c.global).unwrap_or_else(|| panic!("{} missing from {}", c.global, core_path(arch)));
                assert!(text.starts_with(&format!("def[intrinsic] {} :", c.global)), "{} must be def[intrinsic]", c.global);
                assert_eq!(declared_type(src, c.global).as_deref(), Some(normalize(&c.type_text()).as_str()), "{}", c.global);
            }
            for h in CORE_HELPERS.iter().filter(|h| h.arch == arch) {
                assert_eq!(declared_type(src, h.global).as_deref(), Some(normalize(&h.type_text()).as_str()), "{}", h.global);
                assert!(h.uses.iter().all(|u| find(arch, u).is_some()));
                assert_eq!(find_helper(h.rust_path), Some(h));
            }
        }
    }

    #[test]
    fn only_intrinsic_models_are_intrinsic_and_names_are_unique() {
        for arch in [Arch::Aarch64, Arch::X86_64] {
            let src = core_text(arch);
            let names = item_names(src);
            for (i, n) in names.iter().enumerate() {
                assert!(n.starts_with(global_prefix(arch)), "{n}");
                assert!(!names[..i].contains(n), "duplicate {n}");
            }
            for line in src.lines().filter(|l| l.starts_with("def[intrinsic]")) {
                let n = item_name(line).unwrap();
                assert!(
                    models(arch).iter().any(|c| c.global == n) || CORE_HELPERS.iter().any(|h| h.global == n),
                    "{n} is intrinsic but neither a registry model nor a load/store helper"
                );
            }
            // Every helper global is intrinsic (opaque on symbolic data).
            for h in CORE_HELPERS.iter().filter(|h| h.arch == arch) {
                assert!(item_text(src, h.global).unwrap().starts_with("def[intrinsic]"), "{}", h.global);
            }
        }
    }

    #[test]
    fn items_and_hashes() {
        let add = find(Arch::Aarch64, "vaddq_u32").unwrap();
        assert_eq!(add.items(), ["aarch64::vaddq_u32", "aarch64::u32x4", "aarch64::map2_u32x4"]);
        let h = find(Arch::Aarch64, "vsha256hq_u32").unwrap();
        let items = h.items();
        assert_eq!(items[0], "aarch64::vsha256hq_u32");
        for dep in ["aarch64::sha256hash", "aarch64::sha256hash_iter", "aarch64::sha_choose", "aarch64::concat_u32x4"] {
            assert!(items.contains(&dep), "{dep} in {items:?}");
        }
        assert!(!items.contains(&"aarch64::vsha256h2q_u32"));
        let rnds2 = find(Arch::X86_64, "_mm_sha256rnds2_epu32").unwrap().items();
        assert!(rnds2.contains(&"x86_64::view_u32") && rnds2.contains(&"x86_64::sdm_maj"));
        // Hashes are distinct per model and ignore comments/layout.
        let mut hashes: Vec<String> = models(Arch::Aarch64).iter().chain(models(Arch::X86_64)).map(|c| c.hash()).collect();
        let n = hashes.len();
        hashes.sort();
        hashes.dedup();
        assert_eq!(hashes.len(), n);
        assert_eq!(normalize("f (x)  -- c\n   y"), "f (x) y");
        assert_ne!(normalize("#wshr_u32(x, 3u32)"), normalize("#wshr_u32(x, 4u32)"));
    }

    #[test]
    fn apply_text_checks_immediates() {
        let shl = find(Arch::Aarch64, "vshlq_n_u32").unwrap();
        assert_eq!(shl.apply_text(&[3], &["v"]).unwrap(), "aarch64::vshlq_n_u32 3u32 .refl(Bool, true) (v)");
        assert!(shl.apply_text(&[32], &["v"]).is_err());
        let shr = find(Arch::Aarch64, "vshrq_n_u32").unwrap();
        assert_eq!(
            shr.apply_text(&[32], &["v"]).unwrap(),
            "aarch64::vshrq_n_u32 32u32 .refl(Bool, true) .refl(Bool, true) (v)"
        );
        assert!(shr.apply_text(&[0], &["v"]).is_err());
        assert!(shr.apply_text(&[], &["v"]).is_err());
        assert_eq!(
            shr.type_text(),
            "(N : U32) -> (.hN0 : Eq(Bool, #le_u32(1u32, N), true)) -> (.hN : Eq(Bool, #le_u32(N, 32u32), true)) -> (a : Array U32 4usize) -> Array U32 4usize"
        );
    }
}
