#![doc = include_str!("../README.md")]
#![doc(
    html_logo_url = "https://commonware.xyz/imgs/rustdoc_logo.svg",
    html_favicon_url = "https://commonware.xyz/favicon.ico"
)]

// Allow proc-macro expansions to reference this crate as `::commonware_actor`
// in in-crate tests, doctests, and downstream crates with one stable path.
#[allow(unused_extern_crates)]
extern crate self as commonware_actor;

use commonware_macros::stability_scope;

stability_scope!(ALPHA {
    use std::{fmt::{Debug, Display}, future::Future};

    pub mod mailbox;
    pub mod service;

    #[doc(hidden)]
    pub use commonware_utils::channel::oneshot;
    pub use commonware_actor_macros::ingress;

    /// Stateful task driven by the actor control loop.
    ///
    /// # Lifecycle
    ///
    /// In driver mode ([`service::ServiceBuilder`]), hooks run in this order:
    ///
    /// 1. `on_startup` once (receives [`Actor::Init`] data).
    /// 2. Per iteration: `preprocess`, then race lanes against
    ///    `on_external` for one event. If a message is received (`Some`),
    ///    dispatch to `on_ingress`, then `postprocess`. If the source
    ///    yields `None` (lane closed or `on_external` exhaustion), skip
    ///    directly to `on_shutdown`.
    /// 3. `on_shutdown` once, on graceful exit (runtime stop, lane closure,
    ///    or `on_external` returning `None`).
    ///
    /// Returning `Err` from `on_ingress` is fatal: the error is logged and the
    /// loop exits **without** calling `on_shutdown`. Resource cleanup that must
    /// happen regardless of the exit path should use `Drop`.
    pub trait Actor<E>: Send + 'static {
        /// Typed mailbox returned by the service builder.
        ///
        /// Set this to the mailbox wrapper generated by [`ingress!`] so that
        /// [`service::ServiceBuilder::build`] returns the typed mailbox
        /// directly.
        type Mailbox: Send + Clone + 'static;

        /// Ingress message type consumed by this actor.
        type Ingress: Send + 'static;

        /// Fatal error type returned by [`Actor::on_ingress`].
        ///
        /// Returning `Err` from `on_ingress` logs the error and stops the
        /// actor.
        type Error: Debug + Display + Send + 'static;

        /// Initialization data passed to [`Actor::on_startup`].
        ///
        /// Use `()` for actors that do not need external initialization data.
        /// Actors with non-unit `Init` must be started via
        /// [`service::ActorService::start_with`].
        type Init: Send + 'static;

        /// Runs once when the control loop starts.
        ///
        /// `init` carries externally-provided data that the actor needs before
        /// processing messages (e.g., connection handles, peer identity).
        fn on_startup(
            &mut self,
            _context: &mut E,
            _init: &mut Self::Init,
        ) -> impl Future<Output = ()> + Send {
            async {}
        }

        /// Runs once when the control loop stops gracefully.
        ///
        /// Called on: runtime shutdown signal, lane closure, or
        /// [`Actor::on_external`] returning `None`.
        ///
        /// NOT called when [`Actor::on_ingress`] returns `Err`; the actor
        /// exits immediately in that case.
        fn on_shutdown(
            &mut self,
            _context: &mut E,
            _init: &mut Self::Init,
        ) -> impl Future<Output = ()> + Send {
            async {}
        }

        /// Runs at the beginning of each iteration, before polling for events.
        ///
        /// Use this for periodic housekeeping that should run every loop
        /// iteration regardless of which event fires (e.g., cleaning stale
        /// subscriptions, refreshing state).
        fn preprocess(
            &mut self,
            _context: &mut E,
            _init: &mut Self::Init,
        ) -> impl Future<Output = ()> + Send {
            async {}
        }

        /// Handle one ingress message.
        ///
        /// Returning `Err` is fatal: the service loop logs the error and
        /// exits without calling [`Actor::on_shutdown`].
        fn on_ingress(
            &mut self,
            context: &mut E,
            init: &mut Self::Init,
            message: Self::Ingress,
        ) -> impl Future<Output = Result<(), Self::Error>> + Send;

        /// Poll external per-iteration sources and map them to ingress.
        ///
        /// The service loop recreates this future each iteration and races it
        /// against lane receivers. Returning `Some(ingress)` dispatches one
        /// event via [`Actor::on_ingress`]. Returning `None` signals
        /// exhaustion and stops the actor (calls [`Actor::on_shutdown`]).
        ///
        /// # Cancellation safety
        ///
        /// This future is dropped and recreated whenever a lane message wins
        /// the race. Implementations must be **cancellation-safe**: any work
        /// done before an internal `.await` point may be lost if the future
        /// is cancelled at that point. Hold intermediate state in `self` or
        /// `init` rather than in local variables across `.await` boundaries.
        fn on_external(
            &mut self,
            _context: &mut E,
            _init: &mut Self::Init,
        ) -> impl Future<Output = Option<Self::Ingress>> + Send {
            futures::future::pending()
        }

        /// Runs at the end of each iteration.
        fn postprocess(
            &mut self,
            _context: &mut E,
            _init: &mut Self::Init,
        ) -> impl Future<Output = ()> + Send {
            async {}
        }
    }

    /// Ask-response conversion trait for mailbox APIs.
    ///
    /// An ask type converts itself into the actor's ingress enum by embedding a
    /// oneshot response channel into the produced ingress message.
    pub trait Ask<I>: Send + 'static {
        /// Response type expected from the actor.
        type Response: Send + 'static;

        /// Convert this ask into an ingress value with a response sender.
        fn into_ingress(self, response: oneshot::Sender<Self::Response>) -> I;
    }

    /// Fire-and-forget conversion trait for mailbox APIs.
    ///
    /// Maps wrapper types into ingress without closure boxing.
    pub trait Tell<I>: Send + 'static {
        /// Convert this tell message into an ingress value.
        fn into_ingress(self) -> I;
    }
});
