use proc_macro2::Span;
use syn::{
    Attribute, Generics, Ident, Result, Token, Type, braced,
    parse::{Parse, ParseStream},
};

pub(crate) fn canonical_ident(ident: &Ident) -> String {
    let name = ident.to_string();
    name.strip_prefix("r#").unwrap_or(&name).to_string()
}

fn validate_item_name(ident: &Ident) -> Result<()> {
    let name = canonical_ident(ident);
    if name.chars().next().is_some_and(char::is_uppercase) && !name.contains('_') {
        return Ok(());
    }

    Err(syn::Error::new(
        ident.span(),
        "ingress item names must use UpperCamelCase",
    ))
}

fn reject_conditional_attributes(attrs: &[Attribute], owner: &str) -> Result<()> {
    for attr in attrs {
        if attr.path().is_ident("cfg") || attr.path().is_ident("cfg_attr") {
            return Err(syn::Error::new_spanned(
                attr,
                format!(
                    "conditional compilation is not supported on ingress {owner}; gate the entire ingress! invocation instead"
                ),
            ));
        }
    }
    Ok(())
}

fn validate_generic_parameters(generics: &Generics) -> Result<()> {
    for param in &generics.params {
        let attrs = match param {
            syn::GenericParam::Lifetime(param) => &param.attrs,
            syn::GenericParam::Type(param) => &param.attrs,
            syn::GenericParam::Const(param) => &param.attrs,
        };
        reject_conditional_attributes(attrs, "generic parameters")?;
        if let syn::GenericParam::Const(param) = param {
            let name = canonical_ident(&param.ident);
            if name.starts_with("__commonware_actor") {
                return Err(syn::Error::new(
                    param.ident.span(),
                    format!("`{name}` is reserved for bindings generated by ingress!"),
                ));
            }
        }
    }
    Ok(())
}

fn validate_field_generic_names(generics: &Generics, items: &[Item]) -> Result<()> {
    let const_params = generics
        .const_params()
        .map(|param| canonical_ident(&param.ident))
        .collect::<std::collections::HashSet<_>>();
    for field in items.iter().flat_map(|item| &item.fields) {
        let name = canonical_ident(&field.name);
        if const_params.contains(&name) {
            return Err(syn::Error::new(
                field.name.span(),
                format!("field `{name}` conflicts with a const generic parameter"),
            ));
        }
    }
    Ok(())
}

mod kw {
    syn::custom_keyword!(ask);
    syn::custom_keyword!(custom_policy);
    syn::custom_keyword!(internal);
    syn::custom_keyword!(read_write);
    syn::custom_keyword!(subscribe);
    syn::custom_keyword!(tell);
    syn::custom_keyword!(unreliable);
}

pub(crate) enum ItemKind {
    Internal,
    Tell,
    Request {
        response: Box<Type>,
        read_write: bool,
        await_response: bool,
    },
}

/// How a field annotated with `#[span]` is recorded on the enqueue span.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum SpanRecord {
    /// Record with the field's `Display` implementation (`#[span]`).
    Display,
    /// Record with the field's `Debug` implementation (`#[span(debug)]`).
    Debug,
}

pub(crate) struct Field {
    pub(crate) attrs: Vec<Attribute>,
    pub(crate) name: Ident,
    pub(crate) ty: Type,
    pub(crate) span_record: Option<SpanRecord>,
}

pub(crate) struct Item {
    pub(crate) attrs: Vec<Attribute>,
    pub(crate) name: Ident,
    pub(crate) fields: Vec<Field>,
    pub(crate) public_method: bool,
    pub(crate) kind: ItemKind,
}

pub(crate) struct Input {
    pub(crate) unreliable: bool,
    pub(crate) custom_policy: bool,
    pub(crate) mailbox: Ident,
    pub(crate) generics: Generics,
    pub(crate) items: Vec<Item>,
}

impl Parse for Field {
    fn parse(input: ParseStream<'_>) -> Result<Self> {
        let mut attrs = input.call(Attribute::parse_outer)?;
        let span_record = extract_span_record(&mut attrs)?;
        let name: Ident = input.parse()?;
        input.parse::<Token![:]>()?;
        let ty: Type = input.parse()?;
        Ok(Self {
            attrs,
            name,
            ty,
            span_record,
        })
    }
}

/// Remove any `#[span]` / `#[span(debug)]` marker from `attrs` and return
/// the requested recording mode. Remaining attributes pass through to the
/// generated enum variant field.
fn extract_span_record(attrs: &mut Vec<Attribute>) -> Result<Option<SpanRecord>> {
    let mut record = None;
    let mut kept = Vec::with_capacity(attrs.len());
    for attr in attrs.drain(..) {
        if !attr.path().is_ident("span") {
            kept.push(attr);
            continue;
        }
        if record.is_some() {
            return Err(syn::Error::new_spanned(
                &attr,
                "duplicate `#[span]` attribute",
            ));
        }
        record = Some(match &attr.meta {
            syn::Meta::Path(_) => SpanRecord::Display,
            syn::Meta::List(list) => {
                let mode: Ident = list.parse_args()?;
                if mode == "debug" {
                    SpanRecord::Debug
                } else if mode == "display" {
                    SpanRecord::Display
                } else {
                    return Err(syn::Error::new(
                        mode.span(),
                        "expected `#[span]`, `#[span(display)]`, or `#[span(debug)]`",
                    ));
                }
            }
            syn::Meta::NameValue(_) => {
                return Err(syn::Error::new_spanned(
                    &attr,
                    "expected `#[span]`, `#[span(display)]`, or `#[span(debug)]`",
                ));
            }
        });
    }
    *attrs = kept;
    Ok(record)
}

/// Parse the optional `unreliable` and `custom_policy` header flags.
///
/// The flags compose: `unreliable custom_policy,` selects an unreliable
/// mailbox with a hand-written `UnreliablePolicy` implementation.
fn parse_header_flags(input: ParseStream<'_>) -> Result<(bool, bool)> {
    let unreliable = if input.peek(kw::unreliable) {
        input.parse::<kw::unreliable>()?;
        true
    } else {
        false
    };

    let custom_policy = if input.peek(kw::custom_policy) {
        input.parse::<kw::custom_policy>()?;
        true
    } else {
        false
    };

    if unreliable || custom_policy {
        input.parse::<Token![,]>()?;
    }

    Ok((unreliable, custom_policy))
}

fn parse_fields(input: ParseStream<'_>) -> Result<Vec<Field>> {
    if !input.peek(syn::token::Brace) {
        return Ok(Vec::new());
    }

    let content;
    braced!(content in input);
    let fields: Vec<_> = content
        .parse_terminated(Field::parse, Token![,])?
        .into_iter()
        .collect();
    validate_fields(&fields)?;
    Ok(fields)
}

fn validate_fields(fields: &[Field]) -> Result<()> {
    let mut seen = std::collections::HashSet::new();
    for field in fields {
        reject_conditional_attributes(&field.attrs, "fields")?;
        let name = canonical_ident(&field.name);
        if !seen.insert(name.clone()) {
            return Err(syn::Error::new(
                field.name.span(),
                format!("duplicate field name `{name}`"),
            ));
        }
        if name == "response" || name == "span" || name.starts_with("__commonware_actor") {
            return Err(syn::Error::new(
                field.name.span(),
                format!("`{name}` is reserved for fields and bindings generated by ingress!"),
            ));
        }
    }
    Ok(())
}

fn parse_item(input: ParseStream<'_>) -> Result<Item> {
    let attrs = input.call(Attribute::parse_outer)?;
    reject_conditional_attributes(&attrs, "items")?;
    let public_method = if input.peek(Token![pub]) {
        input.parse::<Token![pub]>()?;
        true
    } else {
        false
    };

    let kind = if input.peek(kw::internal) {
        if public_method {
            return Err(input.error("`internal` items cannot be public"));
        }
        input.parse::<kw::internal>()?;
        ItemKind::Internal
    } else if input.peek(kw::tell) {
        input.parse::<kw::tell>()?;
        ItemKind::Tell
    } else if input.peek(kw::ask) || input.peek(kw::subscribe) {
        let await_response = if input.peek(kw::ask) {
            input.parse::<kw::ask>()?;
            true
        } else {
            input.parse::<kw::subscribe>()?;
            false
        };
        let read_write = if input.peek(kw::read_write) {
            input.parse::<kw::read_write>()?;
            true
        } else {
            false
        };
        let name: Ident = input.parse()?;
        validate_item_name(&name)?;
        let fields = parse_fields(input)?;
        input.parse::<Token![->]>()?;
        let response: Type = input.parse()?;
        input.parse::<Token![;]>()?;
        return Ok(Item {
            attrs,
            name,
            fields,
            public_method,
            kind: ItemKind::Request {
                response: Box::new(response),
                read_write,
                await_response,
            },
        });
    } else {
        return Err(input.error("expected `internal`, `tell`, `ask`, or `subscribe` item"));
    };

    let name: Ident = input.parse()?;
    validate_item_name(&name)?;
    let fields = parse_fields(input)?;
    input.parse::<Token![;]>()?;

    Ok(Item {
        attrs,
        name,
        fields,
        public_method,
        kind,
    })
}

impl Parse for Input {
    fn parse(input: ParseStream<'_>) -> Result<Self> {
        let (unreliable, custom_policy) = parse_header_flags(input)?;

        let has_header = !(input.peek(kw::internal)
            || input.peek(kw::tell)
            || input.peek(kw::ask)
            || input.peek(kw::subscribe)
            || input.peek(Token![pub])
            || input.peek(Token![#]));
        let (mailbox, generics) = if has_header {
            let mailbox: Ident = input.parse()?;
            let generics = if input.peek(Token![<]) {
                input.parse()?
            } else {
                Generics::default()
            };
            validate_generic_parameters(&generics)?;
            if input.peek(Token![where]) {
                return Err(input.error("where clauses are not supported on ingress! generics; use inline bounds like `<P: Trait>` instead"));
            }
            input.parse::<Token![,]>()?;
            (mailbox, generics)
        } else {
            (
                Ident::new("Mailbox", Span::call_site()),
                Generics::default(),
            )
        };

        let mut items = Vec::new();
        while !input.is_empty() {
            items.push(parse_item(input)?);
        }
        validate_field_generic_names(&generics, &items)?;

        let mut seen = std::collections::HashSet::new();
        for item in &items {
            let name = canonical_ident(&item.name);
            if !seen.insert(name.clone()) {
                return Err(syn::Error::new(
                    item.name.span(),
                    format!("duplicate item name `{name}`"),
                ));
            }
        }

        if items.is_empty() {
            return Err(syn::Error::new(
                mailbox.span(),
                "ingress! requires at least one `internal`, `tell`, `ask`, or `subscribe` item",
            ));
        }

        Ok(Self {
            unreliable,
            custom_policy,
            mailbox,
            generics,
            items,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_custom_policy_header() {
        let input: Input = syn::parse_str(
            r#"
            custom_policy,
            ApiMailbox,
            pub tell Ping;
            "#,
        )
        .unwrap();

        assert!(!input.unreliable);
        assert!(input.custom_policy);
        assert_eq!(input.mailbox, "ApiMailbox");
        assert_eq!(input.items.len(), 1);
    }

    #[test]
    fn parses_unreliable_header() {
        let input: Input = syn::parse_str(
            r#"
            unreliable,
            ApiMailbox,
            pub ask Get -> u64;
            "#,
        )
        .unwrap();

        assert!(input.unreliable);
        assert!(!input.custom_policy);
        assert_eq!(input.items.len(), 1);
    }

    #[test]
    fn parses_unreliable_custom_policy_header() {
        let input: Input = syn::parse_str(
            r#"
            unreliable custom_policy,
            ApiMailbox,
            pub tell Ping;
            "#,
        )
        .unwrap();

        assert!(input.unreliable);
        assert!(input.custom_policy);
    }

    #[test]
    fn parses_span_field_attributes() {
        let input: Input = syn::parse_str(
            r#"
            ApiMailbox,
            pub tell Vote { #[span] view: u64, #[span(debug)] digest: u64, payload: u64 };
            "#,
        )
        .unwrap();

        let fields = &input.items[0].fields;
        assert_eq!(fields[0].span_record, Some(SpanRecord::Display));
        assert_eq!(fields[1].span_record, Some(SpanRecord::Debug));
        assert_eq!(fields[2].span_record, None);
        // The marker is stripped so it never reaches the generated variant.
        assert!(fields.iter().all(|field| field.attrs.is_empty()));
    }

    #[test]
    fn parses_read_write_subscribe() {
        let input: Input = syn::parse_str(
            r#"
            ApiMailbox,
            subscribe read_write Next -> u64;
            "#,
        )
        .unwrap();

        assert!(matches!(
            input.items[0].kind,
            ItemKind::Request {
                read_write: true,
                await_response: false,
                ..
            }
        ));
    }

    #[test]
    fn parses_internal_item() {
        let input: Input = syn::parse_str(
            r#"
            ApiMailbox,
            internal Tick {
                /// Deadline that fired.
                deadline: u64
            };
            "#,
        )
        .unwrap();

        assert!(matches!(input.items[0].kind, ItemKind::Internal));
        assert_eq!(input.items[0].name, "Tick");
        assert_eq!(input.items[0].fields.len(), 1);
        assert!(!input.items[0].public_method);
    }

    #[test]
    fn rejects_public_internal_item() {
        let result = syn::parse_str::<Input>(
            r#"
            ApiMailbox,
            pub internal Tick;
            "#,
        );
        let err = result
            .err()
            .expect("public internal item should fail")
            .to_string();

        assert!(err.contains("`internal` items cannot be public"), "{err}");
    }

    #[test]
    fn parses_generic_defaults_for_lowering_validation() {
        let input: Input = syn::parse_str(
            r#"
            ApiMailbox<T = u64>,
            tell Ping { value: T };
            "#,
        )
        .unwrap();

        assert_eq!(input.generics.params.len(), 1);
    }

    #[test]
    fn rejects_unknown_span_mode() {
        let result = syn::parse_str::<Input>(
            r#"
            ApiMailbox,
            pub tell Vote { #[span(pretty)] view: u64 };
            "#,
        );
        let Err(err) = result else {
            panic!("unknown span mode was accepted");
        };

        assert!(err.to_string().contains("expected"));
    }

    #[test]
    fn rejects_duplicate_span_attribute() {
        let result = syn::parse_str::<Input>(
            r#"
            ApiMailbox,
            pub tell Vote { #[span] #[span(debug)] view: u64 };
            "#,
        );
        let Err(err) = result else {
            panic!("duplicate span attribute was accepted");
        };

        assert!(err.to_string().contains("duplicate"));
    }

    #[test]
    fn rejects_reserved_span_field() {
        let result = syn::parse_str::<Input>(
            r#"
            ApiMailbox,
            pub tell Ping { span: u64 };
            "#,
        );
        let Err(err) = result else {
            panic!("reserved span field was accepted");
        };

        assert!(err.to_string().contains("reserved"));
    }

    #[test]
    fn rejects_reserved_binding_prefix() {
        let result = syn::parse_str::<Input>(
            r#"
            ApiMailbox,
            pub tell Ping { __commonware_actor_value: u64 };
            "#,
        );
        let Err(err) = result else {
            panic!("reserved binding prefix was accepted");
        };

        assert!(err.to_string().contains("reserved"));
    }

    #[test]
    fn rejects_raw_reserved_field() {
        let result = syn::parse_str::<Input>(
            r#"
            ApiMailbox,
            pub ask Get { r#response: u64 } -> u64;
            "#,
        );
        let Err(err) = result else {
            panic!("raw reserved field was accepted");
        };

        assert!(err.to_string().contains("reserved"), "{err}");
    }

    #[test]
    fn rejects_duplicate_field_names() {
        let result = syn::parse_str::<Input>(
            r#"
            ApiMailbox,
            pub tell Ping { value: u64, value: u64 };
            "#,
        );
        let Err(err) = result else {
            panic!("duplicate field name was accepted");
        };

        assert!(err.to_string().contains("duplicate field name"), "{err}");
    }

    #[test]
    fn rejects_conditional_item_attribute() {
        let result = syn::parse_str::<Input>(
            r#"
            ApiMailbox,
            #[cfg(any())]
            pub tell Ping;
            "#,
        );
        let Err(err) = result else {
            panic!("conditional item attribute was accepted");
        };

        assert!(err.to_string().contains("conditional compilation"), "{err}");
    }

    #[test]
    fn rejects_conditional_field_attribute() {
        let result = syn::parse_str::<Input>(
            r#"
            ApiMailbox,
            pub tell Ping { #[cfg(any())] value: u64 };
            "#,
        );
        let Err(err) = result else {
            panic!("conditional field attribute was accepted");
        };

        assert!(err.to_string().contains("conditional compilation"), "{err}");
    }

    #[test]
    fn rejects_conditional_generic_attribute() {
        let result = syn::parse_str::<Input>(
            r#"
            ApiMailbox<#[cfg(any())] T>,
            pub tell Ping { value: T };
            "#,
        );
        let Err(err) = result else {
            panic!("conditional generic attribute was accepted");
        };

        assert!(err.to_string().contains("conditional compilation"), "{err}");
    }

    #[test]
    fn rejects_reserved_const_generic_binding() {
        let result = syn::parse_str::<Input>(
            r#"
            ApiMailbox<const __commonware_actor_span: usize>,
            pub tell Ping { value: [u8; __commonware_actor_span] };
            "#,
        );
        let Err(err) = result else {
            panic!("reserved const generic binding was accepted");
        };

        assert!(err.to_string().contains("reserved"), "{err}");
    }

    #[test]
    fn rejects_non_camel_item_name() {
        let result = syn::parse_str::<Input>(
            r#"
            ApiMailbox,
            pub tell r#type;
            "#,
        );
        let Err(err) = result else {
            panic!("non-camel item name was accepted");
        };

        assert!(err.to_string().contains("UpperCamelCase"), "{err}");
    }

    #[test]
    fn rejects_field_const_generic_binding_collision() {
        let result = syn::parse_str::<Input>(
            r#"
            ApiMailbox<const value: usize>,
            pub tell Store { value: usize };
            "#,
        );
        let Err(err) = result else {
            panic!("field and const generic binding collision was accepted");
        };

        assert!(err.to_string().contains("const generic"), "{err}");
    }
}
