[package]
name = "commonware-simulator"
edition = "2021"
publish = true
version = "0.0.56"
license = "MIT OR Apache-2.0"
description = "TBA"
readme = "README.md"
homepage = "https://commonware.xyz"
repository = "https://github.com/commonwarexyz/monorepo/tree/main/examples/simulator"
documentation = "https://docs.rs/commonware-simulator"

[dependencies]
commonware-cryptography = { workspace = true }
commonware-macros = { workspace = true }
commonware-p2p = { workspace = true }
commonware-runtime = { workspace = true }
commonware-utils = { workspace = true }
commonware-consensus = { workspace = true }
commonware-storage = { workspace = true }
bytes = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
clap = { workspace = true }
prometheus-client = { workspace = true }
governor = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "json"] }
chrono = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "commonware-simulator"
bench = false
