["commonware_consensus::aggregation::types::tests::conformance::CodecConformance<Ack<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "9fa6d9ec4dd41102c3fefd9c35e65644628824c436ddfc3988bc9392c2a9822f"

["commonware_consensus::aggregation::types::tests::conformance::CodecConformance<Activity<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "e1c7e15c3b28ad5f9820758884c8230359737f74a864bac6e36434444292647c"

["commonware_consensus::aggregation::types::tests::conformance::CodecConformance<Certificate<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "848672b1e4a9c0f19a3cf8cb74c509f94ffb06ddd42c077600eaae8019ec16b1"

["commonware_consensus::aggregation::types::tests::conformance::CodecConformance<Item<Sha256Digest>>"]
n_cases = 65536
hash = "55b287b5530fc9ba77c45ec5030ada38f86b2ddf66a1595fde27d4699667b1a3"

["commonware_consensus::aggregation::types::tests::conformance::CodecConformance<TipAck<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "9e91d17d9f43a6986ad15008464dc3d44316e345b6da4cdad35930f7deb0886b"

["commonware_consensus::marshal::coding::types::test::conformance::CodecConformance<Shard<ReedSolomon<Sha256>,Sha256>>"]
n_cases = 65536
hash = "e53b4b684f0344590427aae976d298e3b6fd2b08ef46ff2cad5def04b4f7690b"

["commonware_consensus::marshal::resolver::handler::tests::conformance::CodecConformance<Request<D>>"]
n_cases = 65536
hash = "481cd68f2e6452c0dda512c75d74ddd2e19ac6c9fb19c642c1a152a0d830c1b2"

["commonware_consensus::ordered_broadcast::types::tests::conformance::CodecConformance<Ack<PublicKey,Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "e240d5459833a95f8088664d7444f187fe0f9f833bf458a2ab31163c87145d25"

["commonware_consensus::ordered_broadcast::types::tests::conformance::CodecConformance<Activity<PublicKey,Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "d004023d2dd45c52ccb6756492173e69f5e7ee925fe07a588f65be0cd7037fc8"

["commonware_consensus::ordered_broadcast::types::tests::conformance::CodecConformance<Chunk<PublicKey,Sha256Digest>>"]
n_cases = 65536
hash = "43624c9e7ce355baebf32ab6e76db21cb5bf08005396ba43dae96b3a86f3a535"

["commonware_consensus::ordered_broadcast::types::tests::conformance::CodecConformance<Lock<PublicKey,Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "7b930679f48a293e8c61e89f1fc0d6aae996eff5fd551d63dc5cece33c285164"

["commonware_consensus::ordered_broadcast::types::tests::conformance::CodecConformance<Node<PublicKey,Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "e3693e1a4482c868466e7c2cac4b583c38b9c93543310d14c70f6f506693d7f4"

["commonware_consensus::ordered_broadcast::types::tests::conformance::CodecConformance<Parent<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "04c82ac8f305f88da3002186dbf44aa8c828f5d4a1c8a4cde5ac4d1557d99ebf"

["commonware_consensus::ordered_broadcast::types::tests::conformance::CodecConformance<Proposal<PublicKey,Sha256Digest>>"]
n_cases = 65536
hash = "6fc6f17d8734a14fb841a8acc1a39cda7519bdd025700663e260d3b000c9c5c6"

["commonware_consensus::simplex::elector::tests::conformance::RandomSelectLeaderConformance"]
n_cases = 512
hash = "6aac342083d9ad1e9429eb316ee707eb51bd4c5cc223261808c6d0163c5e3c9d"

["commonware_consensus::simplex::elector::tests::conformance::RoundRobinShuffleConformance"]
n_cases = 512
hash = "d6232310a3adc5cc8bf0767d095251f25211f165419372a5fe6b4ed7b06dd765"

["commonware_consensus::simplex::scheme::bls12381_threshold::vrf::tests::conformance::CodecConformance<Certificate<MinSig>>"]
n_cases = 65536
hash = "1397193af32c9f3d5c0eca80fbfa741ca588e189074e4ab4b9c60d97673fdfb8"

["commonware_consensus::simplex::scheme::bls12381_threshold::vrf::tests::conformance::CodecConformance<Seed<MinSig>>"]
n_cases = 65536
hash = "9d21dec64f3333d7eb9455dca51657e28db8358eee173dbe0a86f718138d2342"

["commonware_consensus::simplex::scheme::bls12381_threshold::vrf::tests::conformance::CodecConformance<Signature<MinSig>>"]
n_cases = 65536
hash = "1397193af32c9f3d5c0eca80fbfa741ca588e189074e4ab4b9c60d97673fdfb8"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Activity<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "1e25c6dda2b7da4327e5742b1a8b67d68ebd9c34080c8f877ffbd44f38848098"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Artifact<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "f51dd822c99288f77f1557eed3a8c270affba4c484dbb2ef60ac3415f2cc8d03"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Backfiller<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "3147f69e8e0b4d91927852e19e61f4e0a02bc46fd7ccd97e74d8b859f9f25a4c"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Certificate<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "7ae35fb13f2aa8fb3a13d6fc32a658a6cdd3fdfebd58f2dcccdbbd16dba9910d"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<ConflictingFinalize<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "95bb782e73490739bee2dfd0b898a824e450bdb3feeb1e71d9d4a90c6523f0e1"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<ConflictingNotarize<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "95bb782e73490739bee2dfd0b898a824e450bdb3feeb1e71d9d4a90c6523f0e1"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Context<Sha256Digest,PublicKey>>"]
n_cases = 65536
hash = "5227154cc56a996363e26b0e006515b97a83a8c7ba580b0b5e760132fc620f4d"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Finalization<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "eed77fa1bd1ad359dff320a2cdbbe9e1f116dde2feaced367135f748ca5e32d9"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Finalize<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "5c6429b2c96c456803271ebcb0be19ca84a040d75b4076378ec0a587bbc19356"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Notarization<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "eed77fa1bd1ad359dff320a2cdbbe9e1f116dde2feaced367135f748ca5e32d9"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Notarize<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "5c6429b2c96c456803271ebcb0be19ca84a040d75b4076378ec0a587bbc19356"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Nullification<Scheme>>"]
n_cases = 65536
hash = "ada525d25f10f06d1abbb5956ee33d65ac29038177f637adc4f20f7298831d8d"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Nullify<Scheme>>"]
n_cases = 65536
hash = "d7b8fe05e61a3c0619f02cab3d609a2f96790b8ac70eadfbda7db60b7e785342"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<NullifyFinalize<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "2c682c9ee30ccc8393e5b5e5f38c54ed1a718b6d1a74a4ef22e1bf845dc9ba12"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Proposal<Sha256Digest>>"]
n_cases = 65536
hash = "4ba1f5b5cbf271ae45313d8ac48b05c010166ca743334b9b8051a4a610c58fe7"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Request>"]
n_cases = 65536
hash = "6f852b6ad6e5dd77804d80781b03c808e186e7e7c5611752f124c625c5c3ee17"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Response<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "b70a7b65f0d26e695bacfd483d7ed27bd4b78c16811d91227e049f43fbf534f1"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Vote<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "c69ffde4235a13b6a6b70974da030c8c57863d1dae19484f6bc74269528d9683"

["commonware_consensus::types::tests::conformance::CodecConformance<Commitment>"]
n_cases = 65536
hash = "4cc05ec53b515415070f3634ad2b56677c2a938f596ffc99f7909f24e06a8c99"

["commonware_consensus::types::tests::conformance::CodecConformance<Epoch>"]
n_cases = 65536
hash = "56ab85978136cb50f12ea89c8d25ce24451788172fe9d3d3c063f7ae6342d279"

["commonware_consensus::types::tests::conformance::CodecConformance<Height>"]
n_cases = 65536
hash = "56ab85978136cb50f12ea89c8d25ce24451788172fe9d3d3c063f7ae6342d279"

["commonware_consensus::types::tests::conformance::CodecConformance<Round>"]
n_cases = 65536
hash = "d8ccba2653a5a2e5e317f0f365edbfc4845e3dc4325daefe0b43ca75920a654c"

["commonware_consensus::types::tests::conformance::CodecConformance<View>"]
n_cases = 65536
hash = "56ab85978136cb50f12ea89c8d25ce24451788172fe9d3d3c063f7ae6342d279"
