{
 "title": "Flood",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Name", "query": { "query": "label_values(deployer_name)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (deployer_name,deployer_ip) (1 - rate(node_cpu_seconds_total{mode=\"idle\", deployer_name=~\"$Name\"}[1m])) * 100",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{deployer_name=~\"$Name\"} - node_memory_MemFree_bytes{deployer_name=~\"$Name\"} - node_memory_Buffers_bytes{deployer_name=~\"$Name\"} - node_memory_Cached_bytes{deployer_name=~\"$Name\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{deployer_name=~\"$Name\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Inbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(runtime_inbound_bandwidth_total{deployer_name=~\"$Name\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Outbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(runtime_outbound_bandwidth_total{deployer_name=~\"$Name\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum by(deployer_name, deployer_ip) (runtime_tasks_running{deployer_name=~\"$Name\"})",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "network_spawner_connections{deployer_name=~\"$Name\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Tracked Peers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "network_tracker_tracked{deployer_name=~\"$Name\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Dial Attempts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "network_dialer_attempts_total{deployer_name=~\"$Name\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Messages Sent (Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "irate(flood_sender_messages_total{deployer_name=~\"$Name\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Sent Messages Dropped (Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "sum(irate(network_router_messages_dropped_total{deployer_name=~\"$Name\"}[1m])) by (deployer_name, deployer_ip)",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Messages Received (Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "irate(flood_receiver_messages_total{deployer_name=~\"$Name\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "flamegraph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "labelSelector": "process_cpu{deployer_name=~\"${Name:pipe}\"}",
     "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "limit": 20,
     "query": "{resource.service.name =~ \"$Name\" && trace:rootName != \"\" && span:status != unset }",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/log/binary.log\", deployer_name=~\"$Name\"} | json | line_format ` [{{.detected_level}}] {{.target}} {{.fields_message}}`"
    }
   ]
  }
 ]
}