//! Ed25519 signing keys, signatures, and verification.
//!
//! # Validation criteria (ZIP215)
//!
//! Signature validation follows [ZIP215], the criteria that make Ed25519 safe for consensus:
//!
//! - The point encodings of the verifying key `A` and the signature component `R` are accepted
//!   even when non-canonical (a `y` coordinate at or above `p`, or a negative-zero `x`), as long
//!   as they decode to a curve point.
//! - The scalar component `s` must be canonical (`s < L`), ruling out signature malleability.
//! - The verification equation is cofactored: `[8](s·B - R - H(R || A || M)·A) == identity`.
//!
//! [`VerifyingKey::verify`] and [`BatchVerifier::verify`] apply the same criteria.
//! A non-empty batch of at most `u32::MAX` signatures is always accepted when every signature
//! verifies individually. Because batch verification checks a randomized linear combination, an
//! invalid batch may be accepted with probability about `2^-128`. See [this post] for why these
//! criteria matter.
//! [`StrictVerifyingKey`] additionally requires a canonical, non-identity point in the prime-order
//! subgroup, making it suitable for identities whose signatures must demonstrate secret-key
//! knowledge.
//!
//! [this post]: https://hdevalence.ca/blog/2020-10-04-its-25519am
//! [ZIP215]: https://zips.z.cash/zip-0215

mod core;

use self::core::Scalar;
use crate::curve::{G, GAffine};
use ::core::{
    fmt::{self, Debug, Display},
    hash::{Hash, Hasher},
    ops::Deref,
};
#[cfg(not(feature = "std"))]
use alloc::vec::Vec;
use bytes::{Buf, BufMut};
use commonware_codec::{FixedSize, Read, Write};
use commonware_formatting::Hex;
use commonware_math::algebra::Random;
use commonware_parallel::Strategy;
use commonware_utils::{Array, Span, union_unique};
use rand_core::CryptoRng;
use sha2::{
    Digest,
    digest::{FixedOutput, Update},
};
use zeroize::{ZeroizeOnDrop, Zeroizing};

/// The little-endian integer order of the subgroup generated by the Ed25519 basepoint.
const PRIME_ORDER: [u8; 32] = [
    0xed, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58, 0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x10,
];

/// Multiplies by the unreduced subgroup order, which cannot be represented by a modulo-order
/// scalar because it would reduce to zero.
fn prime_order_product(point: G) -> G {
    point.scalar_mul(
        (0..256)
            .rev()
            .map(|i| PRIME_ORDER[i / 8] >> (i % 8) & 1 == 1),
    )
}

/// An Ed25519 signing key.
///
/// Secret material is zeroized when the key is dropped.
#[derive(ZeroizeOnDrop)]
pub struct SigningKey {
    /// When serializing, we want to just write the seed, so we keep it around.
    seed: [u8; 32],
    /// The private prefix we use to derive a deterministic nonce for each message.
    prefix: [u8; 32],
    /// The pruned secret scalar, reduced modulo the basepoint order.
    scalar: Scalar,
    /// The verifying key derived from the secret scalar.
    #[zeroize(skip)]
    verifying_key: VerifyingKey,
}

impl Clone for SigningKey {
    fn clone(&self) -> Self {
        Self {
            seed: self.seed,
            prefix: self.prefix,
            scalar: self.scalar,
            verifying_key: self.verifying_key.clone(),
        }
    }
}

// Private methods.
impl SigningKey {
    fn from_seed(seed: [u8; 32]) -> Self {
        let seed = Zeroizing::new(seed);
        // Following: https://www.rfc-editor.org/rfc/rfc8032.html#section-5.1.5.
        // The first half becomes our secret scalar material, while the second half
        // is the private prefix we use to derive deterministic nonces.
        let h: Zeroizing<[u8; 64]> =
            Zeroizing::new(sha2::Sha512::new().chain(&seed[..]).finalize_fixed().into());
        let mut scalar_le_bytes: Zeroizing<[u8; 32]> =
            Zeroizing::new(h[..32].try_into().expect("h is 64 bytes"));
        let prefix: Zeroizing<[u8; 32]> =
            Zeroizing::new(h[32..].try_into().expect("h is 64 bytes"));
        // We want the integer represented by these little-endian bytes to be a
        // multiple of the curve's cofactor, 8, so we "clamp" it by zeroing its
        // three least-significant bits. This is part of Ed25519 key derivation too,
        // not just key exchange.
        scalar_le_bytes[0] &= 0b1111_1000;
        // We also want the scalar to fit in 255 bits, so we unset bit 255. This
        // doesn't put it below L; scalar-field arithmetic still has to reduce it
        // modulo L.
        scalar_le_bytes[31] &= 0b0111_1111;
        // The RFC also requires us to set bit 254, giving the scalar a fixed 255-bit
        // length. Among other things, this forces scalar-multiplication implementations
        // that start at the highest set bit to use the same number of iterations. It
        // doesn't make a variable-time implementation safe by itself.
        scalar_le_bytes[31] |= 0b0100_0000;
        let mut wide_scalar = Zeroizing::new([0u8; 64]);
        wide_scalar[..32].copy_from_slice(&scalar_le_bytes[..]);
        let scalar = Zeroizing::new(Scalar::from_bytes_mod_order_wide(&wide_scalar));
        let point = GAffine::BASEPOINT
            .to_extended()
            .scalar_mul_secret(&scalar_le_bytes);
        let verifying_key = VerifyingKey {
            bytes: core::VerifyingKeyBytes::new(point.to_bytes()),
            point: Some(point),
        };

        Self {
            seed: *seed,
            prefix: *prefix,
            scalar: *scalar,
            verifying_key,
        }
    }

    fn sign_message(&self, msg: &[u8]) -> Signature {
        let nonce_digest: Zeroizing<[u8; 64]> = Zeroizing::new(
            sha2::Sha512::new()
                .chain(self.prefix.as_slice())
                .chain(msg)
                .finalize_fixed()
                .into(),
        );
        let nonce = Zeroizing::new(Scalar::from_bytes_mod_order_wide(&nonce_digest));
        let nonce_bytes = Zeroizing::new(nonce.to_bytes());
        let r_bytes = GAffine::BASEPOINT
            .to_extended()
            .scalar_mul_secret(&nonce_bytes)
            .to_bytes();

        let challenge_digest: [u8; 64] = sha2::Sha512::new()
            .chain(r_bytes)
            .chain(self.verifying_key.bytes.as_bytes())
            .chain(msg)
            .finalize_fixed()
            .into();
        let challenge = Scalar::from_bytes_mod_order_wide(&challenge_digest);
        let challenge_scalar = Zeroizing::new(challenge.mul_mod_l(&self.scalar));
        let s_bytes = nonce.add_mod_l(&challenge_scalar).to_bytes();

        let mut bytes = [0u8; 64];
        bytes[..32].copy_from_slice(&r_bytes);
        bytes[32..].copy_from_slice(&s_bytes);
        Signature { bytes }
    }
}

impl Random for SigningKey {
    fn random(mut rng: impl rand_core::CryptoRng) -> Self {
        let mut seed = Zeroizing::new([0u8; 32]);
        rng.fill_bytes(&mut seed[..]);
        Self::from_seed(*seed)
    }
}

impl Write for SigningKey {
    fn write(&self, buf: &mut impl BufMut) {
        self.seed.write(buf);
    }
}

impl FixedSize for SigningKey {
    const SIZE: usize = 32;
}

impl Read for SigningKey {
    type Cfg = ();

    fn read_cfg(buf: &mut impl Buf, cfg: &Self::Cfg) -> Result<Self, commonware_codec::Error> {
        let seed = Zeroizing::new(<[u8; Self::SIZE]>::read_cfg(buf, cfg)?);
        Ok(Self::from_seed(*seed))
    }
}

#[cfg(feature = "arbitrary")]
impl arbitrary::Arbitrary<'_> for SigningKey {
    fn arbitrary(u: &mut arbitrary::Unstructured<'_>) -> arbitrary::Result<Self> {
        let seed: Zeroizing<[u8; Self::SIZE]> = Zeroizing::new(u.arbitrary()?);
        Ok(Self::from_seed(*seed))
    }
}

// Public methods.
impl SigningKey {
    /// The verifying key associated with this signing key.
    ///
    /// Signatures produced by this signing key can be verified using this public key.
    pub fn verifying_key(&self) -> VerifyingKey {
        self.verifying_key.clone()
    }

    /// The strict identity key associated with this signing key.
    pub fn strict_verifying_key(&self) -> StrictVerifyingKey {
        StrictVerifyingKey {
            zip215: self.verifying_key.clone(),
        }
    }

    /// Signs a namespaced message using deterministic Ed25519.
    ///
    /// The namespace is committed to the signature to prevent its reuse in another context.
    /// Signing is deterministic per [RFC 8032]: the nonce is derived from the key and the
    /// message, so signing the same message twice yields the same signature and no randomness
    /// is consumed.
    ///
    /// [RFC 8032]: https://www.rfc-editor.org/rfc/rfc8032
    pub fn sign(&self, namespace: &[u8], msg: &[u8]) -> Signature {
        let msg = union_unique(namespace, msg);
        self.sign_message(&msg)
    }

    /// Signs an unframed message for raw Ed25519 test-vector checks.
    #[cfg(test)]
    pub(crate) fn sign_raw(&self, msg: &[u8]) -> Signature {
        self.sign_message(msg)
    }
}

/// A public key used to check signatures.
#[derive(Clone)]
pub struct VerifyingKey {
    /// The encoded point.
    ///
    /// When deserializing, we just have the bytes, deferring parsing of them until
    /// signature verification, so that we can more efficiently parse them in batch.
    bytes: core::VerifyingKeyBytes,
    /// If available, the point associated with these bytes.
    point: Option<G>,
}

impl PartialEq for VerifyingKey {
    fn eq(&self, other: &Self) -> bool {
        self.bytes == other.bytes
    }
}

impl Eq for VerifyingKey {}

impl PartialOrd for VerifyingKey {
    fn partial_cmp(&self, other: &Self) -> Option<::core::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for VerifyingKey {
    fn cmp(&self, other: &Self) -> ::core::cmp::Ordering {
        self.bytes.cmp(&other.bytes)
    }
}

impl Hash for VerifyingKey {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.bytes.hash(state);
    }
}

impl Debug for VerifyingKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", Hex(self.bytes.as_bytes()))
    }
}

impl Display for VerifyingKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", Hex(self.bytes.as_bytes()))
    }
}

impl AsRef<[u8]> for VerifyingKey {
    fn as_ref(&self) -> &[u8] {
        self.bytes.as_bytes()
    }
}

impl Write for VerifyingKey {
    fn write(&self, buf: &mut impl BufMut) {
        self.bytes.as_bytes().write(buf);
    }
}

impl FixedSize for VerifyingKey {
    const SIZE: usize = 32;
}

impl Read for VerifyingKey {
    type Cfg = ();

    fn read_cfg(buf: &mut impl Buf, cfg: &Self::Cfg) -> Result<Self, commonware_codec::Error> {
        Ok(Self {
            bytes: core::VerifyingKeyBytes::new(<[u8; Self::SIZE]>::read_cfg(buf, cfg)?),
            point: None,
        })
    }
}

#[cfg(feature = "arbitrary")]
impl arbitrary::Arbitrary<'_> for VerifyingKey {
    fn arbitrary(u: &mut arbitrary::Unstructured<'_>) -> arbitrary::Result<Self> {
        Ok(Self {
            bytes: core::VerifyingKeyBytes::new(u.arbitrary()?),
            point: None,
        })
    }
}

impl VerifyingKey {
    fn verify_message(&self, msg: &[u8], sig: &Signature) -> bool {
        let r_bytes: [u8; 32] = sig.bytes[..32].try_into().expect("signature is 64 bytes");
        let s_bytes: [u8; 32] = sig.bytes[32..].try_into().expect("signature is 64 bytes");
        let Some(s) = Scalar::from_canonical_bytes(&s_bytes) else {
            return false;
        };
        let Some(r) = GAffine::decompress(&r_bytes) else {
            return false;
        };
        let a = match self.point {
            Some(point) => point,
            None => {
                let Some(point) = GAffine::decompress(self.bytes.as_bytes()) else {
                    return false;
                };
                point.to_extended()
            }
        };

        let digest: [u8; 64] = sha2::Sha512::new()
            .chain(r_bytes)
            .chain(self.bytes.as_bytes())
            .chain(msg)
            .finalize_fixed()
            .into();
        let k = Scalar::from_bytes_mod_order_wide(&digest);

        let sb = GAffine::BASEPOINT.to_extended().scalar_mul(s.bits_be());
        let ka = a.scalar_mul(k.bits_be());
        sb.add(ka.add_mixed(r).negate())
            .mul_by_cofactor()
            .is_identity()
    }
}

// Public methods.
impl VerifyingKey {
    /// Verifies `sig` over the namespaced message, per the [module's validation
    /// criteria](self).
    #[must_use]
    pub fn verify(&self, namespace: &[u8], msg: &[u8], sig: &Signature) -> bool {
        let msg = union_unique(namespace, msg);
        self.verify_message(&msg, sig)
    }

    /// Verifies an unframed message for raw Ed25519 test-vector checks.
    #[cfg(test)]
    pub(crate) fn verify_raw(&self, msg: &[u8], sig: &Signature) -> bool {
        self.verify_message(msg, sig)
    }
}

/// A canonical non-identity point in Ed25519's prime-order subgroup.
///
/// Decoding validates the complete identity domain once. Signature verification then applies the
/// module's ZIP215 equation to the validated point.
#[derive(Clone, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct StrictVerifyingKey {
    zip215: VerifyingKey,
}

impl Debug for StrictVerifyingKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        Debug::fmt(&self.zip215, f)
    }
}

impl Display for StrictVerifyingKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        Display::fmt(&self.zip215, f)
    }
}

impl AsRef<[u8]> for StrictVerifyingKey {
    fn as_ref(&self) -> &[u8] {
        self.zip215.as_ref()
    }
}

impl Deref for StrictVerifyingKey {
    type Target = [u8];

    fn deref(&self) -> &Self::Target {
        self.zip215.as_ref()
    }
}

impl Write for StrictVerifyingKey {
    fn write(&self, buf: &mut impl BufMut) {
        self.zip215.write(buf);
    }
}

impl FixedSize for StrictVerifyingKey {
    const SIZE: usize = 32;
}

impl Span for StrictVerifyingKey {}

impl Array for StrictVerifyingKey {}

impl Read for StrictVerifyingKey {
    type Cfg = ();

    fn read_cfg(buf: &mut impl Buf, cfg: &Self::Cfg) -> Result<Self, commonware_codec::Error> {
        let bytes = <[u8; Self::SIZE]>::read_cfg(buf, cfg)?;
        let point = GAffine::decompress(&bytes)
            .map(GAffine::to_extended)
            .filter(|point| point.to_bytes() == bytes)
            .filter(|point| !point.is_identity() && prime_order_product(*point).is_identity())
            .ok_or(commonware_codec::Error::Invalid(
                "curve25519::StrictVerifyingKey",
                "public key is not a canonical non-identity prime-order point",
            ))?;
        Ok(Self {
            zip215: VerifyingKey {
                bytes: core::VerifyingKeyBytes::new(bytes),
                point: Some(point),
            },
        })
    }
}

#[cfg(feature = "arbitrary")]
impl arbitrary::Arbitrary<'_> for StrictVerifyingKey {
    fn arbitrary(u: &mut arbitrary::Unstructured<'_>) -> arbitrary::Result<Self> {
        Ok(SigningKey::from_seed(u.arbitrary()?).strict_verifying_key())
    }
}

impl StrictVerifyingKey {
    /// Returns the ZIP215 view of this validated identity key.
    pub const fn as_zip215(&self) -> &VerifyingKey {
        &self.zip215
    }

    /// Verifies a signature over a namespaced message.
    #[must_use]
    pub fn verify(&self, namespace: &[u8], msg: &[u8], sig: &Signature) -> bool {
        self.zip215.verify(namespace, msg, sig)
    }
}

impl commonware_cryptography::PrivateKey for SigningKey {}

impl commonware_cryptography::Signer for SigningKey {
    type Signature = Signature;
    type PublicKey = StrictVerifyingKey;

    fn public_key(&self) -> Self::PublicKey {
        self.strict_verifying_key()
    }

    fn sign(&self, namespace: &[u8], msg: &[u8]) -> Self::Signature {
        Self::sign(self, namespace, msg)
    }
}

impl commonware_cryptography::PublicKey for StrictVerifyingKey {}

impl commonware_cryptography::Verifier for StrictVerifyingKey {
    type Signature = Signature;

    fn verify(&self, namespace: &[u8], msg: &[u8], sig: &Self::Signature) -> bool {
        Self::verify(self, namespace, msg, sig)
    }
}

impl commonware_cryptography::Signature for Signature {}

/// An Ed25519 signature.
///
/// For an honestly generated [`VerifyingKey`], successful verification demonstrates approval by
/// the holder of the corresponding [`SigningKey`]. A maliciously generated verifying key can
/// admit a signature that verifies for any message.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Signature {
    bytes: [u8; 64],
}

impl Debug for Signature {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", Hex(&self.bytes))
    }
}

impl Display for Signature {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", Hex(&self.bytes))
    }
}

impl AsRef<[u8]> for Signature {
    fn as_ref(&self) -> &[u8] {
        &self.bytes
    }
}

impl Deref for Signature {
    type Target = [u8];

    fn deref(&self) -> &Self::Target {
        &self.bytes
    }
}

impl Write for Signature {
    fn write(&self, buf: &mut impl BufMut) {
        self.bytes.write(buf);
    }
}

impl FixedSize for Signature {
    const SIZE: usize = 64;
}

impl Span for Signature {}

impl Array for Signature {}

impl Read for Signature {
    type Cfg = ();

    fn read_cfg(buf: &mut impl Buf, cfg: &Self::Cfg) -> Result<Self, commonware_codec::Error> {
        Ok(Self {
            bytes: <[u8; Self::SIZE]>::read_cfg(buf, cfg)?,
        })
    }
}

#[cfg(feature = "arbitrary")]
impl arbitrary::Arbitrary<'_> for Signature {
    fn arbitrary(u: &mut arbitrary::Unstructured<'_>) -> arbitrary::Result<Self> {
        Ok(Self {
            bytes: u.arbitrary()?,
        })
    }
}

/// Inputs retained for batch verification.
///
/// The encoded key is the batch pipeline's authoritative identity. Its optional decoded point is
/// an individual-verification cache and is not part of the queued state.
struct BatchItem {
    message: Vec<u8>,
    public_key: core::VerifyingKeyBytes,
    signature: core::Signature,
}

/// A batch verification context.
pub struct BatchVerifier {
    items: Vec<BatchItem>,
}

impl BatchVerifier {
    /// Creates a verifier with space for `capacity` signatures.
    pub fn new(capacity: usize) -> Self {
        Self {
            items: Vec::with_capacity(capacity),
        }
    }

    /// Queues a signature for verification over the namespaced message.
    pub fn add(
        &mut self,
        namespace: &[u8],
        message: &[u8],
        public_key: &VerifyingKey,
        signature: &Signature,
    ) {
        self.items.push(BatchItem {
            message: union_unique(namespace, message),
            public_key: public_key.bytes,
            signature: core::Signature::from_bytes(signature.bytes),
        });
    }

    /// Checks all the signatures in the batch.
    ///
    /// Empty batches and batches containing more than `u32::MAX` signatures are rejected. Within
    /// that limit, a non-empty batch is always accepted when every signature verifies individually
    /// under the [module's validation criteria](self). Because this checks a randomized linear
    /// combination, an invalid batch may be accepted when the random weights make the combined
    /// equation hold, an event of negligible probability (about `2^-128`).
    #[must_use]
    pub fn verify(self, rng: &mut impl CryptoRng, strategy: &impl Strategy) -> bool {
        let items = self
            .items
            .iter()
            .map(|item| (&item.public_key, &item.signature, item.message.as_slice()));
        core::verify_batch_bytes(rng, items, strategy)
    }
}

impl commonware_cryptography::BatchVerifier for BatchVerifier {
    type PublicKey = StrictVerifyingKey;

    fn new(capacity: usize) -> Self {
        Self::new(capacity)
    }

    fn add(
        &mut self,
        namespace: &[u8],
        message: &[u8],
        public_key: &Self::PublicKey,
        signature: &<Self::PublicKey as commonware_cryptography::Verifier>::Signature,
    ) -> bool {
        Self::add(self, namespace, message, public_key.as_zip215(), signature);
        true
    }

    fn verify<R: CryptoRng>(self, rng: &mut R, strategy: &impl Strategy) -> bool {
        Self::verify(self, rng, strategy)
    }
}

#[cfg(test)]
mod tests {
    use super::{BatchItem, BatchVerifier, Signature, SigningKey, StrictVerifyingKey};
    use crate::curve::{G, GAffine};
    use commonware_codec::{DecodeExt, Encode};
    use commonware_parallel::Sequential;
    use commonware_utils::test_rng;

    const NAMESPACE: &[u8] = b"_COMMONWARE_CRYPTOGRAPHY_CURVE25519_SIGNING_TEST";

    fn torsion_points() -> [G; 8] {
        let generator_encoding = [
            0xc7, 0x17, 0x6a, 0x70, 0x3d, 0x4d, 0xd8, 0x4f, 0xba, 0x3c, 0x0b, 0x76, 0x0d, 0x10,
            0x67, 0x0f, 0x2a, 0x20, 0x53, 0xfa, 0x2c, 0x39, 0xcc, 0xc6, 0x4e, 0xc7, 0xfd, 0x77,
            0x92, 0xac, 0x03, 0x7a,
        ];
        let generator = GAffine::decompress(&generator_encoding)
            .unwrap()
            .to_extended();
        let mut points = [G::IDENTITY; 8];
        for i in 1..points.len() {
            points[i] = points[i - 1].add(generator);
        }
        assert!(points[7].add(generator).is_identity());
        points
    }

    #[test]
    fn batch_items_do_not_retain_decoded_key_cache() {
        assert_eq!(
            core::mem::size_of::<BatchItem>(),
            core::mem::size_of::<(Vec<u8>, [u8; 32], super::core::Signature)>(),
        );
    }

    #[test]
    fn empty_batch_is_invalid() {
        assert!(!BatchVerifier::new(0).verify(&mut test_rng(), &Sequential));
    }

    #[test]
    fn signature_is_bound_to_namespace() {
        const WRONG_NAMESPACE: &[u8] = b"_COMMONWARE_CRYPTOGRAPHY_CURVE25519_SIGNING_TEST_WRONG";

        let signing_key = SigningKey::from_seed([42; 32]);
        let verifying_key = signing_key.verifying_key();
        let message = b"message";
        let signature = signing_key.sign(NAMESPACE, message);

        assert!(verifying_key.verify(NAMESPACE, message, &signature));
        assert!(!verifying_key.verify(WRONG_NAMESPACE, message, &signature));
    }

    #[test]
    fn strict_key_roundtrips_and_verifies() {
        let signing_key = SigningKey::from_seed([7; 32]);
        let cloned = signing_key.clone();
        let verifying_key = signing_key.strict_verifying_key();
        let signature = cloned.sign(NAMESPACE, b"message");

        assert!(verifying_key.verify(NAMESPACE, b"message", &signature));
        assert_eq!(
            StrictVerifyingKey::decode(verifying_key.encode()).unwrap(),
            verifying_key,
        );
        assert_eq!(cloned.encode(), signing_key.encode());
    }

    #[test]
    fn workspace_signing_traits_use_strict_keys() {
        fn assert_private_key<T>()
        where
            T: commonware_cryptography::PrivateKey
                + commonware_cryptography::Signer<
                    Signature = Signature,
                    PublicKey = StrictVerifyingKey,
                >,
        {
        }
        fn assert_public_key<T>()
        where
            T: commonware_cryptography::PublicKey
                + commonware_cryptography::Verifier<Signature = Signature>,
        {
        }
        fn assert_signature<T: commonware_cryptography::Signature>() {}
        fn assert_batch<T>()
        where
            T: commonware_cryptography::BatchVerifier<PublicKey = StrictVerifyingKey>,
        {
        }

        assert_private_key::<SigningKey>();
        assert_public_key::<StrictVerifyingKey>();
        assert_signature::<Signature>();
        assert_batch::<BatchVerifier>();

        let signing_key = <SigningKey as commonware_cryptography::Signer>::from_seed(7);
        let public_key = commonware_cryptography::Signer::public_key(&signing_key);
        let message = b"message";
        let signature = commonware_cryptography::Signer::sign(&signing_key, NAMESPACE, message);
        let mut batch = <BatchVerifier as commonware_cryptography::BatchVerifier>::new(1);
        assert!(commonware_cryptography::BatchVerifier::add(
            &mut batch,
            NAMESPACE,
            message,
            &public_key,
            &signature,
        ));
        assert!(commonware_cryptography::BatchVerifier::verify(
            batch,
            &mut test_rng(),
            &Sequential,
        ));
    }

    #[test]
    fn strict_key_rejects_torsion_and_torsion_cosets() {
        let torsion = torsion_points();
        let basepoint = GAffine::BASEPOINT.to_extended();
        let prime_points = [
            basepoint,
            basepoint.double(),
            basepoint.double().double().add(basepoint),
        ];

        for point in torsion {
            assert!(StrictVerifyingKey::decode(point.to_bytes().as_slice()).is_err());
        }
        for prime_point in prime_points {
            for (i, torsion_point) in torsion.into_iter().enumerate() {
                let bytes = prime_point.add(torsion_point).to_bytes();
                assert_eq!(StrictVerifyingKey::decode(bytes.as_slice()).is_ok(), i == 0);
            }
        }
    }

    #[test]
    fn strict_key_rejects_noncanonical_malformed_and_misframed_encodings() {
        let mut identity = [0u8; 32];
        identity[0] = 1;
        let mut negative_zero = identity;
        negative_zero[31] |= 0x80;
        let order_four_positive = [0u8; 32];
        let mut order_four_negative = order_four_positive;
        order_four_negative[31] |= 0x80;
        let mut order_two_negative_zero = [0xff; 32];
        order_two_negative_zero[0] = 0xec;
        for bytes in [
            identity,
            negative_zero,
            order_four_positive,
            order_four_negative,
            order_two_negative_zero,
        ] {
            assert!(StrictVerifyingKey::decode(bytes.as_slice()).is_err());
        }

        for offset in 0..19 {
            let mut bytes = [0xff; 32];
            bytes[0] = 0xed + offset;
            for sign in [0, 0x80] {
                bytes[31] = 0x7f | sign;
                assert!(StrictVerifyingKey::decode(bytes.as_slice()).is_err());
            }
        }

        let off_curve = (0u8..=u8::MAX)
            .map(|first| {
                let mut bytes = [0u8; 32];
                bytes[0] = first;
                bytes
            })
            .find(|bytes| GAffine::decompress(bytes).is_none())
            .unwrap();
        assert!(StrictVerifyingKey::decode(off_curve.as_slice()).is_err());

        let valid = SigningKey::from_seed([8; 32])
            .strict_verifying_key()
            .encode();
        for len in 0..valid.len() {
            assert!(StrictVerifyingKey::decode(&valid[..len]).is_err());
        }
        let mut trailing = valid.to_vec();
        trailing.push(0);
        assert!(StrictVerifyingKey::decode(trailing.as_slice()).is_err());
    }

    #[test]
    fn signing_key_zeroizes_on_drop() {
        fn assert_zeroize_on_drop<T: zeroize::ZeroizeOnDrop>() {}

        assert_zeroize_on_drop::<SigningKey>();
        assert!(core::mem::needs_drop::<SigningKey>());
    }

    #[cfg(feature = "arbitrary")]
    mod conformance {
        use super::super::{Signature, SigningKey, StrictVerifyingKey, VerifyingKey};
        use commonware_codec::conformance::CodecConformance;

        commonware_conformance::conformance_tests! {
            CodecConformance<SigningKey> => 1024,
            CodecConformance<VerifyingKey>,
            CodecConformance<StrictVerifyingKey> => 1024,
            CodecConformance<Signature>,
        }
    }
}
