            mov {tmp:w}, #0x80
            ins v4.b[0], {tmp:w}
            ins v8.b[0], {tmp:w}
            rev32.16b v4, v4
            rev32.16b v8, v8
            mov {tmp:w}, #512
            ins v7.s[3], {tmp:w}
            ins v11.s[3], {tmp:w}
            mov {k}, {k_start}
