            ld1.8b {{v4}}, [{left_right}]
            ld1.8b {{v8}}, [{right_right}]
            mov {tmp:w}, #0x80
            ins v4.b[8], {tmp:w}
            ins v8.b[8], {tmp:w}
            rev32.16b v4, v4
            rev32.16b v8, v8
            mov {tmp:w}, #576
            ins v7.s[3], {tmp:w}
            ins v11.s[3], {tmp:w}
            mov {k}, {k_start}
