//! FN-DSA (Falcon) implementation of the [crate::Verifier] and [crate::Signer] traits.
//!
//! FN-DSA is the lattice-based signature scheme that NIST selected (as Falcon) for
//! standardization in FIPS 206. It is designed to remain secure against adversaries with quantum
//! computers and has much smaller signatures than [crate::ml_dsa]. Two parameter sets are
//! provided:
//!
//! | Variant | Security | Public key | Signature |
//! |---------|----------|------------|-----------|
//! | [FnDsa512] | NIST category 1 | 897 bytes | 666 bytes |
//! | [FnDsa1024] | NIST category 5 | 1793 bytes | 1280 bytes |
//!
//! # Status
//!
//! **This module is experimental.** FIPS 206 has not been published, and the underlying
//! [fn-dsa](https://crates.io/crates/fn-dsa) crate (0.x) warns that its key encodings, message
//! pre-hashing, and domain separation may change to match the final standard. Keys and signatures
//! produced here are not guaranteed to interoperate with FIPS 206 implementations, and the
//! encodings below may change without a migration path.
//!
//! # Encoding
//!
//! - Private keys are encoded as a 32-byte seed. The key pair is generated by fn-dsa from a
//!   SHAKE256 stream keyed by the seed, so equal seeds always produce equal keys. Key generation
//!   takes milliseconds, so it runs once when a key is created or decoded.
//! - Public keys use the Falcon encoding of the public polynomial (a header byte followed by
//!   14-bit coefficients). Decoding rejects coefficients that are not reduced modulo `q`.
//! - Signatures use the Falcon encoding (a header byte, a 40-byte nonce, and a compressed,
//!   zero-padded vector). Decoding rejects any encoding that verification would fail to parse,
//!   so every decoded signature is well-formed and has exactly one encoding.
//!
//! # Signing
//!
//! Messages are signed with an empty FN-DSA context string and no pre-hashing, after prefixing
//! the namespace with [commonware_utils::union_unique] like every other [crate::Signer] in this
//! crate.
//!
//! Falcon signing samples a short lattice vector and is randomized by design. fn-dsa derives the
//! sampler seed (which also determines the nonce) as SHAKE256 of a hash of the secret key, the
//! message representative, and 40 caller-supplied random bytes. This module supplies 40 zero
//! bytes, so the seed is a secret, per-message pseudorandom value and signing is deterministic:
//! signing the same namespace and message with the same key always yields identical bytes, which
//! never reveals two different short vectors for one hashed target. Signatures are valid
//! signatures for any verifier, which cannot distinguish them from randomized ones, and
//! [PublicKey] accepts randomized signatures over the same payload.
//!
//! Deterministic signing differs from the hedged signing that FIPS 206 may require: like other
//! deterministic lattice signatures, it is more exposed to fault attacks (a fault injected while
//! signing a message that is also signed without a fault can leak information about the key).
//! Signing uses floating-point arithmetic, which fn-dsa runs natively on x86_64 and aarch64 and
//! emulates elsewhere.
//!
//! # Example
//! ```rust
//! use commonware_cryptography::{fn_dsa, PrivateKey, PublicKey, Signature, Verifier as _, Signer as _};
//! use commonware_math::algebra::Random;
//! use commonware_utils::test_rng;
//!
//! let mut rng = test_rng();
//!
//! // Generate a new private key
//! let signer = fn_dsa::PrivateKey::<fn_dsa::FnDsa512>::random(&mut rng);
//!
//! // Create a message to sign
//! let namespace = b"demo";
//! let msg = b"hello, world!";
//!
//! // Sign the message
//! let signature = signer.sign(namespace, msg);
//!
//! // Verify the signature
//! assert!(signer.public_key().verify(namespace, msg, &signature));
//! ```

/// Instantiates each generic test (a function `super::$test::<V>()`) for every [Variant].
#[cfg(test)]
macro_rules! variant_tests {
    ($($(#[$attr:meta])* $test:ident),* $(,)?) => {
        mod fn_dsa_512 {
            $($(#[$attr])* #[test] fn $test() { super::$test::<$crate::fn_dsa::FnDsa512>(); })*
        }
        mod fn_dsa_1024 {
            $($(#[$attr])* #[test] fn $test() { super::$test::<$crate::fn_dsa::FnDsa1024>(); })*
        }
    };
}
#[cfg(test)]
use variant_tests;

pub mod certificate;
mod scheme;

pub use scheme::{FnDsa512, FnDsa1024, PrivateKey, PublicKey, Signature, Variant};
