[package]
name = "commonware-websocket"
edition.workspace = true
publish = true
version.workspace = true
license.workspace = true
description = "Carry Commonware byte streams over WebSocket."
homepage.workspace = true
repository = "https://github.com/commonwarexyz/monorepo/tree/main/websocket"
documentation = "https://docs.rs/commonware-websocket"

[lints]
workspace = true

[dependencies]
bytes.workspace = true
commonware-macros.workspace = true
commonware-runtime.workspace = true
commonware-utils = { workspace = true, features = ["std"] }
futures.workspace = true
thiserror.workspace = true
url.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
commonware-runtime = { workspace = true, features = ["web"] }
js-sys = "0.3.77"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = [
	"BinaryType",
	"CloseEvent",
	"ErrorEvent",
	"Event",
	"EventTarget",
	"MessageEvent",
	"WebSocket",
	"Window",
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["net"] }
tokio-tungstenite = { workspace = true, default-features = false, features = ["handshake"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lib]
bench = false
