name: Bash-Lint
on:
  pull_request:
    branches:
      - main
jobs:
  shellcheck:
    name: Run Shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run Shellcheck
      run: find scripts -name "*.sh" -print0 | xargs -0 shellcheck --shell=bash