name: Crates

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install protoc
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    - name: Publish p2p
      run: cargo publish --manifest-path p2p/Cargo.toml
      continue-on-error: true
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    - name: Publish chat
      run: cargo publish --manifest-path examples/chat/Cargo.toml
      continue-on-error: true
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}