name: Tests 

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  All:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install protoc
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-
    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-
    - name: Lint with clippy
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test --verbose