name: Tests 

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  All:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/checkout
    - name: Lint with clippy
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test --verbose
  
  Dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/checkout
    - name: Install nightly Rust toolchain
      run: rustup toolchain install nightly
    - name: Install cargo-udeps
      run: cargo install cargo-udeps
    - name: Check for unused dependencies
      run: cargo +nightly udeps