name: Tests (Slow)

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: tests-slow-${{ github.head_ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always

jobs:
  Slow:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        features:
          - "--features commonware-runtime/iouring-storage"
          - "--features commonware-runtime/iouring-network"
          - ""
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run setup
      uses: ./.github/actions/setup
    - name: Run ignored tests
      run: cargo test ${{ matrix.features }} --verbose -- --ignored
